version: '1.0.{build}'
skip_tags: true

install:
  - ps: choco install -y miktex
  - cmd: refreshenv

before_build:

build_script:
  - cmd: pdflatex  --synctex=1 -interaction=nonstopmode -file-line-error -recorder  essays.tex
  - cmd: pdflatex  --synctex=1 -interaction=nonstopmode -file-line-error -recorder  essays.tex
  - cmd: pdflatex  --synctex=1 -interaction=nonstopmode -file-line-error -recorder  essays.tex

after_build:
  - ps: 7z a essays.zip *.pdf

artifacts:
  - path: essays.zip
    name: essays

deploy:
  release: essays-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: x2VCjhjls6MUIYqj+WN0D5Db4HA3hTIep++8jGWbSQtnGcPMfzj5gWW39ZNg1z/5
  artifact: essays.zip
  force_update: true
  draft: false
  prerelease: false
  appveyor_repo_tag: false
