#+TITLE: \zihao{0} *书香铭心*
#+SUBTITLE: \zihao{1} 作文集
#+AUTHOR: \zihao{2} 舒铭
#+DATE:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [UTF8,a4paper,titlepage,twoside,10.5pt]
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[heading=true]{ctex}
#+LATEX_HEADER: \usepackage[left=2.2cm,right=2.0cm,top=2.2cm,bottom=2.2cm]{geometry}
#+LATEX_HEADER: \hypersetup{colorlinks=true,linkcolor=blue}

#+LATEX: \pagestyle{headings}
#+LATEX: \newpage
#+LATEX: \pagestyle{fancy}
#+LATEX: \fancyhf{}
#+LATEX: \fancyhead[LE,RO]{\leftmark}
#+LATEX: \fancyfoot[LE,RO]{\thepage}
#+LATEX: \setcounter{page}{1}
#+LATEX: \pagenumbering{arabic}

#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:nil toc:t todo:t |:t

* 一年级——牙牙学语

** 开学第一天

   今天是 8 月 30 日，是我小学报到的日子。我早上起得很早，想到马上就要上小学了，心里很高兴。妈妈陪我一起到了树人小学，找啊找，终于找到了我的新班级一（8）班，那里已经坐了很多小朋友，还有两位老师。等我们全到齐了，老师先说了上课的纪律。然后，我们几个男生在老师的带领下，一起去领新书。在第三趟领书时，我捧的书太重了，老师让另外一个小朋友帮我一起搬。虽然有点累，但想到劳动最光荣时，我还是觉得很开心。领完书，布置好作业，老师带我们去参观了学校。学校比幼儿园大多了，有生物园、体育馆、图书馆等。在校门口，我还看到了一个小邮局和红领巾超市。然后，我们在老师的带领下，排好队伍走到校门口，妈妈已经在那里等我了，我又渴又累，但拎着新书，又兴奋又开心。[fn:1]

** 做冰皮月饼

   快到中秋了，妈妈给我报名参加了一个做冰皮月饼的活动。那天下午，我和外婆、妈妈一起去做月饼。我很高兴，很早就到了，和其他小朋友在休息的地方玩气球。活动马上开始了，妈妈是帮忙做义工的，分给大家已经准备好的面粉团。我穿上倒背衣，准备好小脸盆，我很着急啊，真想马上就能做好月饼。我和外婆一起揉面团，就像玩橡皮泥一样，放上陷，弄好后用模具一压，一个漂亮的冰皮月饼就做好了。我们一共做了 3 个，把分到的面团全用完了。在老师的指导下，我又用紫薯做一个月饼。全部做好了，我好开心啊，一口气吃了 2 个，软软的，甜甜的，很好吃哦。

** 重阳节

   今天是重阳节，重阳节是老人的节日。爷爷、奶奶、外公、外婆都不在我身边，但我都给他们打电话问候了一声。晚上，我帮妈妈端盘子、叠衣服，做了一点小事。孝敬长辈，从身边的小事做起。比如，上星期六，天气很好，我和妈妈陪外婆游了东湖，还一起爬了山。东湖的景色真美啊！外婆看了心里美滋滋的，脸上的笑容像朵花，我心里也很开心！

** 游青藤书屋和周恩来祖居

   今天早上，我本来想去大禹陵玩，但昨晚下了雨，一早又阴沉沉的，所以，妈妈带我去了青藤书屋。我们走进一条窄窄的石板小路，后来才知道那条小路叫大乘弄。走了一会儿，看到灰墙、黑瓦，很醒目的地方，那里就是青藤书屋了。里面地方很小，我看到了青藤、水池、两间屋子，屋子里陈列着徐渭的各种字画和介绍。

   然后，时间还早，我们去了周恩来祖居，也是灰墙黑瓦，里面比青藤书屋大很多。我们看了少年周恩来生活的地方，还参观了周恩来纪念馆。我跟着导游，听了很多有关周总理的介绍。我有点听不懂，妈妈说，等我大一点了，再带我来参观和学习。

** 读《看不见的朋友》有感

   今天，我看了张秋生写的《看不见的朋友》这个故事。这个童话里的主角是小兔子长耳朵，他在草原上盖了一座美丽的新房子。他有很多看不见的朋友，有壁虎、猫头鹰、蚯蚓、小蜜蜂，他们帮了他很多忙，他们在一起很开心。

   我身边也有很多人在默默地关心、帮助我，比如妈妈、学校的老师、小朋友，我也要谢谢他们。

** 游儿童公园

   今天天气很好，爸爸妈妈带我一起去儿童公园。我们玩了很多好玩的。我玩了摇头飞椅、激光战车、汽油赛车、母子车等等。我最喜欢“摇头飞椅”了，因为很刺激，虽然我头很晕。在玩“汽油赛车”时，爸爸和我开的车撞了两次，撞得我有点痛。第一次撞后，工作人员赶紧跑过来帮忙。在玩“高驾车”时，一开始，妈妈不大会开，一直说很害怕，我却一点儿都不害怕，后来她调整车的方向，终于好了。在玩“过山车”时，前面很好，但后来车在轨道上快速前进，太刺激了！还有母子车，一开始是我和妈妈，后来妈妈让爸爸陪我开。所有的项目都很好玩，我玩得很开心！

** 宝贵的水，需要你我来珍惜

   寒假里，我和爸爸妈妈一起去了科技馆，参观了“身边水资源”科普展。

   在那里，我看到了各种各样的东西，比如关于节水的图片、文字、实物介绍，还玩了不少用高科技制作的东西。边看边玩，我才知道水的重要性，更明白了水的用处有各种各样。

   我们的生活离不开水，水在工业中也不可缺少，但很多地方都缺水。在“小孔观图器”中，我透过上面的小孔看到了一个满脸皱纹的老奶奶，为了家里用水，只能背着一个桶，到很远的山上去打水。因为桶太重，她不得不背一程歇一程，刚好一位记者来采访，帮她把水背到家。她用水很节约，还把用过的水洗衣服、洗脸、喂猪；我还看到一群村民因为家里缺水，也只能去附近的洞里找水，可惜洞外没有水，洞里没有水，洞的最深处还是没有水……看到干旱的地方人们用水这么辛苦，我以后一定不要乱用水了，帮助干旱的地方。

   这次参观，我还学到了不少节水的小窍门，收获真不少。回家后，我就马上行动起来，从小事做起，比如每次都把用过的水来冲马桶。我觉得水真的很宝贵，需要我们大家一起来珍惜。[fn:2]

** 春天来了

   冬天过去了，春天来了。万物复苏，春回大地，一种美丽的气派在我们面前出现了。春天多么美丽啊！百花齐放，百鸟争鸣，这是非常美的景色。春光明媚真是好！桃花开了，牡丹花开了，月季花开了，樱花也开了，各种各样的花都开了，各种鸟都在叫。春天来了，快来迎接春天吧！[fn:3]

** 家

   *家*[fn:4]

   来吧，来吧，

   这就是我们的天地，

   我们玩，我们学，

   我们生活，我们嬉戏。

   我们是这艘漂亮船舰中的船员，

   爸爸是船长，妈妈是舵手，

   护着我这个小船员。

   开来开去，开去开来。

   家是一艘神奇的航空母舰，

   收藏着我们一家人全部的甜蜜！

   #+LATEX: \vspace*{\baselineskip}

   *家　(原稿)*

   来吧，来吧，

   这就是我们的天地，

   我们玩，我们学，

   我们学，我们玩。

   我们是这个家庭的船员，

   爸爸是正船长，妈妈是副船长，

   护着我这个小船员。

   开来开去，开去开来。

   家是一艘漂亮快乐的船，

   值得我们学习的船！

** 亚龙湾

   下午，我和妈妈、外婆跟着旅游团，一起去亚龙湾。

   我看见那里的天是那么蓝，海那么宽，一浪高过一浪。我借了一个游泳圈，在游泳处游泳。我觉得那里的水凉凉的。浪冲过来时，我有点害怕。

** 乘飞机有感

   今天傍晚，我和妈妈、外婆一起乘飞机回家。在候机室旁，有免税店，那里有很多东西。我们等了很长时间，终于登上了飞机。我在飞机上吃了航空食物。飞机正式起飞了，轰轰轰的声音，像打雷似得，我感觉耳朵都快要震聋了。我从窗外望去，我看到了南海渐渐离我而去，飞机越飞越高，往下看，夜景十分好看。后面飞到云霄里了，周围都是云，有的像大白马，有的像小船，有的像树叶，有一个还有点像我的妈妈。看了一会，我累了，不知不觉睡着了。等我醒来，飞机快降落了。我感觉乘飞机真好玩。

** 江苏盱眙游

   今天我和妈妈、外婆去江苏盱眙。我们去了铁山寺，里面有孔雀园、黄檀园、葛藤园、蟒蛇涧。我听导游说，铁山寺有 800 种中草药。铁山寺是拜佛胜地。我们到了大雄宝殿，拜了佛。我们又去了都梁阁，都梁阁里有博物馆。因为我们去的有点迟了，所以关门了。我们拍了照，望望下面的美景。第二天，我们先去了明祖陵。明朝朱元璋的祖父、曾祖父都埋葬在那里。江苏真美呀！

** 在江苏盱眙吃龙虾

   今天晚上，我和妈妈、外婆一起在江苏盱眙吃龙虾，我感觉龙虾很辣。我们吃了许多龙虾。那里的导游介绍说，吃龙虾有五个步骤，第一步是亲亲它的手，第二步是轻轻吻一口，第三步是掀起红盖头，第四步是脱下红肚兜，第五步是抽出白丝带。

   #+LATEX: \newpage

* 二年级——新手起步

** 家里来了小客人

   表弟到我家来，他帮我听写。我们玩了磁石跳棋，我们开了小鸡小鸭小饭店，又玩了五子棋、小恐龙。我玩得很开心，表弟也很开心。

** 恐龙园游记

   今天我和妈妈一起去了大禹陵景区里的恐龙园。公园门口有“马门溪龙”和“霸王龙”的化石。

   进了恐龙园，我看到很多恐龙——有最丑的肿头龙、最大的地震龙、声音最响的雷龙……

   我骑到了霸王龙上，做了一回骑士，感觉既高兴又兴奋。我还钻进了恐龙蛋里玩。我玩得很开心！

   在那里，我学了很多恐龙的知识，今天收获真不少啊！

** 中秋做月饼

   今天我和爸爸妈妈一起去书圣故里做月饼。

   白白的粉，黄黄的皮，各种各样颜色的陷。我一下做了四个月饼。月饼都是我一个人做的，大家都夸我做得好哦。第一步把皮压扁，然后再放上陷，最后用模具一压，就成了一个黄金月饼。

   今天收获真不少，自己做的月饼最香甜。

** 第一次做老板

   今天，妈妈带我去跳蚤市场卖东西。妈妈对我说：“铭铭，你得仔细一点呀！”

   一开始，我有点紧张，过了一会儿，看见有些小朋友正在看我的东西，我紧张的心情马上就平静下来。我卖了不少东西，赚了一笔“大钱”呢！

** 游大香林

   今天，妈妈和外婆带我乘 603 路公交车去大香林风景区游玩，那里有很多很多桂花，有金桂、银桂、梅桂、丹桂、早桂 5 种桂花，正竞相开放，还有中国桂花王，那个桂花竟然有 987 岁哦。桂花散发出清新的香气，闻着花香，我都要陶醉了。

   游玩了美丽的大香林，我们又去了旁边的龙华寺，那里的建筑非常壮观。那里有各种各种的庙堂，我拜了观音菩萨、文殊菩萨、灵吉菩萨、如来等菩萨。我玩得很开心，以后还要来大香林玩。

** 去学校看桂花

   今天，我想起了昨天看桂花的情景，桂花黄黄的，黄得像一颗颗珍珠。还香香的，好像苹果，我都要陶醉了。我以后要做科学家，想办法让桂花四季竞相开放，我一定会实现这个梦想。

** 快乐的秋游

   星期五，我们二(8)班去名人广场秋游。我们先到了名人墙，那里有许多“名人”，比如勾践、大禹、鲁迅、周恩来……我们又观看了名人广场里的名人塑像，上面因为年代久了，有绿绿的像青铜一样的颜色。

   我和小朋友玩了一会儿接力赛。我们一起分享美食。

   这一次秋游，我不仅玩得高兴，还收获了不少知识，真是不虚此行啊！

** 《熊出没》观后感

   我是《熊出没》忠实的小观众。聪明的熊大、臭美的熊二、狡猾的光头强、英明的李老板……他们在森林里面，在嘻嘻哈哈的打闹中，表演了一个个可笑的故事。

   我最喜欢熊二，他用蛮力一次次打败了光头强。他虽然贪吃，不过很可爱。他们保护森林的勇气和行为值得我们学习。我们也要多种种树。

** 假如

   假如我有一枝

   马良的神笔，

   我要给没有看过电影的人

   画一个投影仪，

   让他们看着精彩的电影，

   不会孤孤单单地生活着。

   #+LATEX: \vspace*{\baselineskip}

   假如我有一枝

   马良的神笔，

   我要给动物们

   画一片茂密的森林，

   让小动物们自由自在地生活，

   不再受到猎人的侵袭，

   快快乐乐地做着游戏。

   #+LATEX: \vspace*{\baselineskip}

   假如我有一枝

   马良的神笔，

   我要给没有妈妈的孩子，

   画一颗爱心，

   让他们受到妈妈的爱，

   过着幸福的生活，

   不会孤单地生活。

   #+LATEX: \vspace*{\baselineskip}

   假如我有一枝

   马良的神笔……

** 去名人广场玩

   星期六，我和爸爸妈妈一起去名人广场玩。我看见那里有许多落叶，一看原来是银杏树的叶子啊，像一只只黄黄的蝴蝶。

   是冬天来了吧！我要更懂事，更有礼貌，做一个好孩子。

   接着，我又去了名人广场的另一边。在那里，我跟爸爸一起玩。我感觉天更加蓝，阳光更加灿烂温暖。

   我玩得很开心！

** 和弟弟一起玩

   今天下午，我和弟弟到罗门公园玩。走到罗门公园，我们一起拍皮球。拍了一会儿，我们又去喂小鱼。我们把一些发了霉、长了毛的面包丢进水里。小鱼看见了，就游了过去津津有味地吃着面包。看着它们高兴，我也很高兴。

   但是，我又有点担心小鱼们吃了这些面包会不会肚子疼。我去问爸爸，爸爸告诉我，小鱼应该不会有事的，它们的肚子和人是不一样的。

   在罗门公园，我们又玩了“老鹰抓小鸡”，这个游戏又刺激又好玩。我和弟弟又背了乘法口诀表，又对了乘法口令。今天的收获真不少啊。

** 做蛋饺

   今天，奶奶教我做蛋饺。我看见厨房里摆着许多调料。我们用油、蛋汤，还有肉和红萝卜搅拌而成的馅。过了一会儿，奶奶拿出一个小勺子，对我说：“铭铭，做蛋饺，首先，把勺子在煤气灶上烤，第二步，把油放在勺子里，把蛋汤放进去。再把肉和红萝卜搅拌而成的馅放进去，再把它像包饺子一样包好，然后在蒸笼里蒸一蒸。”

   我做了几只，终于学会了。晚上吃饭，我还觉得自己做的就是香呀！

** 包饺子

   今天，我和爸爸一起包饺子。因为今天下雨，所以我们只能包饺子。爸爸切完肉，我洗完手，一起包饺子。包完以后，爸爸烧完饺子，大家一起吃饺子。爸爸妈妈都夸我包的饺子鲜，我听了心里美滋滋的。

** 种树

   今天，我和妈妈去参加植树活动。我们来到迪荡新城的梅龙湖公园。那里非常泥泞。我们走到植树的地方，坑已经事先挖好了，坑里面有很多黄土。工作人员把一棵棵很大的桂花树抬了过来。我们一起把树苗放入坑中。我和其他人拿铁锹培土，然后把土压实。忙了好一会儿，总算把树种好了。

   参加了这次活动，我觉得要多种树，才能让古城绍兴更加生机勃勃。

** 去荷湖村游玩

   今天，我和妈妈乘 8 路车去荷湖村游玩。那里有荷花的雕像，小桥流水。

   在村委的带领下，我们参观了农耕博物馆，那里有很多农耕器具，比如山袜、蓑衣、漏斗、织布机、石磨、水车……

   我们还去了防空洞。里面有古墓、瞭望台。今天我玩得真开心啊！

** 镜湖湿地公园踏春

   今天，我和妈妈去镜湖湿地公园。来到那里，有很多人在放风筝，还有粉红色的桃花，嫩绿的杨柳，金黄色的油菜花，五光十色，美丽极了。我还采了艾草和马兰头，这两样东西可以吃哦。我还去了庙堂，拜了菩萨，抽了签。

   沐浴着温暖的春光，我被迷人的春光陶醉了！

** 我的孝心事（外一篇）

   *我的孝心事*[fn:5]

   谁言寸草心，报得三春晖。孝是中华民族的传统美德，我们一定要孝敬长辈。妈妈告诉我：“孝”这个字很特别，下面一个孩子的“子”，上面一个老人的“老”，孝字的形象就是一个孩子背起一个老人，这就要求我们尊敬、关爱自己的长辈。

   这段时间，爸爸经常去医院陪爷爷，因为爷爷生病了。上个星期六，我也和妈妈去第一医院看望爷爷。爷爷刚刚动完手术，躺在病床上。我们买了牛奶和一个大西瓜，我给爷爷讲学校里发生的事情，听到我有进步了，爷爷的脸上笑开了花。我还给爷爷剥香蕉，爷爷吃得很开心。我希望爷爷快点好起来，也希望我像爸爸妈妈一样，做个有孝心的孩子。

   爸爸妈妈工作很辛苦，我经常在家帮他们做一些力所能及的事情，比如洗碗、洗衣服、拖地，给父母倒水。有一次，我看到爸爸的脚受伤了，就自告奋勇独自去药店给爸爸买红药水。我也很听爸爸妈妈的话，不惹他们生气。家是一个温暖的港湾，只有拥有一颗孝心，才能使这个港湾充满温馨和爱！

   #+LATEX: \vspace*{\baselineskip}

   *悠悠寸草心*[fn:6]

   三字经有云“香九龄，能温席”，说的便是黄香九岁之时，能替其父冬夜暖席，夏夜纳扇，人说能孝敬父母之人，也必爱国爱民，果不其然，黄香后来当了官，也为当地百姓做了不少好事，其孝敬父母之事，也流传千古。

   父母恩情似海深，人生莫忘父母恩。孝敬父母古往今来一直是中国人为人处世的第一要则，众多名人都有关于孝的名言，如“老吾老，以及人之老；幼吾幼，以及人之幼”、“百行孝为先”等等。而不孝是要遭到社会舆论的强烈谴责。然而现在随着改革开放的深入，西方思想进入中国，其中有不少精华，然则亦有不少糟粕。别的暂且不论，由于西方历史文化社会结构与中国相异，中国人的孝敬受到了严重的冲击，甚至抛到了九霄云外。

   究其原因，大致有以下几种原因，一是目前大多家庭是独生子女，父母对其过分溺爱，有些晚辈不仅对长辈缺乏必要的礼貌，甚至出言不逊，指手划脚。二是现在的父母与子女之间缺乏必要的沟通理解，亲情越来越淡薄。

   由此，我们当对此现象进行反思，查一查原因，做父母的，一是看看自己是如何教育孩子的，二是让孩子看看自己是如何孝敬长辈的。

   为人儿女，又为人父母，我深感责任重大，更知榜样的力量。每天必给父母打一电话，每周末去看望父母，若去旅游，必带上他们，成为我一贯的做法。因为我深知：大孝无痕。孝，无须惊天动地，无须甜言蜜语，微处现真情，一杯水、一个电话、一声问候，便是生活里点滴爱的流淌。孝，贵在恒，贵在坚持。

   谁言寸草心，报得三春晖？父母的恩情难以回报，我深感愧疚，只能默默努力。孩子在我的影响下，也慢慢成长。有时会记得给爷爷奶奶打电话报平安，去长辈家里也会做点力所能及的小事，给他们带来不少欢乐。在家里，慢慢学会了不少事情，从洗碗、包饺子、烧菜到给父母端水，不懂事的顽皮小儿逐渐在成长。一次雨天，孩子看到他爸爸的脚受伤发炎了，鼓起勇气独自去附近的药店买红药水。这是他第一次自己一个人下楼买东西，虽然一开始有点害怕，但最后还是顺利完成了任务。最近他爷爷生病住院，看到爸爸一直在医院里陪伴，他似乎也懂事了许多，去医院看爷爷的时候，还主动剥好香蕉给爷爷吃。正所谓“春阳五月倍温馨，唤醒悠悠寸草心。”

   做一个好人、一个善良的人、一个成功的人，首先就要做到孝。孝心需要我们世代相传，一个充满孝的家庭必定是幸福的！孝心无价！让我们一起努力，一起成长！

** 游防空博览园

   今天早上，阳光灿烂，我怀着愉快的心情，和妈妈来到了招宝山景区。那里有镇海中国防空博览园。

   我们进入博览园，穿越人防坑道，那里有雕塑、壁画、图片、实物，还有很多枪、飞机、坦克等模型。我了解了世界防空、中国防空、人民防空、未来防空等知识。

   走出博览园，我还看到许多露天武器比如飞机、高射炮、坦克等，真是大开眼界啊！

   最后，我在军事体验区玩了几个项目，当了一回狙击手。我玩得很开心！

** 打羽毛球

   今天，我和妈妈一起去越秀打羽毛球。到了球馆，我先打了反拍式发球，妈妈轻而易举地接住了。我又打出高远球，但妈妈还是轻松地接住了这一球。我又打了低炮发球，妈妈只差一点点就接到了。妈妈还打出了正手式发球，我用旋球接住了。然而妈妈用身高优势打出了高炮球，我用跳起来的办法打出了高炮斜拉球。妈妈奋不顾身地打出了斜球。我根本还没反应过来，妈妈就打出了这个斜球。妈妈的速度相当惊人啊！我承认这局我输了。

   通过这场比赛，我知道了要多练习才能有成就！

** 我的梦

   昨天晚上，我做了一个梦，梦见了一台机器。

   这台机器上宽下窄。上面有红色的按钮，下面是出货口。最下面有硬币投入口，中间有个牌子，牌子上写着各种饭菜的价格。旁边还有一颗按钮，是调节饭菜饮料的温度。

   有了这个机器，你就不用烧饭了，只要投入硬币，就可以吃到饭了。

   我还给梦中的机器取了个名字，这个名字是“饭料机”。到了早上，我起来的时候一看，咦！梦中的情景呢？我想也许这是个梦吧？我一定要好好学习，天天向上，做一位发明家，把我想象中的“饭料机”发明出来。

** 雨

   满天的乌云，黑沉沉地压下来。突然吹来一阵风，吹得树枝乱动。雨声越来越大，雨点也越来越大。

   我从窗外往下望，原来白色干燥的马路，现在变成了黑油油、湿漉漉了。路上的行人都撑起了雨伞。没带雨伞的人呢？他们在匆匆忙忙地奔跑，我在想，他们可能在小声嘀咕：“这下糟了，要变成落汤鸡了。”过了一会儿，风小了，雨也小了。

** 可爱的小乌龟

   今天，我去奶奶家做客，发现近段时间，奶奶家养了两只小乌龟。这两只小乌龟被养在一只不大不小的缸里。两只小乌龟都比较小，只有我的两只小手那么大。

   奶奶告诉我这两只小乌龟都叫巴西龟。我看了一下，这两只乌龟头都小小的，背硬硬的，脚短短的，尾巴小小的。它们的样子都非常可爱！过了一会儿，体型比较大的一只爬到了体型比较小的那一只上，表演杂技。

** 去兰亭玩

   今天，我跟妈妈到兰亭去玩。我看到兰亭王羲之的鹅池。我还拿着地上捡来的毛笔在上面写了字呢。我去了王羲之博物馆，看到了周围很多名胜古迹。

   我又去了旁边的印山王陵。这里就是越王勾践的父亲允常的墓。今天我玩得真开心啊！

** 我的妈妈

   今天是星期天，又是母亲节。这个节日让我想起了我的妈妈。我的妈妈中等身材，平易近人，和蔼可亲。白天，她辛苦地上班，下班后还要来接我放学，并且还要买菜回家。到了家里，还要烧菜，晚上还要给我批改作业，讲解错题。妈妈不光平时指导我的功课，还经常陪我打球，陪我参加各类活动，让我增长知识。

   我真想快快长大，帮妈妈分担忧愁。

** 我的梦，天蓝地绿的中国梦

   每个人都有自己的梦想。变形金刚的梦，是在丛林里消灭坏蛋；熊大熊二的梦就是保护森林。而我的梦想，就是要建设一个天蓝、地绿、气爽的美丽中国！

   记得有一天我去上学，刚走到中成新村的小区门口。呀！一根香蕉皮被过往的车辆压得面目全非，糊糊地摊在地上，真难看啊！我想：平时老师让我们做一个爱护环境的小学生，我应该马上把它扔到垃圾桶里去。可是时间已经不多了，这样做的会肯定会迟到的。该怎么办呢？“保护环境在于行动！”妈妈的话在我的耳边响起。光说不做，保护环境就只是一句空话而已。说干就干，我马上停下脚步，把香蕉皮扔进了远处的一个垃圾桶里。那时，我感到特别轻松。

   亲爱的同学们，作为美丽中国的小公民，我们都有责任保护身边的环境。建设美丽中国，应该从小事做起：在学校中，看到地上有纸屑，我们要主动弯腰捡起；看到水龙头滴水，也要及时把它关紧。我还要宣传环保小知识，让更多的人加入环保队伍，让天变得更蓝，水变得更清。我一个人的力量很小，但是如果全中国的孩子都能行动起来，那建设美丽中国，这个梦想一定会实现。你们说是吗？[fn:7]

** 参观中药博物馆

   今天，我和妈妈一起去参观上海中药博物馆。博物馆就在上海医药大学里面。一进入博物馆，我就看到古代医药家的雕像。接着我又看到了中医学家的器具。然后，我在二楼体验区体验了各种各样的脉搏，比如平脉、急脉、浮脉等等。

   最后，我在三楼看到了很多中草药。比如百部、天冬、元贝、白及、西瓜皮、合欢皮、葫芦、牛皮、人参、燕窝、熊胆、乌龟、穿山甲等等。

   去了中药博物馆观，不仅让我增长了见识，而且长大后，我想当中药学家。

** 冷血悍虫

   今天，我跟妈妈去听“谁是最冷血的悍虫”的讲座。这次讲座，老师先讲了昆虫的特征。再让我们猜谁是冷血悍虫。我们都猜错了。老师说他认为蜻蜓是最冷血的杀手。因为蜻蜓的幼虫叫“水虿”，嘴巴很大，身体也很大，非常凶猛。我还知道了蜻蜓的羽化过程。蜻蜓能够吃比它大的昆虫。小朋友，你们也认为蜻蜓是最冷血的杀手吗？

   我今天的收获真多啊！

** “六一”当老板

   小朋友，你们猜，今天我在哪里？答对了，我就在城市广场的美术馆里参加第五届小学生跳蚤市场的活动呢。

   为了这次活动，我可准备了很多东西，比如：铅笔盒、书籍、橡皮、铅笔……一进场，我马上布置好摊位，把要卖的东西依次摆好，等待小顾客的光临。过了一会儿，第一个顾客从我这里挑走了可爱的“小黄人”。又过了一会，陆陆续续又卖掉了好多东西。我正想到别的摊位里去买东西，忽热听见有人叫我的名字。我回头一看，原来是我的好朋友张烨和他的表哥。他到我摊位里买东西，我给他最便宜的价格。

   我一共赚了 15 元，我觉得卖东西真辛苦啊！

** 游壶口瀑布

   暑假里，我和妈妈在西安旅游。今天我们的行程主要是去参观壶口瀑布。

   一进入景区，我看到黄色的瀑布，气吞山河，声如雷鸣，涛声震天。我不禁想起了李白的诗句“黄河之水天上来，奔流到海不复回。”这景色真是太雄伟了！

   我还玩了黄河的水，水凉凉的、黄黄的。我还戴上了白毛巾，骑上了驴子。我感觉很好玩。我又看到旱地船，敲了锣，打了鼓。

   时间过得真快啊，马上就要离开母亲河黄河了，我真有点依依不舍呢！

** 马路趣事

   今天，妈妈骑电瓶车带着我去逛街。前面有一位老爷爷骑电动三轮车。车子的椅子上坐了一条小狗。这只小狗的毛是棕黄色的，样子很可爱。

   过了一会儿，因为道路不平，所以小狗跳了下来，一路奔跑，想追上主人。警察笑了，路人也笑了，我也笑了，妈妈也笑了。

   我很着急，让妈妈骑得快一点，总算赶上老爷爷了。我说：“爷爷，你的狗在后面呢。”我还指了指后面的空椅子。老爷爷发现空的椅子，赶紧调转头去找小狗了。

   老爷爷找到小狗了吗？我想一定会的。

** 拼四驱车

   今天，我跟妈妈去一个售楼中心参加拼四驱车比赛。

   我拿到了一辆紫色的车子，开始拼装了。我看了一下图纸，第一步是车面的安装及贴纸的位置，看了一会儿，我感觉好难哦！拼了一个小时左右，我只拼装了第一步。我想找人求助，可是这里规定不能找大人帮。我只好垂头丧气地回家，让爸爸帮我一起完成。

   爸爸先教我拼车底，再教我拼车身。从十点一直拼到十一点，总算把车子拼好了。

   我试了一下，这辆车开得太快了，又很猛，真好玩！我觉得自己拼好东西，就有收获。

** 花雕

   今天，我跟爸爸去参加花雕工艺实践活动。开始进教室了，我问爸爸什么是花雕，爸爸说：“花雕就是在酒坛上画画。”老师讲我们要自信、自强、自主。

   老师先带我们去拿酒坛。我们顺便拍了几张花雕酒的照片。然后再让我们在酒坛上描线条。我画了农夫山泉的样子。最后我们高高兴兴地回家了。

** 发黄手环

   今天，我和妈妈到白马社区发黄手环。这是“带上黄手环，引导回家路”的活动。这个黄手环就像表一样，中间有一个槽。槽里面可以放这个人的信息。如果看到有佩戴黄手环的人，在他处于危险的时候，就可以获得帮助。

   我把黄手环发给旁边的爷爷奶奶，告诉他们黄手环的用处和用法。虽然有点热，可是听到他们的夸奖，我心里乐开了花。给别人送去爱心，我很高兴！

** 军事体验

   今天，我来到绍兴武警反恐分队。一进入大门，我觉得我好像已经是解放军战士了。

   我先去参观他们的宿舍，那里很干净，被子也很整齐。我还学了用被子折豆腐干的方法。接着，我跟他们去训练。我学了立正、起步走、稍息、向后转、向前转、向左转、向右转、跑步等动作。

   我还参观了解放军战士的枪。有信号枪、手枪、左轮枪、八一式步枪、八杠式步枪、初式步枪。这些枪里，我最喜欢的是左轮枪。后来我看他们在双杠、单杠上穿梭自如。

   然后，我又重新训练了一下。后来我又看了以前国民党和共产党联合抗日的电影。等我长大了，我也要像他们一样保卫家园。

** 嘉兴游

   今天，我和爸爸妈妈一起参加来斯奥吊顶组织的嘉兴游活动。我在旅游车上表演了一个节目，拿了个小礼品，我很开心。我们来到来斯奥工厂。我们看了各种各样的车间，还看了他们的产品。后来还去了会议室，回答问题拿礼物。下午我们还去了南湖。南湖是由很多小景点组成的。听导游讲乾隆皇帝曾经八次登临南湖。我们去了湖心岛、壕股塔。

   我们后来开开心心地回家了。

** 游泳

   今天下午，妈妈带我去新建成的奥体中心游泳馆游泳。那里有冲浪的项目和按摩、冲脚，都很好玩。还有儿童玩水的地方。我在滑滑梯上玩了好几次。每次滑到滑梯的尽头，我就慢慢地掉了下去，无比刺激。还有水枪、蘑菇水房等等。

   我又去了冲浪的地方玩，那里一浪接着一浪，无比刺激。

   我还在泳道里游了三圈呢。

   游泳是一种很好的体育运动，但是千万不要到大河、大海去游哦！更要小心哦！

   #+LATEX: \newpage

* 三年级——懵懂少年

** 去表弟家做客

   今天晚上，我去弟弟家做客，让我兴奋不已。我先和弟弟走飞行棋，下得很激烈，最后我的一颗棋子把弟弟的棋子纷纷撞回原处，可弟弟很快又占了上风。可我还是技高一筹，赢了这场比赛。过了一会儿，我们比陀螺，我拿出了列风光翼，弟弟拿了极地金盾。摸着战斗盘，拿出一副胸有成竹的样子。我喊一二三开始，弟弟和我的陀螺就撞了起来。但过了一会儿，弟弟的陀螺停止了撞击，改成了防御型。我的陀螺怎么撞都撞不掉。但我的陀螺努力撞弟弟的陀螺，最后我和弟弟的陀螺同时倒下。

   我们又玩了篮球、排球、三毛球等等，然后我就高高兴兴地回家了。

** 学烧菜

   今天，爸爸和我一起烧胡萝卜炒豆腐干。爸爸说：“炒菜要先把锅中的水弄干，再放油，然后放食材，油要放得少点，最后再放盐，炒一炒，这样就好了。”

   就这样，我先把锅中水弄干，再放了一点油，让锅变热，然后再放胡萝卜，再放豆腐干，但油溅到了我的手，不过没事。我问爸爸是不是要炒几下，不然会半生半熟的。然后，我东炒几下，西炒几下。爸爸说：“是把旁边往中间炒”。最后我放了一点点盐。爸爸说：“不够”。我又多放了一点。爸爸说这样才刚刚好。我又把胡萝卜豆腐干炒了几下，然后用盖子盖住。过了一会儿，菜就烧好了，我把菜盛到了碗里。大家说我烧得很好，纷纷夸奖，我懂得了一个道理，那就是只有失败，才有成功。

** 去环城河游玩

   今天，我和弟弟在环城河玩捉人游戏，弟弟跟我比第一局。

   我非常快地跑了过去，与他迎头痛击，各减几滴血，然后重新战斗。我快速地向安全地带跑去，但被弟弟击败，只好重新防守。但是我被弟弟击到一个地方，大败而归。可我鼓足了精神，把弟弟击败，连续让他败了三次，而且还把他赶出了战斗区，弟弟大败而归。我又和弟弟奋勇一战，我跑他追，我击他闪。我巧用计谋，把他打得落花流水，溃不成军，根本就没一个样子。但我知道，安全地带是最有效的，能战胜另外什么人的攻击都没有。[fn:22]我进入安全地带，但被他拦住，不过我还是快了一步，进了安全地带，战胜了弟弟。我懂得了一个人要强，那就要有经验。

** 拆电风扇

   秋天是一个美丽的季节，经过了一个酷暑，天气渐渐得变凉爽了。因为天气慢慢变冷，所以我们在国庆节小长假间，拆洗电风扇。我们先拆了第一把电扇，爸爸去拿螺丝刀，拆好后，我一看说：“爸爸，你去洗，我去拆。”爸爸去把脏脏的扇叶洗了一洗，我拆电风扇，但没有成功。所以我就去洗电风扇的扇叶。洗完了电风扇，爸爸说：“你真棒，待会给你吃棒棒糖！”我连忙说：“我去把这一把电扇放好。”我去把电扇放好，可是我不小心把里面的东西掉了出来，压到了我的小腿、大腿、膝盖、脚趾头和屁股。我感觉有点痛，但我还是把东西放好了。我懂得了再小的事，也会有失败。

** 观察小动物

   今天，我买了两只巴西龟。我看了一下，发现两只龟头小小的，背硬硬的，脚短短的，尾巴也小小的。它们的样子都很可爱。

   我把它们养在一只不大不小的缸里。过了一会儿，体型大的爬到了体型小的上面，好像在表演杂技呢！我们全家人看了都哈哈大笑。有时我手轻轻一碰它，它的头便缩了进去，难怪叫它“缩头乌龟”呢。

   我们家的乌龟给我们带来了很多乐趣。

** 杂诗

   月下鸟虫鸣，

   花草寂如静。

   大树直笔挺，

   形隐灯下明。

   *——舒铭写*

   #+LATEX: \vspace*{\baselineskip}

   鸟儿仰天鸣，

   花草卧地静。

   大树笔直立，

   月光照树影。

   *——爷爷写*

** 绿豆发芽记

   *星期四  绿豆们的冲浪*

   今天，我听老师讲回家观察绿豆。一进家门，我就迫不及待地把绿豆找出来，小心翼翼地把绿豆放进小脸盆，然后把水放进去。绿豆便不停地在水中发转，像在冲浪一样。我观察了一会儿，绿豆已经停止了冲浪，静静地发呆。

   *星期五  绿豆破壳而出*

   第二天，我看见大多数绿豆都破了壳，比原来的胖了些，大了些，像小鸡孵从蛋里孵出来似的，都露出了白白的身体。但有的只是开了一个小口。

   *星期六 绿豆发芽一*

   第三天，我去看，发现绿豆全都长出了白白的豆芽，不过大多很短。而且是从缝隙里长出来的根，很像钩子。

   *星期天 绿豆发芽二*

   今天和昨天相比，绿豆的芽更长了，更像钩子了。我想再过几天，会变得更长的。我觉得这个好有趣啊！

** 秋游记

   今天是个秋高气爽的日子，我随着老师同学去小亭山秋游。

   我们等同学都到齐后，便上了山路，一路上，两边全是花草树木。我看见很多同学带了溜溜球，我很后悔没有带。我们走着平坦的路，一会儿便走到了山顶。我们班在一块平坦的地方一起分享美食。我们吃了一会儿，突然风变大了，我们的报纸袋子被吹走了。我们还爬上了石墙。

   之后，老师给我们拍了照做了纪念。小朋友，我在小亭山秋游，你在哪里秋游呢？快来告诉我吧！

** 介绍一种民族文化——脸谱

   今天，我给大家介绍的是脸谱，你知道脸谱吗？

   制作脸谱的第一步是勾线，勾线勾完后，要涂淀粉，淀粉要拿稳，不然的话会涂出去的。而且淀粉袋要用力地挤，才能挤出去白白的、糊糊的东西。淀粉袋前面的角可要对准，挤向要涂的地方，才行哦!

   然后还不能忘了涂色，涂色要涂得美！

   这就是我的脸谱介绍，小朋友，你们说好不好？

** 学做中国结

   今天，我在书上看到了中国结是中国人祈求幸福的工艺品，我便和爸爸一起来学做纸制的中国结。

   我先把纸找出来，然后再上面做上标记。爸爸帮我剪下来。然后我们把它排齐，把多余的部分插进去，并且奇数在上面，偶数在下面，都穿插进去，把它整整齐齐地弄好，并把它所有露出来的插进去。一开始，我觉得它很像面条，后来我才感觉有点像书上的中国结。然后再找了一张纸，把它插进去，做成了柄。

   我知道了中国结的做法和插法，我的收获可真不少啊！

** 第一次主持班队活动有感

   这个星期三，我在班级讲台上讲课件呢！我讲的内容是感恩节。为了参加这次活动，我可下了很大的功夫，最近每天都在练这个课件稿。本来我不是当天的，因为我讲的是感恩节，恰好感恩节就在这个星期四，经过了一波三折，我终于轮到到台上讲了。当天，我无比得紧张，因为万一说错了怎么办？我脑海中是一片空白，虽然练了这么多次，但我还是很慌张。我有一节音乐课没去上，就是因为这件事情。后来的每一节下课铃一响，我都觉得毛骨悚然。到了下午第三节课了，我慢慢地冷静了下来，我心里想着不能出错啊，心里默念着。到了台上，我先是放音乐，再是讲感恩节的东西。我流畅地讲完了这些，才大大地松了口气。

   通过这次锻炼，我知道了在感恩节里，更要体会父母的辛苦，体会父母的劳累，不光是在感恩节要孝顺父母，平时也要孝顺父母哦!

** 家乡的环城河

   我的家乡是绍兴，那里风景优美，物产丰富，是个可爱的地方。

   就说环城河吧！环城河是一条美丽的河，水质清澈，每当节假日一到，就有很多人去玩，那里就成了一道美丽的风景线。近几年，环城河还举行了一年一度的皮划艇比赛。

   春天，树木长出嫩绿的叶子。夏天，最有趣的要算水幕电影，每到晚上，稽山公园这里就人山人海，因为他们都慕名前来观看“大美绍兴”。秋天，它凉凉的风，给我们带来了快乐。冬天，雪花更美丽。

   环城河一年四季都很美丽，像一座大花园。

** 游柯岩

   今天，阳光明媚，天气晴朗，是个出游的好日子，我和妈妈怀着兴奋的心情去绍兴柯岩游玩。

   柯岩风景区分成柯岩、鲁镇、鉴湖这三个景点。在柯岩，一块奇石映入我的眼帘，这就是云骨，听说是千古年的一块奇石。我还看到了巨大的石佛，那是石匠精雕细制而成的。我真佩服他们精湛的手艺。

   在鲁镇，我们走在民俗风情街上，两旁是一间间店铺，好不热闹。我还看见了鲁迅笔下的人物比如鲁四老爷、阿 Q、祥林嫂。我们还去了狂人府，看到了斜斜的小屋。

   接着，我们乘着画舫来到了鉴湖。我们走在古纤道上，无际的微波轻抚着波光粼粼的水面，感觉太美了。我还在码头旁边的地方射了箭。

   今天，我觉得柯岩太美了。听妈妈说《武媚娘传奇》有一集就在这里拍摄。小朋友，你们说柯岩美不美？欢迎你来我们的家乡！

** 二十年后的家乡

   我刚回到绍兴，一下车，就看到一片荒凉的场地，一个人也没有，花草树木也没有，我顿时惊讶无比。我想：“我的家乡怎么会这么凄凉无比呢？”我觉得很奇怪。我又去了环城河。看见上次清澈见底的环城河也没了，只剩下干涸的河床，裸露的石头，留下了一片荒凉的土地。我想那是老天爷给人类的惩罚吧。都怪人类没有好好保护这个环境，不爱护环境的人当然会受到这个坏环境的折磨。

   我又去了上次绿树成荫的小亭山，现在竟然变成了一座黑山，只留下裸露的土地和光秃秃的石头。我顿时惊呆了！美丽的绍兴竟然变成了如此荒凉的黑暗世界。我生活在这个世界里，真的有一百个不想回来。

   这时，闹钟响了，爸爸让我起床，我才知道这是一个梦，但我决定要保护这个家园。

** 这就是我

   我有一头乌黑的头发，一双不大不小的眼睛。

   虽然外表很普通，但我有很多爱好，比如说看书，玩溜溜球，下国际象棋，打羽毛球。就说国际象棋吧。有一次，我和爸爸下棋，我采用了王车易位，爸爸用闪击，闪将的方法，杀了我的一颗象。我连忙用通路兵一起上，团结力量大，兵兵向前冲，杀掉了爸爸的很多子。爸爸又用捉双战术，一马杀了三颗子。我先把大子躲藏起来，用小子攻击。我还剩下两个车，一个皇后，一马一象一王，三个兵。爸爸还剩下一个皇后，二哥马，三个兵，一个王和两个象。爸爸又用牵制的方法杀了我的一个子。最后我用单车杀王的方法打败了爸爸。

   但我也有缺点，就是非常粗心，老是错一些计算题。

   这就是我，一个爱下棋的人。

** 春游杂感

   这周五，我听老师说去春游，我非常高兴。

   在周四晚上，我在书包里放好了薯片、豆腐干、海苔、蛋黄派等以及溜溜球。但老师发短信说：“如果明天下雨，可能不去春游，照常上课。”

   知道这个情况后，我非常紧张。到了晚上八点钟，我听到了大雨，哗啦啦地下着。我在心里想，大雨啊大雨，不就是一次春游，你都不放过我，但愿明日不要下雨啊！

   到了第二天早上，我醒来后第一句话就是今天去不去春游啊，妈妈跟我说不去春游了，我很失落！

** 我学会了炒芦笋

   傍晚，妈妈教我炒清炒芦笋。我说芦笋怎么炒。妈妈说：“这个菜既好吃，又有营养。芦笋又名长命菜，龙须菜。在西方，芦笋是十大名菜之一呢！”

   开始做菜了，我们先把芦笋挑出来。一根一根地洗，再用水清洗一遍。在洗的时候，我发现芦笋的头像麦穗，杆像竹子。然后妈妈把芦笋切成一段一段的，每一段差不多三四厘米。再把木耳洗得干干净净，然后就开始炒菜了。清炒芦笋是很有讲究的，要先把芦笋放进去炒，再把木耳放进去一炒，烧了一会儿，等芦笋快熟了，再放上盐。一碗美味的菜清炒芦笋就炒好了。

   吃上我可口的饭菜，我心里乐开了花。

** 春游——游环城河

   周五，老师带我们去环城河游玩，大家排着队出发了。一路上，欢声笑语，我们走啊走，终于走到了环城河。在那里，有一些花草树木。我看见一些同学带了溜溜球，我很后悔没有带。我们走着平坦的路，一会儿就找到了一块阴凉的场地。我们吃了一会儿，老师便给我们拍照。

   我给别人吃薯片，别人也给我吃薯片，好不热闹。别人还借我玩了溜溜球呢！我今天玩得很快乐！

** 爸爸妈妈的爱

   爸爸妈妈的爱是无限的，丰富多彩的。就先说爸爸吧!

   我的爸爸是一个不大会讲话的人，但是动手能力特别强，马鞭、恐龙模型、青蛙模具等，凡是动手的东西，差不多都是他指导我。每天都是他送我，他虽然不大讲话，但是我觉得他的父爱在我心灵深处。

   我的妈妈是一个会讲话的人，从小到大都是她陪我的，陪我读绘本，讲故事，自从她生病期间，这些事情就中断了。我就变得无法无天了，因为爸爸傍晚五点才回来。她病好了，又是陪我参加一些活动，管我学习生活，为我操心，我认为母爱也很伟大。

   我认为爸爸妈妈是无私的，我一定要管好自己，不让爸妈操心了。

** 金渔湾

   今天天气一点儿也不好，但妈妈这次约她的同学和我们一起到金渔湾农庄。我们十点左右到达那里，先去了五间小房子，再去看鸭子。到了十二点左右，一起去吃饭。下午去旁边爬山，爬到了山上，我和妈妈在那里挖笋。后来就回家了。

** 未来的房子

   今天，我做了一个梦，梦见了一幢高大美观的房子。我按了一下一个按钮，门就打开了。我看见有一些机器人在那里工作。机器人告诉我，这幢房子非常牢固，防盗、防洪水、防地震。这幢房子还能随着主人的心情变颜色。主人心情好，就会变成红色；主人心情不大好，就会变成蓝色。要是主人去了很远的地方，这幢房子就能带着主人飞到那个地方。

   咦！房子呢？原来这是一个梦，但我想这个梦一定会实现。

** 一件奇特的事情

   一天，我一回到家，听见有猫的叫声。一开始，我还以为是外面发出的声音，爸爸在家里找来找去，还是没有发现任何猫的踪迹。这时，妈妈说：“有可能在阳台里”。爸爸去阳台里一看，果然有一只黑白相间的猫在那里上窜下跳，爸爸顿时吓坏了。

   听到爸爸的惊叫声，我便和妈妈鼓足勇气到阳台，妈妈慢慢地把窗打开，想让猫咪跳出去，但是猫咪在阳台里跳来跳去，我们束手无策。这时，我把门打开了，猫就跳进了我的床，蹦进了内卫。妈妈赶紧把门关上了，把猫赶出了内卫窗口。一开始，那猫并没有跳下去，因为实在太高了。但到了后来，那猫渐渐跳了下去，因为底下是马路。

   我觉得很奇怪，猫怎么会在我家里的呢？这猫是怎么进来的？谁养的？现在在哪里？妈妈上网查了一下，有人说家里来了猫代表吉祥，有人说猫来了代表不吉祥，猫走了代表吉祥。猫早一点来，晚一来也都很好，但为什么偏偏要这个时候来我家。反正，这是一件奇特的事。

** 假如我变成了孙悟空

   今天，我正捧着《西游记》津津有味地看着，看了一会儿，我的眼前一黑，便把我带入了一个洞的旁边。

   突然，从里面冲出一个怪物，穿着红铠甲，嘴巴里露出明晃晃的钢牙，大声说：“你是谁？留下买路钱，不然，性命难保！”我说：“我是你家爷爷，吃我老孙一棒！”说时迟，那时快，我用力地砸向那怪物咚地就是一下子。就在这时，那怪物侧身躲过，往外一闪，拿起九节钢鞭就砸过来。这下我恼羞成怒，用力砸向那怪物。那怪物用九节钢鞭相迎，打了二十几个回合，那怪物渐渐招架不住。它说：“你到底是谁？”我说：“我是齐天大圣孙悟空，天兵天将都没一个不认识我的！”

   那怪物说：“我是天蓬元帅猪八戒之子猪小戒!”我说：“真是大水冲了龙王庙一家人不认一家人！我应该去天宫大闹一场！”

   这时，如来来了，我连忙侧身躲过，但还是被如来一掌打到了家中。这时我才如梦方醒，原来我现在正在看《西游记》呢！刚才是做了个梦，梦中变成了孙悟空，哈哈!

** 未来的鞋子

   现在是 2060 年，我是舒博士。

   有一天，我买了一双新鞋子。我迫不及待地穿上了它，突然听见脚下有东西在讲话，我仔细一听，原来是鞋子在讲话。鞋子向我问好。我说：“好啊！”鞋子说：“我不会破，非常耐用。还能远走高飞，行走自如，穿上我，你几秒钟就能飞到外国，比飞机快多了！”我说：“真神啊！”鞋子说：“这得感谢科学家们，是他们用高科技材料制成我的！”“现在的科技实在是太好了！真得感谢他们。”我欣喜地说。

   鞋子继续自豪地说：“嗯，因为鞋里装了全世界最强的材料，能感应大脚趾和小脚趾，大脚趾是开始键，小脚趾是停止键。我还有一个机器，就是导航仪。你只要输入目的地，它就会告诉你怎么走。除外，我还装了一个机器就是保护伞。如果你遇到了意外，保护伞就能自动弹出。”

   我一想，这些机器不是都需要电嘛，那万一没电了，那怎么办呀？鞋子似乎看出了我的疑惑，解答到：“你不用担心，这可是用太阳能提供电能的，即使是下雨天，以前储存的太阳能也是够用的。”

   这就是未来的鞋子！我穿上它，无比开心地朝着我向往的地方飞去……[fn:8]

** 另眼看三国

   “滚滚长江东逝水，浪花淘尽英雄……”，读着这《三国演义》的定场诗，我胸中感慨万千，豪情万丈！一个个熟悉的英雄浮现在我的眼前，有白面长须的刘玄德、羽扇纶巾的诸葛亮、面若重枣的关云长、黑脸虬髯的猛张飞，还有那挟天子以令诸侯的曹操、偏安一隅韬光养晦的孙权，一时多少豪杰，但其中我最敬佩的还是关羽关云长。

   关羽是大家都熟悉的英雄，三国里有很多很多关于他的故事，从最开始的桃园三结义，到后来的温酒斩华雄、过五关斩六将、千里走单骑、水淹七军，连赤壁之战后华容道义释曹操都成了一项义举，甚至最后的败走麦城也成为了一个不可超越的传奇。这是为什么呢？之所以成就这么一位传奇的英雄，就是因为关羽身上有着中国人历朝历代最看重的品质——忠义，所以连他的缺点也变成了优点，比如说关羽放走敌军首领啥事都没有，而后来的魏延却只是因为头骨畸形被按上反骨的名义，莫名其妙说他谋反，最终被马岱斩首。

   通过阅读这部三国，我懂得了要有光明的地方一定有黑暗，有天使的地方一定有魔鬼，有正能量的地方一定有负能量。我学到了很多课本中学不到的知识，让我受益匪浅。[fn:9]

** 听评书《隋唐演义》有感

   最近，我在听评书《隋唐演义》，一共有 380 集。讲述了英雄结义二贤庄，程咬金瓦岗称王，小罗成勇破敌阵，秦琼大破铜旗阵，齐国远拦路劫友，云召血战南阳城，杨广谋取太子位等等故事。

   我很喜欢听，故事情节生动，人物形象栩栩如生，秦琼卖马，程咬金义劫官银，罗成大破长蛇阵，尉迟恭日抢三关等经典章回，千百年传为美谈，经久不衰。

   我最喜欢的就是秦琼，因为他马好，人好，武艺精湛，还有一副侠义心肠，专爱打抱不平。他在济州官府做辑捕，办案时公正无私，替民解冤。当地人提起秦琼，无不竖起大拇指。他那匹马，是御顶干草皇，不幸死在疆场。他善使铜锏和金枪。

   听了这些故事，我懂得了很多道理和历史。

** 我和老外过一天

   今天，爸爸妈妈带我去绍兴图书馆三楼参加英语角活动。到了活动的地方，已经有很多小朋友在了。活动开始了，老外先自我介绍，说：“我叫约翰。”然后唱了一首儿歌，之后就一个个问小朋友，第一个就轮到我，他问我：“你叫什么名字？”我说：“我叫 Mike，这是我的英语名字。”之后，他又问：“你有什么爱好？”我回答：“我喜欢乒乓球。”接着，老师让我们简单的自我介绍。后来，又一起聊了喜欢的动物、季节、天气、食物、水果等等。最后让我们完整的自我介绍。我是最后一个上台做自我介绍的。马上就到午餐时间了，午餐很丰富哦，一饭一汤两荤两素。

   午餐后，我们一起观看了《飞屋环游记》。这部影片讲述了老爷爷随着飞屋，找到了鸵鸟化石的故事。下午，我们分好组，一起做烘培。我们把事先已经揉好的面团压扁，用模具做出各种各样的形状，然后放进烤箱了。接着就坐等饼干出炉了。过了大概 20 分钟，饼干终于烤好了，我迫不及待地想品尝自己做的美味。

   通过这次活动，我收获了很多，我知道了英语是很重要的，学习的过程也是很开心的。

** 快乐的上午

   今天，我和表弟去十里荷塘参加雄鹰小队活动撕名牌比赛。

   活动开始了，我们到了一片空地，准备开撕了，是两队的比赛。我们这队有五个女生和两个男生，对方有六个男生。

   撕名牌比赛开始了，对方先进攻我们，我们就跑。过了几分钟，对方和我们抱成了一团。我从对方的背后偷袭。我撕掉了一个人的名牌。这时候，有人来撕我的名牌，我双手捂住名牌，不让他们撕掉。

   之后，双方又展开了一场激战。我们“死”了两个队员，他们则“死”了五个。我们最后五个人撕对方一个人的名牌，才把敌方 out 了。然后，是胜局对胜局，败局对败局。因为有一个男生中暑了，所以撕名牌活动就结束了。接着进行下一个项目即采标本。

   我们采完标本高高兴兴地回家了。

** 遛狗记

   *遛狗记（第一版）*

   今天，爸爸带我去奶奶家拿一些菜。这时，表弟来了，说让我留下来玩一会儿。爸爸去菜场买一些配料，所以我就答应了。后来，弟弟去吃早饭，吃的是烤饺，有十个饺子，我们分了一瓶冰糖葡萄。之后，我们去了健身的地方锻炼了一下。

   回到楼上，表弟跟我说，近段时间，他们家买了一条博美和巴金智慧结晶的白色杂种狗，弟弟叫它“小阿”，已经发育了三个月。表弟让我到他们家去看这条狗。我说：“好吧！”这时，爸爸来了，表弟说服了爸爸，不过要让表弟的爸爸把“小阿”带到这里才行。这时，弟弟的爸爸来，并把狗带来了。我就和表弟下了楼，去遛狗。表弟先把狗套上了绳子，因为不套上的话，它会到处乱跑。表弟先摸了摸狗，我也试着摸了摸，狗一点反应都没有。这时，表弟的爸爸把肉骨头拿来了，让我喂狗。我把袋子里的狗骨头给了狗一点，很快，狗把所有的骨头都吃了，肉也全吃了。之后，我们就牵着狗到各个地方走走。有一次，我在前面快步跑着，狗就来追我。我吓得魂飞魄散，这时，狗突然不跑了，停在那边不动了，我才松了一口气。

   我们后来去楼上吃饭，把肉骨头放进盘子里，喂小狗吃，可是小狗要喝水，我们只好把水给它。小狗喝完了水，啃完了骨头。表弟带我又到下面遛狗，我答应了。我们去下面遛这只狗，但没有想到，这只狗挣出了绳子，它跑了。表弟追了上去，把狗抱了起来，接着，我也抱了抱小阿。

   通过这次遛狗，人如果有意的破坏有生命的物体，那物体也会做出反抗。

   #+LATEX: \vspace*{\baselineskip}

   *遛狗记（修改版）*

   今天，爸爸带我去奶奶家。这时，表弟来了，说让我留下来玩一会儿。

   表弟跟我说，近段时间，他们家买了一条博美和巴金白色杂种狗，弟弟叫它“小阿”，三个月大。表弟让我到他们家去看这条狗。我说：“好吧！”这时，姑父来，并把狗带来了。我一看到了这条狗，银白色的毛，小小的眼睛像两颗珠子，腹部像穿上深红的外衣。我觉得很可爱。

   我就和表弟下了楼，去遛狗。表弟先把狗套上了绳子，因为不套上的话，它会到处乱跑。表弟先摸了摸狗，我也试着摸了摸，狗一点反应都没有。这时，姑父把肉骨头拿来了，让我喂狗。我把袋子里的狗骨头给了狗一点，很快，狗把所有的骨头都吃了，肉也全吃了。之后，我们就牵着狗到各个地方走走。有一次，我在前面快步跑着，狗就来追我。我吓得魂飞魄散，这时，狗突然不跑了，停在那边不动了，我才松了一口气。

   我们后来去楼上吃饭，把肉骨头放进盘子里，喂小狗吃，可是小狗要喝水，我们只好把水给它。小狗喝完了水，啃完了骨头。表弟带我又到下面遛狗，我答应了。我们去下面遛这只狗，但没有想到，这只狗挣出了绳子，它跑了。表弟追了上去，把狗抱了起来，接着，我也抱了抱小阿。

   不久，爸爸来接我回家了。通过这次遛狗，我从原来的怕狗开始喜欢上了这个小动物，我觉得它很有灵性，很可爱，只要你对它好，它就会成为你的好朋友，我也好想有一只自己的狗狗，一个知心的好朋友！

** 亲子欢乐营

   今天，妈妈带我去镜湖广场参加玩转暑假亲子欢乐营的活动。其中有大风车、军对抗等项目。

   我先参加了模拟工厂，再玩了超级蹦床。其中我最喜欢的是疯狂飞行棋。这种飞机棋跟一般的不一样，不用甩六再出去，直接就可以出去，甩几就走几步，可以飞，飞的会要跳过去，之后，如果谁先到了，谁就拿一个哨子。我最喜欢的就是这个疯狂飞行棋。我们还去玩了“小手牵大手，共建美好家园”的活动。

   通过这次活动，我很累，但我又非常快乐。

   #+LATEX: \newpage

* 四年级——初出茅庐

** 看大阅兵

   今天，我和爸爸一起看大阅兵仪式。我在电视中看到今年是世界反法西斯战争胜利 70 周年，大阅兵举办的地点是北京天安门广场。请来了 30 多位外国领导人，其中有波黑、古巴、波兰、朝鲜、南非、苏丹、老挝等国家，场面非常壮观。有 50 多位现役将军当领队。其中有装甲五方阵、坦克，还有挂着原盘的预警机，直升飞机、运输机。还有很多英模部队方阵，有 45 辆摩托车保护着军队齐头并进。11 个外军方队，大约 75 人，6 个外军代表队，大约 7 人。地面装备方队，其中有坦克方队、自行火炮方队、轻型突击车方队、航空导航方队、高射炮兵方队、白求恩医疗方队等方队。很多飞机在空中飞行，“拉烟”的次数最多，形成了七种颜色，真是光彩夺目啊！活动结束时，还放了七万多只和平鸽，五万多只气球代表和平。

   通过这次观看大阅兵仪式，我觉得我们祖国非常强大，有这么多武器，真是很伟大！

** 拉蒂迈小姐的鱼

   昨天晚上，我参加了自然学堂的讲座。老师先讲了历史上著名的动物，其中有巴普洛夫的狗、薛定谔的猫、克隆多利羊、摩尔根的果蝇等。之后，再讲主题“拉蒂迈小姐的鱼”。在陆地和海洋之间，有一个进化期，在古生代，有一种鱼，但早就灭亡了，叫作矛尾鱼，浅蓝色，有白斑，在邮票上也有，有四只鳍，是两栖动物，这就是拉蒂迈鱼。一位助理在南非买到了这条鱼，带回去腌成了鱼干，这是第一条跟别的鱼不一样的鱼。过了十几年，渔民又发现了一条跟这条鱼一样的鱼。目前为止，我们中国已经有了六条矛尾鱼。分部在六个地方，保存最好的是在北京古动物馆。

   我告诉大家一个秘密，鱼的鼻子不是用来呼吸的，而是用来闻气味的。听了这次课，我知道不少知识，但是人类的祖先到底是谁，到现在还是一个谜。我长大了要当科学家，去研究这个谜团。

** 我们的校园

   我们的学校树人小学东校区，坐落在城南的环城河边。那红红的加上白色的建筑物，就是我们的校园。我们的校园非常大，有教学楼、体育馆、食堂等等。

   走过两道校门，你一眼就望见了一幢高大的建筑物，高约 2 米，宽约 20 米，旁边是一块黑色的大理石，上写“崇德尚美，百年树人”八个鎏金的大字。后面是大家最爱去玩的操场了。每天大家都在这里玩耍。有的人在打球，有的人在踢球。

   校园的中间就是那同学们最爱去的长方形网格状的一个花坛。那是同学们心目中的乐园，花坛中用青石板铺成的小道，分成一格一格的，同学们可以穿梭其间，里面有各种的小花小草。旁边第二道校门的绿化带，里面有一株桂树。秋天到了，香气非常的好闻。

   校园的最西边是一条沿河的小道，这里非常的幽静，很少有人在这里玩耍。我觉得这是校园里最好的地方，这里凉风习习，小道宽约一米。对面是大操场，旁边是洗手间，后面是食堂，前面是教学楼，中间是长廊。还有青绿的竹林点缀着小道，环城河映衬着小道，水道变得更加美丽。

   最热闹的应该是体育馆，里面是地板，有两个篮球架，像两个高大的巨人，可以打篮球。在储存室，里面有各种健身器材，比如足球、篮球等。

   我们的校园非常美丽，小朋友，你们说我们的校园美不美？欢迎你来我们的校园！

** 第一次当小记者

   九月的古城绍兴，秋高气爽，绚丽灿烂。9 月 19 日上午，我非常荣幸的作为绍兴晚报小记者代表，参加“寻味绍兴•游学古城”——重写《从百草园到三味书屋》大型采风活动。老师安排我和另外一位小记者一起陪同来自江浙沪 10 家媒体的小记者们参观鲁迅故里和沈园。挂上采风证，拿着采访本，我感觉自己马上就像一名真正的记者了，又自豪又倍感压力。一路上，队伍浩浩荡荡，红色队旗高高飘扬，各地小记者们个个精神抖擞，有说有笑。我也开始兴奋激动起来，走在了队伍的最前面。

   不知不觉中，我们来了鲁迅故居，导游姐姐带领我们参观了鲁迅爷爷小时候居住的地方。在那里，我看到了整洁的卧室，幽静的弄堂，高高的台阶。沿着青石板路，来到了鲁迅爷爷小时候的乐园——百草园。映入眼帘的是碧绿的菜畦、光滑的石井栏、高大的皂荚树……很多小记者们都在认真记录导游姐姐的介绍，细心地探索着整个百草园，热热闹闹的拍照合影。我也认认真真的做了很多记录。然后我们继续兴高采烈地来到戏台，观看了越剧。接着就到了鲁迅纪念馆，一起排排坐，听导游姐姐讲述鲁迅笔下的人物和故事。听完故事，在留言板上留完言，我们一行继续前往三味书屋。

   在三味书屋里，老师带领我们饶有兴致地诵起《三字经》，有模有样对起了课。扮演小鲁迅刻字的那一幕，我仿佛看到了鲁迅儿时读书的场景。

   穿过大马路，马上就到了沈园，仿佛进入了诗境，聆听陆游和唐婉凄美的爱情故事，看到了六朝井亭、八咏楼、孤鹤轩、闲云亭……在沈园的葫芦池边，我采访了来自台州晚报的六年级的小记者。通过采访，我了解到这是他第一次来绍兴，他原先就知道鲁迅是一位了不起的人物，今天来到了鲁迅故里，和原先想的不一样，看到了不一样的百草园，还看到了久负盛名的沈园，他说他很开心。

   在回来的路上，我继续采访了一位五年级的台州晚报小记者严军伟，他也是第一次来绍兴，同行的还有两位台州小记者，也都是五年级的，都是第一次来绍兴。他们说绍兴挺好的，古色古香，这么古老的建筑物保存得这么好，真是美丽的水乡啊。这是我第一次采访，虽然不是很熟练，但我一点也不紧张。回来后，我还去他们住宿的房间玩了一会，很快成了朋友。

   下午还有一个交流会，有很多小朋友都在舞台上大显身手，他们讲了自己在绍兴一天半游学的感想。大部分人都在讲笑话、猜谜语、讲故事，其中，乐学少年的小记者给我们讲了很多笑话，气氛一下子就变得很轻松很活跃。我也上台给大家猜了一个谜语呢。

   时间过得很快，马上就到了分手的时刻，我依依不舍地告别了来自远方的朋友。通过这次采访活动，我不光更加了解鲁迅爷爷的故事，还知道了如何与人交流，如何进行采访，收获满满。这真是一次难忘的活动，感谢绍兴晚报能够给我这一次锻炼的机会。我想，下次我还要继续参加这样的活动，既能增长见识，又能锻炼胆量。

   #+LATEX: \vspace*{\baselineskip}

   *《台州小记者说：绍兴真是一个美丽的水乡》*[fn:10]

   /——小记者 舒铭：树人小学东校区四（8）班/

   9 月 19 日上午，我非常荣幸地作为绍兴晚报小记者代表，参加“寻味绍兴、游学古城——重写《从百草园到三味书屋》”大型采风活动。老师安排我和另外一位小记者一起陪同来自江浙沪 10 家媒体的小记者们参观鲁迅故里和沈园。挂上采风证，拿着采访本，我感觉自己马上就像一名真正的记者了，又自豪又倍感压力。

   不知不觉中，我们来到了鲁迅故居，导游姐姐带领我们参观了鲁迅爷爷小时候居住的地方。在那里，我看到了整洁的卧室，幽静的弄堂，高高的台阶。沿着青石板路，来到了鲁迅爷爷小时候的乐园——百草园。映入眼帘的是碧绿的菜畦、光滑的石井栏、高大的皂荚树……很多小记者们都在认真记录导游姐姐的介绍，细心地探索着整个百草园，开开心心地一起拍照留念。我也认认真真地做了很多笔记……

   随后，穿过大马路，我们走进了沈园，仿佛进入了诗境，聆听陆游和唐婉凄美的爱情故事，看到了六朝井亭、八咏楼、孤鹤轩、闲云亭……在沈园的葫芦池边，我采访了来自台州晚报的小记者。通过采访，我了解到这是他第一次来绍兴，他原先就知道鲁迅是一位了不起的人物，今天来到了鲁迅故里，和原先想像的不一样，看到了不一样的百草园，还看到了久负盛名的沈园，他说他很开心。

   在回来的路上，我还采访了另外三位台州晚报小记者。他们说，绍兴挺好的，古色古香，这么古老的建筑物保存得这么好，真是美丽的水乡啊。这是我的第一次采访，虽然不是很熟练，但我一点也不紧张。

   感谢绍兴晚报能够给我这一次锻炼的机会。我想，下次我的表现会更棒！

** 观察日记  豆芽成长记六则

   *2015 年 9 月 22 日    星期二*

   今天，我一回家，就找出三种不同样子的豆，其中有刚刚舅公家拿来的新鲜黄豆 29 颗，一年多从市场上买来的陈年黄豆 31 颗，还有红豆 15 颗，也是从市场上买来的。我把这三种豆放进塑料盒，浇上水，看明天会有什么变化。

   *2015 年 9 月 23 日    星期三*

   今天，我去观察不同的两种黄豆和一种红豆的变化。我一看，它们都没有发芽，黄豆的水吸收得最快，每一颗都有些皱，像是要涨开似的，我又浇了一点水，准备明天继续观察。

   *2015 年 9 月 24 日    星期四*

   今天，我去看豆子，发现它们都发芽了。红豆还只有半厘米的长度，新鲜的黄豆大概有一厘米，陈年黄豆只有一点点长，新鲜黄豆的皮变成浅绿色的了，像是绿豆。红豆洁白的嫩芽好像一只白色的虫，露出了白白的身子，我又浇了点水，准备明天继续观察。

   *2015 年 9 月 25 日    星期五*

   今天，我发现陈年的黄豆上有些霉变，灰色的，像虫子一样，有六七颗陈年黄豆身上变成灰色的了，新鲜黄豆的芽往上瞧着，像是调皮的孩子在玩滑滑梯，变成了大象。红豆虽然不长，但有点像月亮，又有点像钩子。我浇上水，准备明天观察。

   *2015 年 9 月 26 日    星期六*

   今天，新鲜的黄豆大概长了有 3 厘米长，像是翘着胡子的老头。红豆芽还是很短，大概就 1 厘米长，像是短短的小芽。陈年的黄豆则霉得像一朵朵棉花，霉点都快大过自身了，一个个东倒西歪，摇摇晃晃。我浇上水，准备明天观察。

   *2015 年 9 月 27 日    星期日*

   我今天继续观察豆子。陈年黄豆有一半都发了霉，新鲜黄豆全部都长出了 2、3 厘米左右的芽，像是大象的鼻子，但有点烂了。红豆还有一半没发芽，有些腐烂了。妈妈把红豆、陈年黄豆都扔掉了，只留下新鲜黄豆，这就是我观察的结果。

** 美丽的水乡，幸福的乐园

   我的家乡绍兴，山清水秀，人杰地灵！鲁迅爷爷的故居、笔下的百草园、三味书屋等景点吸引了成千上万的各地游客。今年的 9 月 19 日，我作为绍兴晚报小记者代表，参加“寻味绍兴 • 游学古城”活动，陪同江浙沪的小记者们一起来到鲁迅故里，了解鲁迅爷爷。虽然我多次参观过这个地方，但每一次都有不同的感受和收获，这次更是如此。

   走在青石板路上，一边的小河里摇曳着只只乌篷船，一边是白墙黑瓦的老台门，幽静的弄堂，高高的台阶……我仿佛走进了鲁迅爷爷生活的那个年代。一路跟随导游姐姐，我们来到了百草园，我看到了碧绿的菜畦、光滑的石井栏、高大的皂荚树。当导游姐姐介绍说这就是鲁迅爷爷当时的乐园时，我仿佛看到了幼年的鲁迅和闰土蹲在短墙边挖何首乌的情景。很多小记者们都在仔细记录导游姐姐的介绍，细心地探索着整个百草园，我也认认真真地做了很多记录。

   接着，我们又来到了鲁迅爷爷小时候上学的地方，屋子中间挂着一块匾，上面写着“三味书屋”四个大字。在那里，老师带领我们饶有兴致地诵起了《三字经》，有模有样对起了课。当听到鲁迅爷爷刻“早”字的故事，我深深感动了。导游姐姐介绍三味书屋后面也有一个园，虽然小，但在那里也可以爬上花坛去折腊梅花，在地上或桂花树上寻蝉蜕。听着听着，我仿佛看到了鲁迅爷爷儿时读书玩耍的场景。

   看着鲁迅爷爷的乐园和学堂，我不禁想到了我们现在。我们的乐园到处都是，不必说那洞桥相映、水碧于天的东湖，曲水流觞的书法圣地兰亭，江南园林风格、蕴藏着陆游与唐琬凄惋动人的爱情故事的沈园，也不必说风景如画的环城河，浓重文化底蕴的历史街区，各式各样新建的公园，单是居住的小区，都打扮得像个花园。花园里四季如春，还装上了各种各样的健身器材，像我这样的运动能手最喜欢在那里健身了。

   我们的小学那更是我们幸福的乐园了。我就读的小学——树人小学东校区，坐落在城南的南池江边，这可是由鲁迅爷爷的名字命名的学校哦！这里环境优美，设施齐全，有教学楼、体艺楼、体育馆、图书馆、食堂等。这学期，学校还装上了直饮水机，只要轻轻一拧龙头，暖暖的水就直接接到杯子里，拿起来就能喝了。

   我们的校园比较大，走过两道校门，你一眼就能望见一幢高大的建筑物，旁边是一块黑色的大理石，上写“崇德尚美，百年树人”八个镏金的大字。后面就是大家最爱去玩的操场了。校园的中间是一个长方形网格状的花坛，那是同学们心目中的乐园。花坛中用青石板铺成的小道，分成一格一格的，里面有各种小花小草，大家穿梭其间，尽情玩耍。旁边第二道校门的绿化带，里面有一株桂树，秋天到了，香气非常好闻。最热闹的要数体育馆了，里面有各种健身器材。校园的最西边是一条沿河的小道，非常幽静，我觉得这是校园最美的地方。青绿的竹林点缀着小道，旁边的南池江映衬着小道，这里变得更加美丽。偶尔会看到河道上驶过几只轮船，碧波荡漾，凉风习习，水乡的气息扑面而来。我想如果鲁迅爷爷小时候也有这样的学校，说不定能写出更美的文章来呢！

   这就是我们现在幸福的家园，鲁迅爷爷，您喜欢吗？[fn:11]

** 做月饼

   今天是中秋节，爸爸带我去做月饼。活动开始了，老师发给我们六张皮，六种馅，并指导我们把馅搓圆，包进皮里，把皮也搓圆、压扁，包好，把皮搓圆，用模具一压就能吃了。我先学着老师样子，把六种馅搓圆，搓到一半，我发现前面搓得并不圆。后来，爸爸教我，手要拱起来，不要伸直。但我在压皮的时候，发现有厚有薄，薄得都要破了。

   我把它捏扁，一口气做了六个，把分到的皮和馅都做完了。我非常高兴，回家了吃了 2 个，软软的，甜甜的，很好吃。通过了实践，我知道了一个道理，要把一件事情做得十全十美，那是不可能的。不要把事情想得很简单，最后做的时候都是有难度的。

** 国庆划船

   今天，我和表弟、爸爸、姑姑一起到青少年活动中心，参加划船活动。

   我们先到了划船的码头排队，穿上了救生衣，坐上了红颜色的船，我坐在前排，拿着桨。那边的老师告诉我们怎样转弯。我们开始划了，我奋力地划着，结果船并没有动，反而倒退了，爸爸教我们怎样划，原来我刚才划错了，从前往后退，靠着船外面的木头，再升回来。在爸爸的指导下，我会划船了。在一个地方，河面变宽了，有一只船划不回去了，我们帮助他们拿了一个桨，因为他们少拿了一个桨。给了他们桨后，我们发现自己也划不回去，因为风把我们一次次地吹了回去。最后，由爸爸用桨把舵，才把船划到了码头。我感觉很刺激。

   我还去玩了很多项目，有声乐、趣桥、单车、攀岩、英语沙龙等。

   我知道了做事不能用蛮力，要用巧劲，要以柔克刚。

** 写考试过程

   今天，我们考第二单元，我一拿到试卷，就迫不及待地做了起来，起初并不难，后来的阅读题就有点难，直到做到阅读题的第二小题，我想了好一会儿，也没想出来。我只好先写，再做这一题。做完了作文，又想这一题，好一会儿也没做出这一题。我觉得这题好难，心想这次肯定不会考得很好了。铃响了，交完了试卷，我才松了一口气，一看别人的试卷，我才发现我错了几题。

** 炎热的广场

   有人唱：“炎热的广场是一个童话世界，

  　　　　　走进广场，

  　　　　　你会变成超人。

  　　　　　展现神奇的魔法，

  　　　　　你会发现许多奥妙。

  　　　　　广场的雕塑让你陶醉，

  　　　　　许多游人使你惊讶。

  　　　　　花朵迎接你来到，

  　　　　　还有鸟儿表演才艺。”

   这时，超人来了，观众纷纷闪开地方让超人进来拍照。超人慢慢地到了观众中，向他们挥手，但此时一个怪物来了，在天空看着观众和超人，观众全吓坏了，都躲到超人身后，想让超人保护自己。超人说：“怪物，我要让你尝尝我的厉害。”说完，超人便和怪物打了起来，打了一会儿，怪物被超人打败了，观众全都兴奋地叫着。

** 参观奶牛场

   上个星期天，天气晴朗，是个出游的好日子。妈妈带我跟着五年级的一个小队去奶牛场参观。一路上，我们费尽周折，总算来到了滨海的挤奶场，我一看原来是一景乳业的生态牧场。

   已经快下午 1 点了，我怀着急迫的心情，一路奔跑终于来到了挤奶厅，沿着楼梯到了二楼，通过一排排玻璃窗，我看到底下有很多头奶牛，工人把奶牛依次赶进一个转动式的挤奶器。管子扎进奶牛的身体，接在一个盆子里，过了半分钟，牛没奶了，工人把它赶进宿舍。我还跑到了三四两楼逛了一圈，四楼是一个观望台。从那里放眼望去，牧场好大啊，一眼望不到边呢。

   接着，我和妈妈还来到一个草棚，草棚里栓着两只小公牛。我们小朋友争先恐后地抢着给小公牛喂草，我也用那边的草给小公牛喂了起来。起初，我有些害怕，怕被牛咬掉手指。后来就不怕了。哦，对了，这两只小公牛长着黑颜色的毛，有两只很小的犄角，身上还有白色的斑点，有点像斑马。说实话，我是第一次看见公牛呢！我还看见了旁边人工栽培的青储玉米。

   然后，我随着那边的工作人员，来到了展示厅。学习了关于奶牛的小知识，品尝了一杯新鲜的牛奶。

   这次来奶牛场，我不光知道了很多关于奶牛的小知识，还有很多收获，这一次真是意义非凡。

** 续写小木偶的故事

   小木偶自从没了红背包，身上就没钱了，成了一个流浪汉。这一天，他发现了上次嘲笑自己的小兔了。他到了小兔子的跟前笑嘻嘻地说：“嗨，小兔子，还认识我吗？”小兔子一看是小木偶，就说：“你啊，不是脑袋疼么，现在不疼了，是谁给你治病的？”小木偶愤怒地说：“你以为我不会另外表情，我已经会了！”像这样，小木偶做了一个痛苦的表情。小兔子说：“小木偶，我们来做个朋友吧！”小木偶说：“好的”这时，小木偶看到上次骂他的老婆婆。小木偶走过去说：“老婆婆，你为什么来到大街上，要买东西吗？”老婆婆说：“原来是撒谎的小木偶，这个讨厌的家伙，你又来了。”小木偶深情地说：“原来我只会笑，现在会了十二种表情。”就这样小木偶和老婆婆成了知心朋友。小木偶又看见小红狐背着他的红背包，从人行道走过。小木偶马上叫来警察。警察调查事情成功了。小红狐被处死，小木偶得到了红背包，回了老木匠的房子。

** 游萧山湘湖

   上个星期天，我们来到杭州萧山湘湖游玩。我们进入景区，走了一会儿，就看见有个小饭店，我们在里面坐了一会儿，又走了一会儿，看见前面水面上悬着一座用木头砌成的桥，中间有空隙，底下由两条铁丝驾成，左右有两根绳子，摇摇晃晃，风一吹，更是摆动得厉害，像一个喝醉的人在摇晃。我们一行人吓得是胆战心惊，不寒而栗。最后，爸爸决定他先过去，就这样，爸爸一马当先，就过去了，我在后面跟着。但是妈妈不敢过去，但后来在众人的鼓励下，妈妈也过来了。接着，我们又玩了好多景点，还在岸边追打嬉戏。对了，这儿的水很清，被称为西湖的姐妹湖。这儿还有 12 生肖桥，比如闻鸡桥、灵犬桥、玉兔桥等等。上面还有越王城，据说是越国的军事重地。

   我想下次还有萧山的湘湖玩，去看一看越王城。

** 奶奶家的金鱼

   前一段时间，奶奶买了二十一条金鱼，养在鱼缸里，还有很多石子、假的水草和假山。

   有一天，我一看鱼儿们在缸里追打嬉戏，其中有一条黑颜色，有着白斑点的鱼，它在鱼缸里上窜下跳，我称它为“黑将军”。还有一只全身都是白色的鱼，我称它“白将军”。还有 13 条孔雀鱼，除了颜色不同，大小样子都差不多。还有一条黄色的鱼，下巴是凹下去的，非常的狡猾，我叫它“黄军师”。另外还有三条棕黄色的鱼，一条灰颜色的鱼，嘴巴旁边有两根白色的胡须，不仔细看，看不出来，我称它为“灰白爷爷”。我给鱼儿喂食，鱼群就有一点儿乱，我想鱼儿应该爱吃鱼食，正合鱼儿的口味。鱼儿们抢鱼食吃，鱼食不是沉下去，就是浮起来。很快，放下去的鱼食都被抢光了。还有不少鱼被一些鱼拿去了几粒鱼食。我一看，又放进去了十粒鱼食，鱼儿们抢着吃，但是还有不少鱼还是没有吃到鱼食。

   过了几天，我往鱼缸里一看，孔雀鱼死了一条，还剩下 12 条，我又放进去了三只虾和一颗螺丝。过了一会儿，我发现虾都躲在石头后面，我想应该是虾也怕被鱼儿们吃。

   又有一天，我看见“黑将军”在咬“白将军”。“黑将军”一口咬住“白将军”的尾巴，猛地往外一窜，好像在跳水。就在这时，“灰白爷爷”咬住了三只孔雀鱼，三只虾跳了起来，在假山里跳来跳去。后来，我用鱼兜把它们拦住，它们才不咬别人了。这才结束了这场风波。

   今天，我又买了几条大鱼，我想让这些鱼自己玩，自己做一条听话的鱼，我希望它们快乐地生活。

** 运动会

   这周四，我们学校在开运动会，说起来真让人回味无穷。

   这一天，先是下雨的，所以先上第一节课。后来天晴了，学校开运动会，真让人琢磨不透。先是跑六十米的，我一看六十米跑了六次才跑完。后来我才知道是每个年级男女各一次的。六十米跑完了是两百米、垒球、铅球、跑步等都开始了，开了整整一上午，听说下午就要接力赛。我是参加接力赛的运动员。上午就这么过去了，中午吃完饭，老师让我们在教室里休息，我和其他人在下棋。马上就轮到了接力赛，我们在老师的带领下观看第一组接力赛，学习怎么接棒。接着就轮到我们了。前面的同学像离弦之箭一样超了上去，遥遥领先，把另外两个班级甩在了后面。轮到我了，我用尽全身力气，拼命地跑了出去。但是在后来，有同学棒掉了，所以我们班跑了个最后。但是我相信我们的速度并不慢，就是因为没有接住棒，才没了第一名。希望下次比赛，我们能得到第一名，弥补这次的失误。

** 《校园三剑客》读后感

   最近，我在看《校园三剑客 拯救未来世界》谜题版，以前我看过注音版的。现在的这本书让我过目不忘。

   这本书讲述了一万年后的地球，人类惨遭机器人的蹂躏。在机器人伯爵的凶残命令下，不计其数的无人轰炸机，如蝗虫般铺天盖地而至。那些曾经让人类引以为傲的大楼，如同面粉做的纷纷倒塌，像公交车一样大的蟑螂、老鼠以及其他各种奇形的基因怪物也趁火打劫，疯狂袭击落单的人类……这一幅幅触目惊心的情景，让乘坐时光飞船而来的“校园三剑客”大为震惊！他们三人还来不及做出反应，便被一群像高速列车一般袭来的变异毛毛虫所追赶……躲进地下后的三人，竟偶然发现了一个神秘的洞穴。而在这洞穴中，竟然沉睡着一位王子，他是地球人最后的希望。

   读完这本书，我知道了我们要保护环境。首先，我们要从身边的事情做起。不要乱扔垃圾，要回收利用，环保使用。到哪儿去吃饭，最好带自己的筷子，不要用一次性筷子。到超市里买东西，最好用自己的袋子，不要用那儿的塑料袋。等我长大后，要去当超人，去教育那些没有环保意识的人，让生活变得更环保。去把不懂得注意环保、乱砍伐树木的人叫到公安局去。

** 畅游水王国

   在一个阳光明媚的秋天，我来到环城河边游玩。美丽的环城河波光粼粼，在阳光的照射下，更加清澄通透。坐在长凳上，沐浴着阳光，欣赏着河边的美景闭目养神，暖洋洋的，我迷迷糊糊的睡着了……

   突然有一个小小的声音飘进了我的耳朵:“小哥哥，你是谁啊？”我转过身一看，是一个戴着蝴蝶结的小姑娘，但又和一般的小姑娘不一样，她长着圆圆的脑袋尖尖的腿，身上的衣服五彩缤纷，像是一条美人鱼。我脑子里突然跳出一个想法，“难道这是一个鱼人？”我刚要开口问，小鱼人好像明白了我的心思，自我介绍说:“我是粉色小鲤鱼丽丽，你呢?”“我是舒铭，这是哪儿？”她回答道：“这儿就是地下的水王国啊，你也是小鲤鱼人吗？”“不是，我是住在附近的小朋友，我正在环城河边玩呢!”丽丽一脸兴奋说：“那你就是我们的朋友了，欢迎你！现在由于你们人类的重视和保护，我们的王国越来越干净整洁了，住在这里可比以前舒服多了。”“哦，真的吗？”

   这时，又游过来了一群鱼。“丽丽，国王让你回王宫吃饭，你赶紧去吧!”丽丽说：“伙伴们，我们一起去吧。对了，铭铭小哥哥，你要和我们一起去王宫吗？”“好啊，我也参观参观你们的水世界。”

   鱼儿们带着我，飞快地行驶在水中，我们潜入水的深处，我觉得半身沉沉，像鸟儿一样轻飘飘的，周围的水就像一块碧绿的丝巾，滑滑的，柔柔的，在我身边飘过。还有很多小鱼人友好地“啊呜啊呜”地叫着，和我们打招呼，为我们让行。

   不一会儿，我们就来到了宫殿。宫殿金碧辉煌，气势宏伟，整洁漂亮，和龙宫有得一比。我们一行人进入宫殿，抬头看到在中间的金灿灿的宝座上，坐着一位老鱼人，雪白的胡子长得拖到了地上，非常和蔼可亲，他乐呵呵地问:“小朋友，欢迎你来到水王国，听我的手下说，这段时间，原先王国里多年来的杂物都慢慢消失了，我正奇怪呢，你能给我讲讲外面的事情吗？”

   难道这位老国王讲的外面的事情就是新闻和学校老师讲过的“五水共治”吗？幸好我以前参观过保护水资源的展览，也看过“五水共治”的新闻，还记得一些，就脱口而出地：“报告国王，这里是水乡绍兴，自从开展五水共治以后，周围的水确实越来越干净了，我在学校里学过不少保护水环境的知识呢。我还知道‘五水共治’就是治污水、防洪水、排涝水、保供水、抓节水。现在绍兴可是一个美丽的现代水城，一年一度的国际皮划艇马拉松前不久就在环城河里举行呢!”

   鱼人国王呵呵地笑了，说:“小朋友，懂得真不少啊，如果真是如此，那我就安心在这里养老了。”旁边的丽丽突然插话道：“父皇，我看你们聊了这么久，大概肚子饿了吧，我们一起去吃大餐!”我突然才发现，原来这个丽丽，是国王的女儿，是一位公主呢。

   我听了连连摆手，忙说:“谢谢，不用了，我妈妈喊我回家吃饭呢。要是回家晚了，妈妈会着急的。”国王说:“还真是一个孝顺的孩子，赶紧回家吧。我送你一程，随便也到岸边看看外面的美景。”说着一抬手发出一道金光，我终于回到了现实世界。[fn:21]

** 一次马戏表演

   人人都有经历过挫折吧，你放弃过一次了吗？

   今天是星期六，我和同学约好去看马戏。可我早上一醒来，就觉得身体不好。身体实在是太难受了。早上七点醒来到十点钟还没有起床。爸爸妈妈一直说：“快起床，不然没时间看了，你快起床呀！”我虽然人不是很难受，但也还是不舒服，根本听不进爸爸妈妈的话。直到十点三十二分了，我才觉得很想起床，但人还不是很舒服。我一想：“忍一忍吧！去看马戏吧！要坚持！”最后，我还是一咬牙起了床。

   姑姑开着车来接我们。一上车，车里暖洋洋的，非常舒服。但是开了一会儿，我就觉得很不舒服了。我一闭眼，想休息一会儿。但到了目的地，只好下车。一下车，我就觉得很难受，有一种想吐的感觉。才走了几步，我就吐了。周围的人不停地安慰我，我才觉得好了一些。我们进了大门，走到看马戏的地方。我又觉得头昏眼花，非常难受，有一种不可形容的难受。我在心里鼓励自己，加油一定要坚持住，不要放弃，放弃就要失败。我看着周围的绿树，心中的苦恼顿时减轻了不少，身体又变得舒服了。就这样，我们进了马戏表演场。开始看马戏表演了，节目有太空漫步、空中钢丝等。实在是太好看了。我真感谢我心里最后的选择。

   通过这次看马戏表演的经历，我明白了一个道理：一个人如果想成功，不能随随便便地做事，要一步一步踏实地去做，遇到困难，不要放弃，要坚持，才能成功。

** 未来的笔

   时间过得飞快，转眼间就来到了 2085 年，我是 X 博士，我发明了一支具有很多功能的笔。让我来为你们介绍吧！

   这支笔是蓝色的，在笔上有几个按键。你可不要小瞧这几个按键，它们可有作用呢！在笔帽旁的那个按键，是修正字的按键，如果你把字写错了，只要用笔头放在那个错字上，只需按这个按键，就能消失笔迹。这是轻点按，如果重点按，它就成了你的坐姿监视器。只要你一不坐好，它就咕咕地叫，提醒你要坐好。但是，如果按多了这个键，笔可是会出故障的。也许你会认为，那如果笔出故障，不就没有用了吗？没关系，在这支笔的笔芯管子的左侧，有一个修复按键，不管你是断墨、没墨，还有爆墨等等情况，它都可以修复。如果你的笔芯断墨，它会把你的笔芯调整一下，让它不再断墨。如果笔芯没墨了，它可以用笔里的自动装置装好笔芯，但是装得可能是不好的笔芯，它也是可以自动修复的。

   我告诉你如果是别的笔芯，红色的、蓝色的，如果按一下修复，它可以把它转换成黑色笔芯，但如果是黑色笔芯转换不成其他笔芯。这支智能笔尾部有一个中控器，它是控制笔的按键。

   那如果它没电了怎么办？我告诉你，它是用你自己人体的热能，如果你触摸它，它就立刻变得电足了，像一个皮球。

   这就是我的发明，神不神奇呀！

** 我发明了汽车

   2088 年到了，终于成功了，我兴奋地叫道。转眼间，客厅中就出现一辆外形美观、构造精致的汽车。告诉你吧，这是我 X 博士发明的。

   这辆车是红蓝相间的，整理来讲，外形美观。车的扶手这儿有一个按钮，这是整辆车的中心，只要按一下这个开关，车门就会打开，你坐进去，整辆车就会腾空而起。你说停在哪里，它就按照你的指令来行动。如果你不想飞行，想在陆地上行驶，那更不是难题，你只要按一下驾驶舱左边窗户的一个按钮，就能自动行驶了，并且都是很安全的。你只要按一下另外的按钮，就能听音乐，看电视、上网等，而且你还能按副驾驶中间的一个按钮，就可以下海。而且汽车的轮子可以变成潜水艇的轮子。而且你可以放心大胆地在海底娱乐。如果你想要知道海底的东西，你可以用电脑的显示屏打字搜索周围的事物。如果你觉得海底太暗，你可以打开车前灯，照亮海底。这辆车还可以自动洗车。也许你会说：“不可能，不可能，怎么能自动洗车呢？”只要按一下车里的窗户键，它就自动洗车，整个车身变得焕然一新。还有它的后备箱比其他后备箱的空间大，足足大十倍，可以放很多东西。尽管这是幻想，但是我相信在 2088 年，一定会有这样的智能汽车的。

** 让爱走进心灵

   有一次，我摔跤了，膝盖流血了。妈妈看到后焦急万分。回到家后，她一点也没有来得及休息，就拉着我的手，带我进了卫生间，用清水清洗我的伤口。我那时很害怕，因为我怕疼。但是妈妈不停地安慰我，最后我还是坚持用清水洗伤口。洗完后，我用湿毛巾敷伤口，然而只有一点点疼。我心里也不紧张了。用清水敷完伤口后，妈妈又给我贴上了创口贴。一股热泉涌上我的心头。

   后来，我又不小心摔了一跤，膝盖再次流血，妈妈还是无微不至地呵护我。

   不仅如此，在平时，妈妈一直在关心呵护我，给我改作业，讲错题。我想起我好几次惹妈妈生气，真是不应该啊！而妈妈对我的关心则始终不减。虽然我现在也在学习妈妈，能自己做的就自己做，但是要妈妈干的活还是很多。

   我们的爸爸妈妈也一样，都是无私奉献的，不求回报，只求子女们成绩优秀、开心快乐。他们的奉献远远超过了回报。所以我要快快长大，快快帮爸爸妈妈分担苦恼和忧愁。

** 当一回“罗马士兵”

   今天，我们全家怀着兴奋的心情又去当了一回“罗马士兵”。

   什么？你是“罗马士兵”？其实，我是去参加“罗马战车”挑战赛决赛，实际上我已经当了一回罗马士兵了。虽然我已经进入了总决赛，但是我还是有点紧张。

   比赛分为四个环节，分别为“战车拼装”、“飞天入地”、“请球入桶”、“拆车大师”。比赛开始了，首先大家都专心致志地做着自己的“罗马战车”。转眼间，便有几组家庭做好了罗马战车。我顿时惊讶无比。

   “飞天入地”是指用队员自制的“子弹”用“罗马战车”的“投石机”打出去，看谁的子弹飞得远。在比赛过程中，有的子弹向左边飞，有的子弹向右边飞，还有的甚至往队员脚下飞，所得成绩为负数。但是失败是成功之母，有失败也有成功的。其中表现最优异的是 19.78 米和 21.43 米，那真是真正的飞天入地啊！

   “请球入桶”是指一边的队员用“罗马战车”的“投石机”把子弹打出去，而另一边的队员却要把子弹接进塑料桶中。真是非常难呀！既要一边的队员发得准，又要另一边的队员接得准。但最好的九枚里接住了七枚，真是潜力无限、熟能生巧啊！

   “拆车大师”就是指每个家庭将“罗马战车”拆除。

   在这次活动中，在“战车拼装”环节，我和爸爸妈妈努力拼装，坚持不懈。在“请球入桶”环节，我来接球，九枚中了三枚。而在“飞天入地”中，我最好的一次又 16.25 米。在最后的战车拆除时，我们也很认真的完成了任务。虽然我们在初赛中也厉害无比，但我在这次决赛中，照样心中紧张。不管以前多有基础，在决赛时，还是会紧张，所以要不断挑战自我，才能成功，才能赢得比赛。

** 一次有意义的小队活动

   寒假里，我组织了一个小队，叫“阳光小队”，我是队长。小队的辅导员就是我的妈妈，她组织我们去绍兴市图书馆的少儿馆整理书籍。活动那天，我和队员们都早早地来到少儿馆。那里的阿姨热情亲切地接待了我们。她先教我们怎样整理书，按照书脊上贴着的红色、绿色的标志把书分类，再按大小排放，一套的放在一起。然后，我们大家立刻热火朝天地干了起来。我让队员们两个一组，正好八个人，分为四组。小朋友们专心致志地理着书。整理书籍看看很简单，但做起来，并不容易。有的队员力气小，搬不动重的书，有的队员个子矮，够不到上层的书。我身为队长，身先士卒，互帮互助，完成任务。不一会儿，乱摆乱放的书就被我们整理得整整齐齐，像是刚放上去的新书一样，看上去赏心悦目。图书馆的阿姨都夸我们理得好，干得棒！

   少儿馆里有很多很多书，真是书的海洋。我们整理完书后，就迫不及待地挑了自己喜欢的读物聚精会神地看了起来。看了一会书后，我组织队员们离开少儿馆，来到了旁边的展馆。那里正在进行书画展。在展馆里，大家兴致勃勃地看着，七嘴八舌地议论着，学习着博大精深的书法和美妙绝伦的美术作品。不知不觉，快到中午时分，我们依依不舍地离开了图书馆。

   这次小队活动，让我学到了不少知识。书籍的整理不仅让我感受到劳动的乐趣，而且更体会到团队的力量。观看书画展让我欣赏到了绍兴书画家们的精美作品，受益匪浅。这次小队活动真是收获满满啊![fn:12]

** 游玩小亭山

   今天，天气晴朗，阳光明媚，是个出游的好日子。我和爸爸妈妈、姑姑表弟一起去风景优美的小亭山玩。

   我们先走上长长的陡峭的山路，不一会儿，我和表弟就累得筋疲力尽。最后我们总算上了小亭山的大门。再走上长长的石阶，终于到了小亭山中的永和塔。这座永和塔共有八层，建成于 2004 年，是六边形混合结构的塔，高 73 米。我们进了塔内，底层有电梯。我们乘坐电梯，到了塔的最上层观望台。从最上面极目远眺，绍兴的城的风貌尽收眼底。其实，塔的每一层都有文化成列，主题都不同，第一层是永和长春，两三层是亭山道古，四五两层是有关山阴道的历代绘画、诗歌文章等，六层为历史掌故，七层是“南河风采”。这是我查了资料了了解到的，当时我只看了第二层塔壁的文化陈列，下次有机会再去的话，再把每一层的文化陈列都好好看一下。

   这一次游玩小亭山，不仅锻炼了身体，还欣赏了美景，学习了知识。这一次真是收获满满啊！

** 参观绍兴市科技馆

   今天是个出游的好日子，不仅没有炎热的太阳，而且我如愿以偿地去了科技馆。

   我们先来到了科技馆的运动与科学展厅。在那里，我看到了许多球拍的构成，还看了许多运动的视频。还打了乒乓球、拳击。其中，拳击我打到了 180 千克，还测了血压等。我跑了一公里多。之后，我们就来到了“探索与发现”展厅。

   在那里，我玩了竖金蛋、气流投篮等项目，玩得不亦悦乎。我还跟着“金猴”玩了一次气流投篮，拿了一个书签。我还让机器人给我画了一张像呢！

   玩了一会儿，到了“魔力科学秀”节目时间了，我跟着人群来到展厅外的大屏幕前。主持人一开场就给我们演示了一个“水果弹钢琴”，在互动环节中，我是第一个举手参与的。一开始我觉得很奇怪，水果怎么能弹钢琴呢。我一上台才知道原来水果里装了电线，才能像钢琴一样。主持的阿姨教我弹了一首“小星星”呢，引得观众热烈的掌声。接着，我又看了水往高处流、自动吹气球等科学实验，我觉得很有趣了。

   听完“魔力科学秀”后，妈妈说在地球与生命展厅里，正在进行“小喇叭、大讲堂”活动，就带着我去那里听了一会，然后，又参观了这个展厅，并且看了两个宣传片和各种资料。接着，我们又在旁边的地方猜了谜语，在爸爸的帮忙下，一共猜出了两个，一个谜底是短路，另一个则是照相机。抽奖分别获得了一个孔明锁和一本知识小册子。

   这一次参观科技馆让我受益匪浅，不仅懂得了许多奥妙的科学知识，还亲子体验了许多有趣的科学实验，这次参观真是很有意义啊！

** 走进《俗世奇人》

   世界上有许多千奇百怪、有着一手绝活、会绝技的人。在假期里，我走进了书的海洋，看了一本名为《俗世奇人》的书。这本书是冯骥才写的，讲述了在天津卫城区近一百年，许多有本领、有绝艺的人的故事。

   这本书由十八篇短文合成。里面有神医之称的苏七块和华大夫，有能说会道的快嘴杨巴，有精打细算的蔡二少爷和重义气的李金鏊，还有力气非凡的张大力、钓鱼神人大回、绝盗小达子等。俗话说“三百六十行，行行出状元”，每一行，每一业，只要勤奋刻苦地练习，都能熟能生巧，成为这一行的奇人。这些人之所以能有这么多本事，都是由于他们背后付出的艰辛和汗水。比如说苏七块，他就是一位内科专家，他有这么大的本事，都是他艰苦努力的结果。

   在《俗世奇人》中，我最佩服的是刘道元，因为他不仅在当地名气大，而且人品好，乐于助人。他假装进了一次棺材，发现许许多多人趁机报复，拿他家产。最后，他一出棺材吓走了所有的人。

   这本书中的人物个个本领高超，都有独一无二的绝活，虽然不是我们能轻易学懂的，但是，我觉得每个人非常有必要掌握一项或多项本领，就像书中的十八位奇人一样。特别是在生活中，要学会生存的本领、劳动的本领、学习的本领等等。在学习本领的过程中，在碰到困难和挫折时，我们要微笑面对，要有一股永不放弃的精神。就拿我暑假里学游泳的事情来说吧。一开始，我担心淹死，又怕冷，所以连水都不敢下。我一度想放弃，但是妈妈不断鼓励我继续学下去。我克服心中的恐惧和困难，甚至连后来耳朵发炎了，我还是坚持到底，不断地练习，坚持不懈，最终学会了游泳。

   看完这本书，我受益匪浅，《俗世奇人》值得一看，耐人寻味！[fn:13]

** 看《功夫熊猫 3》有感

   今天下午，爸爸带着我来到卢米埃影城，观看电影《功夫熊猫 3》。这部电影是我很想看的，今天总算能如愿以偿地看这部电影。

   这个故事围绕阿宝失散已久的亲生父亲突然现身，久逢的父子两人一起来到一片神秘且不为人知的熊猫山庄。在山庄这里，熊猫阿宝遇到了许多有趣滑稽的同类。但当天，拥有神秘力量的天煞横扫神州大地时，熊猫阿宝便把村民们训练成了功夫高手，与天煞进行对抗。可最终遭到失败，但最后阿宝到了灵界，眼看就要死亡，但它最后并没有死，因为它的朋友最终靠着坚定不移的信念，获得了气功，方使阿宝活下来，打败了天煞。阿宝就变成了乌龟教的传承人。

   在电影中，我最喜欢的是阿宝，因为它不仅滑稽有趣可爱，还是几次拯救世界于水火的神龙大侠。不过，它还是谦虚地看着盖世五侠的绝招。

   在电影中，我最佩服的是娇虎，因为它身上有着机智聪明的精神，它是阿宝最好的伙伴。

   看了这部电影，我学到了一种精神团结。如果阿宝的伙伴不一起团结来救阿宝，阿宝就会死在天煞的手下，所以团结精神很重要。

** 美丽的诸葛仙山

   寒假里，爸爸、妈妈、姑姑、爷爷、奶奶带着我和表弟去风景优美的富盛，顺路去游了一下诸葛仙山。

   我们先来到了诸葛仙山的诸葛广场，抬头往上望，诸葛仙山高耸入云，危峰兀立，险如斜的线条一样。据资料，诸葛仙山 572 米，是绍兴第三高峰，比香炉峰还高。接着，我们便走进山门，“诸葛仙山”四个大字映入眼帘，左右是一幅对联。在左面，我看见有一尊雕塑，雕塑中介绍的是东晋在诸葛仙山炼丹者和道教学者——葛洪。右边是一个大大的池子。池水碧蓝，蓝得视乎比蓝天还蓝。一阵风刮来，一池子的水就漾起条形的波纹，非常好看。再加上两旁竹林小道，显得十分幽静。再往里走，不到十步路，呈现在我们面前的就是炼丹台遗址，树木横生，怪石嶙峋，似乎让我感觉到了一丝“仙气”。

   再走了几步路，一旁刻着的一块块石碑上全是描写诸葛仙山的诗句和介绍，其中有《广陵散》、《雪竹》等诗词。

   之后，我和表弟便走向竹林，通向竹林里的小路真崎岖啊！怪石嶙峋，一段段路好像一个个险峻的山坡，好像一不小心就会掉下来，但我和表弟还是走上了竹林的最高处。

   再走了几步路，便来到了一个绿色的潭，这个潭水真绿啊！绿得像一块无瑕的碧玉。潭水真清啊！清得可以看见潭底的沙石。潭水真静啊！静得可以听见潭底的动静。

   再往里走，就是上山的路。走了不一会儿，我们就看见一个阿姨在砍毛竹，我们知道了原来毛竹也很有用。

   之后，我们便来到了八卦田，这个八卦田相传是葛洪当时在诸葛山炼丹时开辟的。由于时间紧迫，我们只爬了大概四分之一，但从这里往下看，人和树木都变得如同蚂蚁一般，我想四分之一都这么高，那诸葛仙山的顶峰肯定会更高。

   诸葛仙山两旁毛竹耸立，再加上空中云雾迷蒙，正好似走进了仙境。

   这就是富盛的诸葛仙山，希望你有机会来诸葛仙山玩。

** 东村赏梅

   寒假里，我和爸爸妈妈、姑姑弟弟、奶奶去平水王坛镇的东村去赏梅花。

   进了东村，一股梅花香味迎面扑鼻而来，使我们觉得神清气爽，本来疲惫不堪的身体顿时变得有精神了。我又看见两旁的梅花一簇一丛散发着清香。一棵棵梅树，梅树有着红的、白的梅花。梅花的花苞宛如一颗颗珍珠，而花枝向我们招展，似乎在说: “欢迎，欢迎你们到来！”两旁的梅花迎风招展，迎风舞动，为寂静的小路增添了无数生机。

   再往里走，满是梅花，田埂里的梅花更美，一簇簇，一丛丛。无数的梅花似乎在向我们招手。瞧，那挂满花朵的枝干迎风舞动，多美啊！有的花苞绽放了，如一个个展开的金圈，有的花苞还没绽放，如同一颗颗果实。这些花朵迎风摇曳着，十分美丽。

   再往里走，便是一块大草坪和一个大水库，草坪上有一些健身器材。抬头望去，漫山遍野的都是梅花。红的、白的，争相吐艳，个个都想表示得引人注目。但我们由于时间紧迫，所以就没有走上山去。

   王坛东村的梅花很美，希望你有机会来这里的香雪梅海细细游赏！

** 妈妈，我想对你说

   #+LATEX: \noindent
   亲爱的妈妈：

   妈妈，你昨天生气了。因为我在玩游戏。但是你也不能不顾一切地阻止我玩游戏。我相信你能让我放松一下，玩一会儿游戏的。

   不过，妈妈，我也不会玩很长时间，不然会浪费时间的。你也应该体会一下我的心，被你这么一说，我非常难受。而让我玩一次游戏，心情就会很舒畅。但我也明白你的心思，你是不想让我浪费时间，把时间用到正道上去。到难道你就不能让我体会一下游戏的乐趣，放松一下？我相信你会让我放松一下的，玩一会儿游戏的。

   但我向你保证，每个星期六总共玩三盘游戏。而且会合理安排时间、合理休息的。而且我会让妈妈你不操心，自己管好生活与学习。妈妈，我希望你也能管好自己，不要为游戏一点小事而烦恼、操心……

   玩是儿童的象征，是儿童的翅膀，是儿童的欢乐，为了让学习不枯燥，请投入一点玩。妈妈，让你给我一点时间，让我来玩游戏吧！让我来放松，让我愉快吧！

   　　　　　　　　　　　　　　　　　　祝妈妈身体健康！

   　　　　　　　　　　　　　　　　　　　　　　舒铭

   　　　　　　　　　　　　　　　　　　　　　　2016 年 3 月 19 日

   #+LATEX: \vspace*{\baselineskip}

   #+LATEX: \noindent
   *（修改稿）*

   #+LATEX: \noindent
   亲爱的妈妈：

   #+LATEX: \marginpar{\footnotesize 妈妈寄语：文章修改得不错，不过此文后面即 “你不让我自己上学自己走路。”不真实，事实是妈妈让你自己回来，是你不想自己锻炼，不想自己走回来哦！}

   妈妈，你昨天陪我去玩。在旅游时，我走得快了一点，你跟不上我的脚步。你就不分青红皂白地斥责我，一定让我跟你同步走，不能走在最前面，你一直说这句话。

   在这几次旅游中，你都是这样的。不让我单独走在前面，你也应该体会一下我的心，被你这么一说，我非常难受。但我也明白你的心思，你是不想让我有危险。我相信你能让我放松一下，自由一点。

   而且我会向你保证，我会保护好自己的。而且，你不让我自己上学自己走路。我长大了，你应该让我自己去克服困难，虽然没有你的呵护，我会多一些挫折。但是我就能多一些生活经验。如果我大了，你难道还能来管我吗？所以请你让我锻炼一下。

   在温室里的花朵长不成参天大树，在牢笼中的困兽最终会丧失野性。所以请投入一点挫折困难。给我一点时间让我来体验生活吧！

   妈妈给我一点时间让我来锻炼自己，让我愉快的生活吧！

   　　　　　　　　　　　　　　　　　　祝身体健康！

   　　　　　　　　　　　　　　　　　　　　　　舒铭

   　　　　　　　　　　　　　　　　　　　　　　2016 年 3 月 23 日

** 宛委山看樱花

   今天，天气晴朗，我和妈妈一起去宛委山看樱花。

   一进宛委山景区，门口两只石象，好像是守护大山的两个卫兵。而吸引我们的是大片成群的樱花，有红的、白的、粉的，清香扑鼻。虽然在枝上的樱花所剩无几，但也散发着清香。景区内游人如织，大量的游客在拍照做纪念。

   再往里走，樱花一阵阵的清香迎面扑鼻而来，使我格外清爽。微风徐动，树上的樱花便散发着清香，让宛委山显得更美。有樱花这样点缀着整个景区，大山能不美吗？这真不愧为华东地区最大的樱花之一啊！

   再往里走，便是樱花园。园内游人数量不减。园内一股清香，使人格外舒服。花枝招展，随风舞动，无数的花朵点头，似乎在说：“欢迎你们来啊！”这些花各有各的姿态，有的亭亭玉立，有的随风舞动，一朵朵映入我的眼帘，实在太美了。无数的樱花好像都在向我们招手。瞧！那劲翠的枝干迎风飘动，多美啊！

   突然，一个“孙悟空”打扮的人映入我的眼帘，为景区增添了无数的生机。

   宛委山的樱花非常美，希望你有机会来细细欣赏！

** 春游

   这星期五，学校组织我们去迪荡梅龙湖公园春游。

   我们早早地到了学校，大家在教室里玩玩具，吃东西，每个人都是一副兴奋的样子。公交车一来，大家争先恐后、迫不及待地上车。一路上，大家兴高采烈，说说笑笑，好不热闹。

   到了梅龙湖公园，两旁柳树依依，花儿绽放着笑脸，到处都是春的气息。前几年，我就是在这里种过树呢！

   越往里走，两旁全是著名电影演员的雕塑。再往里走，便走到一座陡峭的桥，这座桥两旁的脚下是钢筋。钢筋错落有致，这座桥非常牢固，可以通向世贸。

   又走了一会儿，便到了一块平地，我们在那里吃东西。在这块平地上，大家都在互相交换着食物，分享美食。李老师还给我们拍了照。大家互相吃了一点东西，有的人就在玩三国杀，有的在玩一种牌。大家各自游戏，非常开心。

   过了一会儿，我们便往前走。前面走了不到一会儿，各种花争相吐艳，非常美丽。我觉得迪荡好新啊！记得上次我在这里种树的时候，迪荡还没有现在建设的好。再看那梅龙湖公园，分成迪荡胡公园和电影文化公园。现在的迪荡建设得真好呀！

   时间过得很快，马上就到了中午时分。我们依依不舍地离开了迪荡的梅龙湖公园。梅龙湖公园建设得非常好，希望你有机会来游玩！

** 我发现了金鱼的秘密

   大自然，有许多奇妙的事，如壁虎的尾巴能断了又长，仙人掌生命力强，地震前老鼠到处乱跑，变色龙可以变颜色等。

   上上个星期六，奶奶买了九条金鱼，金鱼很可爱。

   金鱼也有奇特的一面，让我来告诉你吧！

   在奶奶家，我经常观察金鱼的游动、嬉戏等几方面。一天夜里，我出去拿东西时，看见九条金鱼眼睛睁着，而鱼却没有游动。我以为它们死了，用渔斗一碰，还是没动静。又碰了几下，金鱼们终于游了。不一会儿，金鱼又不动了，眼睛还是睁着的。真奇怪！我断定金鱼是睁着眼睛睡觉的。早上我问了爷爷，爷爷说应该是金鱼没眼睑，我问眼睑是什么，爷爷说眼睑就是眼皮。

   到了白天，我喂鱼的时候，发现鱼群又动了起来，一切都是那么自然。我认为爷爷说得是对的。

   为了再深入知道（了解）这个问题，我便上网查阅资料，一看才发现原来是因为金鱼没眼睑，所以不能闭上眼睛。这样看上去好像它从不睡觉一样，大多鱼睡，只保持水中的宁静状态，就像人睡觉时那样，金鱼就是用这种方式使它们的身体得到休息的。

   看了回答，金鱼为什么不闭眼，就是没眼睑，眼睑就是眼皮。

   是啊！大自然有很多奇妙的现象，大自然真是我们的好老师啊！

** 美丽乡村——绍兴棠棣

   今天下午，天气晴朗，我们一行五人驱车来到最美乡村棠棣。一下车，便看到棠棣村的介绍栏和著名人物。一路走着，两旁是一幢幢独立的别墅，房子好像古典的欧洲农庄外墙用大块大块的很有特色的石块磊砌而成，像城堡一样。每户人家的门两旁挂着对联，外墙挂着花篮，连下面的出水口还贴着“雨水”的字眼，真是规划得细致入微啊!路面非常干净整洁，走在路上，感觉神清气爽，不愧是最美乡村啊！我查看了资料后才知道：棠棣是绍兴县漓渚区的一个村，有花木之村的美誉。在前不久的兰花节里，游客那真是人山人海。我似乎也闻到了兰花的芳香。

   再往下面走，走了不到一会儿，就看到一口偌大的水池，池面上飘荡着两只乌篷船，一照壁上镶嵌着不少酒坛，有水从酒坛口往下流出，流入水池。照壁上还写着“美丽棠棣”这四个大字。一看介绍，才知道，原来这个景点是“庙池醉月”，由兰谷亭、庙池、酒坛、照壁所组成。池水清清，兰谷亭也仿似一座仿古长廊，再加上一块照壁的酒坛上喷出的泉水，真是一幅美丽的画面。

   之后，我们便走进了旁边的兰苑，里面培育着很多兰花，有各种品种，比如“神话”、“廿七梅”等品种，天花板上吊着兰花。还有两张很有特色的桌子，桌子上摆放着茶具。正门口还有一个大大的“兰”字。

   接着，我们乘车一路行在干净的公路上，两旁时而群山环绕，时而花木葱茏，其中还有一两个水库。真是青山绿水，空气清新，风景秀美啊！我们还在附近的花棚养殖户里买了一些花，也算不负此行。

   棠棣很美丽，希望你能来我们绍兴最美乡村棠棣游玩，品味花儿的芳香，体验棠棣的美丽吧！

** 一张旧照片

   我在床前发现了一张旧照片，这张照片正是日本轰炸上海火车站时，被记者拍下的情景。一见这张照片，当时的情景顿时呈现在我眼前。

   原先不轰炸前的上海火车站，本是繁华一片的景象。那时，在火车南站是人山人海，为什么火车站会人山人海呢？因为大家乘火车逃难，逃往中国各地。突然，天空发出了声响，原来是日军的飞机在天空上盘旋。不知是谁说了一句“大家快跑！”人们四处逃散，妄想逃出火车站，但有些人惊慌着，尖叫着，逃窜着，但日军的飞机仍不放过这些手无寸铁的百姓。日军在飞机上投下一个个的炸弹，炸向那些百姓。百姓东奔西跑，但还是躲不过日军的炮火。不一会儿，倒下了许多人，剩下的百姓呻吟着、挣扎着、叫喊声充满了整个火车站。日军的狂轰滥炸把繁华的火车站炸成了一片废墟。日军一看，火车站已成废墟，便扬长而去。

   突然，一个微小的声音传入了我的耳朵。“爸爸妈妈，你们在哪里呀？”但没人回答，之后便是一阵钻心裂肺的哭声。我一看，原来是一孩子在铁路上坐着，大概只有二三岁。可能在之前，他还在爸爸妈妈的怀抱里。而现在，他没有了父母，也没有了亲人的照顾，更没有了今后幸福的生活。他都不知道离开父母后他会怎样生活。

   日本人，你们也有自己的父母，你们怎么能杀这些手无寸铁的百姓呢？

   我又回想我们现在，现在我们生活在优良的环境里。所以我们更要珍惜现在的环境，为战争敲响丧钟，在和平的环境中幸福生活吧！

** 穿针引线——仿真线装书制作

   今天是世界读书日。杜甫说：“读书破万卷，下笔如有神。”高尔基说：“书籍是人类进步的阶梯。”笛卡尔说：“读一本好书，就是与许多高尚的人谈话。”从中国到外国，书籍是非常重要的。

   今天，我和爸爸去绍兴市越城区图书馆参加“穿针引线——自己亲手做一本线装书”活动。我们先拿到一本书，接着又拿到线和针。工作人员教我们怎么穿书、装饰书。我和爸爸按照工作人员的教法，先用线量出书的七倍，之后把线对折，穿进针眼里。之后把两头打结。先拿出两根线头，右手的线头在底下，左手的线头在上面，之后以左手大拇指的大小穿一个洞，把右手的线头拉出。这样两头就不会散了。之后把针穿向书的第二个孔里。书有四个孔，之后拉出，留着大概半边书的长度，再把针从书的中间挑出来，把线头留在书的中间部分。然后再把第二个孔的线拿出来，再穿下去，再拿出来。这样正反共穿三次，四个孔，就是穿十二次。最后，用一个巧妙地方法将线打得非常漂亮。书就这样装好了，感觉很漂亮哦！

   本来还有两个活动即体验碑拓技艺和古籍修复技艺展示，由于时间关系，我没有参加，不过我还看了旁边的古书介绍。

   这次参加仿真线装书制作，我不仅体会到书籍装订的乐趣，还知道了一些古书的知识，收获满满！

** 我的一个星期天

   在上上个星期天，我和表弟在奶奶家玩。

   上午，我和表弟去水果市场买水果。我买了苹果，表弟买了鸭梨，奶奶买了芒果。

   之后，我们就去看电视，看《植物大战僵尸》。看了一会儿，我觉得这个电视很好看。既体现出了植物的机智，又体现出了僵尸的凶残。过了一会儿，我们便去下面玩。这时，我们看见爷爷奶奶和爸爸来了，便跑了下面。跑到下面，发现奶奶他们追下来了，我们赶紧往“空中花园”跑。“空中花园”就是一个漂亮的花园。但由于爸爸跑得快，所以我们就被追上了，但我从口袋里掏出七根棉签，拿了一根棉签扔向爸爸，爸爸一躲。之后，我们就跑进了“空中花园”。但爸爸又追了过来。我们便跑向物业，但被爷爷奶奶挡住。我又扔了两根棉签，才躲过了这一挡。但我发现表弟不见了，去哪儿了呢？去停车库了吧！我正想去停车库把他叫出来，发现他来了，他在奶奶他们后面。我们便上楼了。

   下午，我和邻居羿奇澳出去放风筝。我们一开始放，就放不上去。然后，我们一直放都放不起来，后来有人教我们放了一下，我们就会放了，而且放到最高了。

   这就是我快乐的一个星期天，你有这么快乐的一天吗？

** 一件使我高兴的事

   我曾经有一件高兴的事，让我来告诉你吧！

   我又学了几节课，漂浮、屏气已经学会了。但有些高难度的动作还不会。后来发现耳朵发炎了，游泳学习就中断了。

   等耳朵炎症好了以去年暑假里，妈妈给我报了一个游泳兴趣班。我不等教练说下水，就已经下水了。之后，我马上就出来了，因为水太冷了，我不得不再跳出水来。我在旁边休息了一会儿，又一次下水，这次水不太冷了。教练教我屏气，我刚头下水，就冒了出来，大概只屏了一秒钟吧！练了五六节课，最多也只能屏三秒钟。教练让我在家练习，虽然我在家练习，但我还是只能屏个三四秒。对我来说，游泳时一种苦恼。妈妈觉得我没有多大的进步，所以就给我换了个教练继续学下去。

   后来，妈妈又给我报了一个班，我说我不想学了。但妈妈说：“学习要一鼓作气，再学几次就学会了，要坚持哦！”我鼓起勇气，继续学游泳。

   在最后一次学习中，我学会了蛙泳，虽然最后的换气还不太会换，但至少有了好大的进步。我终于能在水中游大概 15 米，我终于能在水中游了。啊，我真高兴啊！这真是一件值得我高兴自豪的事情！

** 国旗下讲话——爱我中华，勿忘国耻

   敬爱的老师、亲爱的同学们：

   大家上午好！

   在蓝天下，迎着初升的太阳，我们举行这庄严的升国旗仪式。今天我国旗下讲话的主题是“爱我中华，勿忘国耻”。

   大家还记得吗?我们四年级下册的语文课本中印有一张旧照片，这张照片正是日本轰炸上海火车南站时，被记者拍下的真实情景。看着这张照片，当时的景象顿时呈现在我眼前……

   原先的上海火车站，本是繁华一片的景象。那时，在火车南站是人山人海，因为大家乘火车逃难，逃往中国各地。突然，天空发出了一阵阵巨大的声响，原来是日军的飞机在天空上盘旋。不知是谁说了一句“日军的飞机来了，大家快跑！”人们惊慌着，尖叫着，四处逃串着，但日军的飞机仍不放过这些手无寸铁的百姓。日军在飞机上投下一串串的炸弹，炸向那些百姓。百姓大叫四散逃跑着，但还是躲不过日军的炮火。不一会儿，倒下了许多人，剩下的百姓呻吟声、尖叫声、叫喊声充满了整个火车站。日军的狂轰滥炸把繁华的火车站炸成了一片废墟。房屋倒塌了，铁轨扭曲了，天桥裂开了……日军一看，火车站已成废墟，便扬长而去。

   突然，一个微小的声音传入了我的耳朵。那哭声是多么的无助，多么的伤心啊！“爸爸妈妈，你们在哪里呀？”但没人回答，之后便是一阵撕心裂肺的哭声。我一看，原来是一个孩子在铁路上坐着，大概只有二三岁。可能在之前，他还在爸爸妈妈的怀抱里。而现在，他没有了父母，也没有了亲人的照顾，更没有了今后的生活。

   日本人，你们也有自己的父母，你们怎么能杀这些手无寸铁的百姓呢？

   我又想到我们当前，现在我们生活在和平的环境里。所以我们更要珍惜现在的幸福生活，为战争敲响丧钟，在和平的环境中幸福生活吧！

   同学们：我们要自觉行动起来，珍惜学习的机会，树立远大的理想，刻苦学习，超越自我。让自己成为一个珍惜时间、热爱学习的人，成为一个积极向上、心灵纯洁、全面发展的人。古人云：“一屋不扫，何以扫天下。”所以，我们要从身边的小事做起，从生活、学习中的点点滴滴做起。只有一件件小事做好，将来才能做好大事，把我们的祖国建设的更加强大，更加美丽，更加繁荣昌盛吧！[fn:14]

** 语文期中考试的反思

   这次语文期中考试我考了 93 分。

   如果我认真复习的话，大概可以考 95 分。所以我们要复习旧知识，才能考好。

   这次没考到 95 分，就是因为作文扣了 3 分，所以才没考到 95 分。

   我们要认真复习，并整理分析。也要归纳整理，经常做一做题目，这样才能巩固知识，考出好成绩。

   同时，也要取长补短，学习别人的长处。这样才能获得一些好的行为习惯。我们也不要气馁，一次没有考好，并不重要。只要懂得知识，一定能考好。

   在考试前要认真复习，不要临时抱佛脚。在考试中，我们一定要独立思考，不能抄别人答案，也不能乱做。在考试后，也不能跟没做完试卷的同学说话，交流答案。做完考试卷后，也不能忙于交卷，要先认真地检查几遍，看看有没有题目没做对，之后，才能交卷。

   虽然我这次期中考试语文没考到 95 分，但我相信如果我按照上面的去做，以后一定能考高分。

** 生命是什么

   我家的仙人掌 ，真是惹人喜爱，但它非常矮。它怎么会这么矮呢？

   这是因为我们家原先有一株老仙人掌，但在前不久，由于仙人掌的主根腐烂了，变成黄的了，而上面也已萎缩了，变成了一个漏的大口。所以我们想把它扔掉。但是我说不要扔，因为我常常想：生命是什么?

   一次，我养蚕宝宝。一次忘找到桑叶，让它饿了三天。一个小时，蚕宝宝没变。过了一天，蚕宝宝没变。过了两天，蚕宝宝没变。过了三天，蚕宝宝死了。虽然蚕宝宝死了。但它是在没有食物的情况下，坚持了两天才死的。虽然它只坚持了两天。但这两天，它是用生命去做搏斗，由此可见生命是非常坚强的。

   又一次，我偶然发现中校区水管旁有一株植物。它竟然能在水管旁生长，真是个奇迹。所以生命是个奇迹。

   又一次，我在奶奶家的鱼缸里捉鱼玩。我抓住了一只红色的鱼。只要我的网斗把它盖住，再过几分钟，鱼就露出水面了。但是突然我发现鱼不见了，又发现了网斗上破了一个洞。鱼大概是从洞里出来。所以生命是勇气。

   一次偶然的机会，我们学了“杏林子的生命生命”，让我了解了杏林子患了关节风湿病，导致肩不能抬，手不能举。但她仍坚持写作，成为台湾著名作家。所以生命是毅力。

   虽然生命是有限的，但可以做出无限的价值。所以我们要让生命活出无限的精彩。

   现在我终于明白了，生命是坚持，用生命去搏斗，生命也是奇迹，更是勇气，也是毅力。所以我们要用生命做出更多的贡献。

** 生命的毅力

   最近，我家养了一盆仙人掌。它傲然挺立，白白的刺长在身在网上看过仙人掌的知识，仙人掌丢了一个根，是没什么的。一开始，我也不相信网上的话，但我还是想试一试，相信仙人掌一定能救活的。之后，我们把腐烂的根剪掉，再把一个主根旁边的根给扎到主根那里。过了五天，我看见了那根代替主根的根也腐烂了，我连忙把根换成另外的根，但是都腐烂了。我觉得这块泥土可能出了些问题，这仙人掌可能活不了，但我仍不死心。所以我们就换了一个盆，剪了一株仙人掌的根放在盆里，越长越高，渐渐高过盆了。我想这有希望，一个月后，仙人掌就变得生机勃勃了。真没想到仙人掌竟然有如此强的生命力啊！

   而且仙人掌几年不浇水都不会死，由于它的生命力适应过沙漠的温度，所以才有这个本事。仙人掌很顽强，就是在沙漠里也不会死。

   仙人掌顽强的生命力令我敬佩。剪一株根养在盆里，竟然能变成一株大仙人掌，几年不浇水竟然还能活，在沙漠里几年也不会死。我们要学习这种精神。仙人掌为什么有这么顽强的生命力呢？因为仙人掌顽强地在恶劣的环境中生长，就是靠勇气，才没有倒在沙漠里。这是因为仙人掌在恶劣环境中，不屈向上，茁壮成长，这就是仙人掌顽强的生命力。我们也要有毅力，不放弃，勇于面对困境！

** 河里嬉戏图

   家乡有一条河，到了夏天，家乡有很多人在河里嬉戏、打水仗、游泳。家乡的伙伴们就穿梭其中。看那条河两边散落着许多石子，也有一些人在两旁投石头，我也忍不住玩了起来，好好玩，我也玩成了一流高手。之后，我们就比赛谁的石头扔得远。我玩了第一名。打水仗是要分成个人赛和团体赛，个人赛是个人用水去浇对方，让对方淋湿，你就赢了，而团体赛是分层两队，用水浇对方，看谁浇得多，谁就赢。我玩了一局，个人赛和团体赛都赢了。

   家乡的河就是那样的有趣，希望你们也来我的家乡玩。

** 科技馆一日游

   上个星期天，我去镜湖的绍兴科技馆玩。

   我们先进了三楼的科技与生活展厅。一进门，我就看见有人在玩“模拟火车”，我也忍不住去玩了一下。“模拟火车”是有 3 分钟的时间，让我们在 3 分钟到达终点，而到达终点的路程有 50 公里，而且不断地有危险出现，比如天气变冷、车道修补等。但我克服了种种困难，还得了 100 分。然后，我又玩了“水游绍兴”。“水游绍兴”是乘了一只模拟的船，游览绍兴，欣赏水乡的风景。我们在模拟的小船里驶过了光相桥、太平桥、吕府、鲁迅故里等绍兴有名的景点。

   在科技与生活展厅，我最喜欢玩的莫过于地震体验了，那里的工作人员先让我们地震的时候把门打开，放一把椅子出去，顶住门背，然后再关掉带有红蓝黄三种颜色的指示灯，接着再躲在桌子底下，这样就能保护自己，减少伤害。

   我还玩了踢足球、火场体验等。踢足球是把足球放进洞中踢出去。火场体验就是让我们进入火场，告诉我们哪些在火场中可以用，哪些不能用。我还看了旁边的身体器官的介绍等等。

   我还在二楼的探索与发现展厅看了电磁大舞台，一根铁针释放出无数的电花。我还进了法拉第笼体验了一下：我被关在一个笼子里，笼子里有小口，而外面有紫色的闪电在笼子周围盘旋，使我胆战心惊，这样在笼子里大概过了两三分钟，我就被放出来了。

   接着，我观看了魔力科学秀的表演，看了球幕电影。球幕电影是要躺着看的，非常舒适，屏幕非常大，一个屏幕上有好几个不同的放映，一次就能播出两至三幅画面。

   这次游玩科技馆，真是很有收获哦！

** 农村小景

   今年寒假，我和妈妈、外婆去柯桥区的马鞍镇的舅公家做客。

   我们乘着公交车来到马鞍镇寺桥村，进了村后，我发现走一会儿，就会碰到狗。而且这些狗大多是白色的。等快到了舅公家，我数了一下刚才狗的数量，有八只狗。我问妈妈农村里为什么有这么多狗。妈妈以前在农村度过一段时间，我想她应该知道。妈妈说：“这些狗是看家的。”这些看家的狗好像一个个士兵。我想有这么多狗看家，他们的家一定很安全。

   我和妈妈又到旁边的菜地上去看了一下，许许多多的菜都在那儿种着。我问妈妈这些是什么菜。妈妈说：“我也不知道。”在一旁的外婆说：“这个是芥菜，那个是油菜，这个是大蒜叶。”我想这里怎么会有这么多菜，真是一个“土中市场”啊！原来我们吃的菜都是农村人种出来的。这些种在土里的菜，我以前都没看见过。

   我们又走到了旁边的房子和桥那边，发现那边的房子和桥都很旧。我问妈妈为什么农村里都这么旧。妈妈说：“这是农村的特点。”而又一些房子则是楼房，这些楼房还挺好的，不亚于我们城市里的别墅。我想农村也变得这么好了。

   寺桥村有一条小河，更是引人注目，那清澈的河面泛起层层微波，再加上两旁具有特色的屋子，真是一幅美丽的画卷啊！

   这就是农村，无论什么时候，无论什么季节，农村都有一幅美丽的图画。

** 读日本版的《三国演义》有感

   前段时间，我看了一本由日本人写的《三国演义》，作者是吉川英治，非常好看，我觉得比以前的《三国演义》，简单，好笑。

   吉川英治是日本大众文学泰斗、历史小说大师。曾荣获“国民作家”的头衔，晚年荣获日本文化勋章。吉川英治的书有现代和古代的风味。

   我以前也读过中国版的《三国演义》，现在我觉得这本《三国演义》非常的好看，读起来轻松，虽然都是耳熟能详的故事，但是有些话语则非常有趣。许许多多的事都在这本书中出现，每次都引得我哈哈大笑。在吉川英治的书里，情节更加充实，人物变得更加有血有肉。很多人物都像游戏中的人物那样，个个有着特长和不足。有些情景也改变了，这个把故事延长了，许多剧情都拖长了。

   我们要有三国中曹操的勇气、关羽的人格、孔明的智慧、孙权的年富力强、张飞的蛮力，就能成功!

** 让我敬佩的爸爸

   在身边，有很多让我们敬佩的人，我最佩服的人是我的爸爸。

   爸爸爱看书，书看得很入迷，常常看到 11 点或 12 点，有时就是早上起来，也要看一会儿书。爸爸最近买了一只 Kindle 的阅读器，整天捧在手上看。

   你肯定不会相信我说的话，那我就给你讲他的一件事，让你相信吧！

   爸爸有一次想看书，但是我也想看书。妈妈说：“让孩子先看，看完给爸爸看。”爸爸同意了。我看了大概十分钟，就给爸爸看了。爸爸大概五十分钟才肯罢休。而晚上我在刷牙的时候，发现爸爸不见了。我在阳台、大房间、小房间里找爸爸，就是没有找到爸爸的踪影。又在客厅、浴室间、厕所间里也没有找到爸爸的踪影。最后，我去敲了一下书房间的门，发现爸爸在书房间里一个人静静地看书呢！你看我的爸爸看书专不专注啊！

   这就是我的爸爸，一个让我敬佩的人。

** 虫虫乐园半日游

   今天，我去镜湖避风塘农庄的虫虫乐园玩。

   一进门口，两旁就是风车，非常漂亮。我们来早了，要等到九点，才能玩。

   到了九点钟，那里的工作人员跟我们玩破冰游戏。破冰游戏是指自我介绍、互动游戏等。我们先做了自我介绍，之后玩“萝卜丝皮”。“萝卜丝皮”是指两人面对面，说“萝卜”时拳头相撞，说“丝”时手掌相合，说“皮”是指手背朝上翻。

   之后，我们就去玩了虫虫捕鱼。虫虫捕鱼时指分成三队，在有限的时间里捕到的鱼最多的那队就获胜。然后我们又玩了“打土狗”。“打土狗”是指一个人敲，其余人躲，还要按桌子上的按键，可加分数。在有限的时间里获得最高的分数，那队就赢。但如果一个人分数太高，就要被敲头三下。我们还去玩了“一起除害虫”。“一起除害虫”是指每队十颗子弹，打“害虫”，比分值谁高，高的那队就获胜。我们还玩了“虫虫粘粘乐”。“虫虫粘粘乐”是指套上粘粘的衣服，粘在具有粘性的墙壁上。最后，我们玩了“蛛网捕食”。“蛛网捕食”是指两或三队调一个人上蛛网，抢到铃铛，铃铛一响，就算那队获胜。

   之后，我们又去昆虫展馆，看到了竹节虫、金龟、螳螂等。我觉得最有意思的是松鼠了。松鼠被关在一个筒里，从筒口往里望，会发现一个毛茸茸的东西，一双黑眼珠盯着我们，非常得可爱。

   我们还做了一个标本，这个标本是独角仙。工作人员教我们怎么做，先把独角仙的水给挤干，之后再把腿给伸开，并依次用两根大头针八字交叉地固定住头和脚。这样一个标本就完成了。

   最后我们又玩了“奔跑吧，毛毛虫”。这个是指骑上充气的“毛毛虫”，跳着到达终点，哪队先到终点，哪队获胜。

   我们还在旁边拍照纪念，今天一天真是收获满满，受益匪浅啊！

** 全民开放日，一起玩转消防

   在前不久，我和妈妈去越城区公安消防支队参观。

   那天，天气晴朗，我一进消防支队，就看了一个宽大的操场，消防员叔叔就在这里健身。消防员叔叔就给我们拿来了一件器具。消防员们讲这个就是水泵，是用来喷水的，还有两条水带，就啪一下，消防员们把水泵打开，水顿时射了出来。我们也试了一下，我玩了一会儿，知道了如果往右转，水就变大，往左转，水就变小了。

   之后，我们就去参观器材库。器材库里有救生类器材和基本防护类器材等等。一边听介绍，一边参观。消防员叔叔首先介绍了消防服，这个衣服非常重，而且可以防火。我也穿上消防服体验了一下，感觉路也走不动了。之后，我们又看了消防车，消防员叔叔讲，每辆车价值都在上百万元呢。我们还坐了一会消防车。我们还看了消防员叔叔讲剪切钳。如果火场的钢筋挡住去路，可以用剪切钳剪断。

   之后，我们又去参观了消防员的宿舍。消防员被子折得很整齐，消防员叔叔们折的是豆腐被子，折的很整齐。我们也试着学习了一下。我们又在消防车上看了高压水枪，高压水枪是在消防上面，五米的水柱冲向远方，气势宏大。

   我们还在旁边拍照留念，这次让我知道了消防知识，和一些器材，真是意义非凡，受益匪浅啊！

   #+LATEX: \vspace*{\baselineskip}

   *玩转消防之铁血丹心(消防征文投稿)*

   前不久，妈妈作为志愿者，带我一起去参加“全民开放日，一起玩转消防”的活动。

   那天，天气晴朗，阳光明媚，我们早早地来到越城区消防支队，一进大门，就看了一个宽大的操场，消防员叔叔平常就在这里训练。消防员叔叔们穿着整洁的军装，英姿飒爽，他们热情地迎接了我们。其中一位负责人先给我们讲了注意事项，接着就介绍各种消防知识，带我们参观消防支队。首先他拿来了一件器具，他介绍说这是消防水带，是用来喷水的，还有两条水带，就啪一下，消防员们把出水口打开，水顿时射了出来。我也试了一下，知道了如果往右转，水就变大，往左转，水就变小了。

   之后，我们就去参观器材库。器材库里有很多东西，比如救生类器材、基本防护类器材、新兵训练器材等等。我跟随着消防员叔叔，一边听介绍，一边参观。消防员叔叔首先介绍了消防服，这个衣服非常重，而且可以防火。我也穿上消防服体验了一下，感觉重得路也走不动了。之后，我们还来到消防车旁边，听消防员叔叔介绍消防车里的各种设备和功能，他还说，每辆车价值都在上百万元呢。我还坐上了消防车的驾驶室。坐在高高的消防车上，感觉自己就是一名消防员了。接着，我们还看了消防员叔叔讲剪切钳。如果火场的钢筋挡住去路，可以用剪切钳剪断。还学习了怎么使用灭火器、吹风器等等。

   接着，我们又去参观了消防员们学习的地方、食堂、宿舍等，给我印象最深的是他们的宿舍，里面一尘不染，特别是被子折得很整齐。消防员叔叔还给我们示范了如何折叠这种豆腐被子。我们也试着学习了一下。我们又在消防车上看了高压水枪，高压水枪是在消防车上面，用来扑灭高层的火灾，五米多的水柱冲向远方，气势宏大。

   最后，我们一起拍照留念，这次警营体验活动让我认识了一些消防器材，学习了很多消防知识，受益匪浅！特别是有机会和消防员战士们近距离接触，他们比我大不了多少，却肩负着不怕牺牲的誓言，守卫着一方百姓的平安，铮铮铁骨的消防员战士们值得我们学习和致敬！

** 畅游米王国

   昨天，我吃饭时，有一些饭没有吃，我就睡觉了。

   突然，门里进来了几个白衣服，白身体，白嘴巴，白耳朵，全身都是白的，把我带到了一个宫殿，这座宫殿也是白色的，高大耸立，不一会儿，带我去宫殿的人把我带进了宫殿，我一看宫殿两旁尽是人，而且也都是白身体。中间坐着个老爷爷，也和下面的人一样。老爷爷说：“小朋友，让你参观一下我们的宫殿吧。”我说：“这是哪里？”老爷爷说：“这是米王国。”老爷爷又说：“为什么你没吃完饭。”我说：“我不想吃！”老爷爷说：“难道你没学过《悯农》这首诗吗？你难道就不懂得米的重要性？让我来给你介绍一下米。”我说：“学过，给我介绍一下米吧！”老爷爷接着说：“米的过程的第一步是把稻谷割下来，把它放在机器里，将米弄出来，把米和麦子分开，用机器把米给包装好，然后让工人把米运到超市，然后一袋袋的买走。还有一些机器，比如收割机、包米机等。小朋友，知道米来之不易了吗？所以我要把你抓进牢间。”我惊出了一声冷汗。

   我一摸，原来我还在我自己的床上。原来是一场梦。但我们还是要珍惜粮食，不能浪费粮食。

** 游东方山水乐园

   七月五日，妈妈带我去绍兴的迪士尼——东方山水乐园玩。路上，我和妈妈一起乘公交车到了东方山水乐园的门口。

   从门外往里走，里面人山人海。我们好不容易才买到了门票。我们一进去，就看到了一个屏幕，在灯光照射下，九条龙呈现出金色的光芒，非常耀眼。

   之后，我们通往“山之王国”，去看珍宝馆。

   一进珍宝馆，我们看见一只用黄金樟做的狮子，顿时惊呆了。这狮子的形态栩栩如生，还获得世界吉尼斯纪录。再往里走，不光有各种颜色的雕像，还有许多工艺品、各个朝代的镜子、百家姓镜等。还有些雕塑，比如猛犸象牙雕刻珍品。在珍宝馆中，我们品味到了璀璨的中国艺术瑰宝。

   之后，我们又去了地下晶窟。去地下晶窟必须先穿过“南非草原”。“南非草原”里有许多猿人和动物。之后，我们便来到了地下晶窟，一看到处都是千奇百怪的石头、石钟乳、石笋、石花、石片等，星罗棋布。再一看墙壁上还有许多紫晶、水晶。我还听说这是全球最大的室内人工溶洞。

   我们还去了国防科技教育馆，看到了海陆空三军的装备，还看到了碉堡等。

   我们还玩了“天马行空”、“射击总动员”等项目。我非常开心。

   这次游玩东方山水乐园，既开阔了眼界，又开心了自己，真是一举两得啊！

** 参观精灵实验室

   这个星期天，爸爸和姑姑带着我和表弟去贺家池参加精灵实验室的活动。

   我们进了精灵实验室，看到了一个阿姨在一个个瓶子里放了色素，有红的、黄的，还有蓝的、绿的。

   之后，精灵叔叔给我们变一个魔术，叫做“鼻子也能喝水”，让我们认识了吸水粉，一个吸水非常快的东西。

   精灵叔叔还在那些瓶子放入干冰，那些水立刻就沸腾了，一股白雾就从瓶里冒了出来。精灵叔叔讲干冰是固态的二氧化碳，温度是零下七八十度。精灵叔叔还给我们看了在瓶子里放一点洗洁精和干冰，水里便开了锅，白雾便源源不断的流出来。我摸了一下，很凉。精灵叔叔还在瓶子里放了很多干冰和洗手液，不一会儿，就流出了很多泡泡。这些泡泡跟洗澡时的泡泡一样。这就是泡泡雪花澡。

   最有趣的莫过于是“火焰掌”。火焰掌就是放一点泡沫在手上，然后把打火机上的火放在手上，持续一会儿就好了。起初我不敢，后来看见很多人去了，我也去了，效果还不错的。之后，便是柠檬挤几滴就可以让气球爆炸，因为柠檬油酸性，所以气球就会爆炸。我们还看了大象牙膏。这个牙膏比我们人还壮呢！

   这次去精灵实验室，既懂了科学知识和道理，还玩了一些活动，真是收获满满啊！

** 我的爷爷

   我的爷爷已经七十五岁了，瘦瘦的，戴着一副眼镜。

   爷爷喜欢看书写诗。他每周六都要去老年大学，那边还请了老师，教他们写诗。除了爷爷，那里还有很多人星期六也去。而且爷爷每天坚持看书、写诗。写的有几首还在报纸上登过呢！不仅如此，爷爷还在抄诗，这个学期就抄了十几本。爷爷还每个月都去图书馆借书。

   有一次，我去奶奶家，发现爷爷在聚精会神地看书。我叫他，他都不理我。你看他看书认不认真？

   有一次，我和爸爸去接爷爷回来。到了门口，没发现爷爷，问保安，保安说：“你爷爷在教室里面。”因为爸爸是开车来的，不方便进去，所以就让我进去。我一进去，看见他们教室与我们的教室一样，而且还比我们的整洁。我发现爷爷正在认真地看书。我们便把他接走了。

   奶奶经常说：“爷爷读书比你们还认真呢！”这句话引起了我的思考……

   你说我的爷爷学习认不认真？我们应该要学他，认真学习呢！

** 我的外公

   我的外公已经八十岁了，胖胖的，酷爱画画，对艺术很着迷。最近几年，尽管年事已高，身体不好，但他依然坚持创作。他细心寻找伟人、著名科学家、鲁迅的资料。在今年 7 月 20 到 8 月 8 日在鲁迅纪念馆展出“心中的旗帜——鲁迅系列中国画专题展”，8 月 13 到 8 月 25 日在美术馆展出了“科技之光——当代著名科学家肖像画展”。

   这两次画展，外公呕心沥血。鲁迅专题展有 53 幅作品，具体有鲁迅与李大钊、鲁迅和青年木刻家、毛泽东与鲁迅、鲁迅与蔡元培等作品。科学家肖像的作品画得是栩栩如生，让我心生佩服，让人们啧啧赞叹。而外公为了这两次画展，付出了很多心血。听外婆讲，外公有时要凌晨一两点钟睡觉，早上五点钟就开始画画，除了吃饭睡觉，几乎都在画画。

   以前，我去外公家时，外公的画桌上就放着很多画卷，现在变得更多了。外公坚持画画，执着的精神感染了我。我也要学习这种精神。

   宝刀未老，艺术长青。我要学习外公对艺术的执迷和专注。

** 黄酒小镇故事多

   越酒行天下，小镇故事多。7 月 30 日，东浦黄酒小镇迎来了独具特色的“开耕节”。我和妈妈乘着大巴车，来到东浦，和其他小朋友及家长一起参加绍兴晚报组织的小记者亲子家庭体验活动。

   在开耕节现场，天气炎热，但东浦百姓热情似火。仪式上，身穿古装的酒娘子提着鉴湖水，手捧糯稻秧，和糯稻种植农户祭拜神农氏、马臻与酒仙菩萨。接着，酒娘子还为 40 位穿着传统耕种服装的农民伯伯倒酒，他们喝下黄酒，拿着一捧捧秧苗，下田插秧。这是我第一次看到稻田，看到秧苗，感到很新奇，但真的让我们自己体验插秧时，我犹豫了。在老师的鼓励下，我最后鼓足勇气下田了，在农民伯伯的指导下，用大拇指和食指拿着秧苗，用力插进田里。虽然只插了 8 株，我就满头大汗，真正体会到农民伯伯耕种的辛苦和粮食的来之不易。

   之后，我们便去参观黄酒小镇展示厅，二楼摆放着小镇规划的大型沙盘，播放着介绍黄酒小镇的视频。通过视频和领队姐姐的介绍，我了解了不少东浦的历史、风情和发展。在旁边的展示馆里，摆放在由 80 岁的东浦沈厚夫爷爷长长的画卷《东浦风情图》。进入内厅，中间摆放着一艘乌蓬船，在灯光照射下，水乡的美丽风情尽显无遗。旁边有许多图片资料和老照片，还有一些酿酒的器具，展示东浦酒乡、桥乡、名士之乡的风貌。展厅布置也很有特色，感觉就是古镇的缩影。

   走出展厅，来到古镇，踏着石板路，沿着悠长的小巷，在古桥边，小河旁，我们品尝了黄酒，吃了有着淡淡酒香的黄酒棒冰，最后参与答题，还领到了一瓶黄酒做纪念呢!

   这次参加开耕节、参观黄酒小镇是很有意义的活动，我受益匪浅。欢迎大家有空来这里，品品黄酒、吃吃棒冰、坐坐小船、赏赏美景，听听小镇故事、看看黄酒发展。[fn:15]

** 《忍者神龟 2》观后感

   在暑假里，我看了一部电影叫《忍者神龟 2 破影而出》。

   你们一定会觉得很奇怪。《忍者神龟 2》是一部讲乌龟的电影吧！是的，《忍者神龟 2》是讲四只乌龟、女记者奥尼尔和一名司机共同抵抗大脚帮，与施莱德战斗，最终获得胜利的故事。

   在《忍者神龟 2》中，四只乌龟的老师叫斯普林特，是一只老鼠。四只乌龟的首领是麦奇，麦奇戴着紫头巾。戴着黄头巾的是李奥，它的武器是双刀。戴着红头巾的是拉斐，它的武器是匕首。戴着蓝头巾的是多纳，它的武器是棍子。

   而反派角色是施莱德，它的身体是钢铁做成的，身上有飞刀，非常残暴。它还有一个徒弟叫赛克斯。最后是四只神龟一起打败了施莱德。

   是啊，《忍者神龟 2》里的四只神龟非常团结、有趣。我们也要学习它们。

   这部电影非常好看，希望你有机会也能来看。

** 畅想未来家庭生活

   双休日，我去绍兴市科技馆参观。在三楼的科技与生活展厅，我参观了数字生活馆。里面的工作人员给我们介绍了能自动冲洗的马桶、手碰一下能亮的指示灯、能直接购物的冰箱，甚至刷牙的玻璃还能看资料，我觉得很新奇。

   回到家中，晚上睡觉。突然我前面出现了一个小精灵，“这是 2026 年，这是我们新造的房子，欢迎你来参观。”我走了一会儿，就看到一幢房子。这座房子外表普通，但内部非常好。在门口，小精灵介绍要有主人的指纹才可以进去。小精灵带着我进去，一楼有一个客厅，客厅的台面有一个电脑页面，可以查阅资料、看电视，用途广泛。再往里走，就是一台电视，这个电视可以有限无限地调整，随意搜索。之后，小精灵带我上二楼，二楼上有一个冰箱。冰箱上有各种食物什么时候买的记录，还能订购食物。用手机、支付宝远程支付。二楼还有一个厨房，厨房里灶台旁有一个电子屏幕，它只要一搜索，你想做的菜的方法就出现在屏幕上，你只要一步步地学着做就可以做出美味的佳肴。小精灵还告诉我房子的温度是自动调节的，外面冷，它就热，外面热，它就冷。而且这幢房子白天用太阳吸收能量，晚上用太阳储存的电照明。就是阴天雨天也没事，因为太阳照一小时，就可以照十个小时的灯。它们晾洗衣服只用一台机器，按晾或洗，机器就会操作。

   小精灵又带我去了三楼，三楼有一间卧室、浴室、洗手间。小精灵讲卧室躺上去很舒服。而且还可以保健按摩。洗手间一年四季都是温水。而且这个水如果调整另一种状态，还可以当白开水用呢！而浴室也一样，洗的都是温水。旁边还有一个电脑，这个电脑网速快，而且用太阳能，不耗电。

   突然，妈妈的声音在耳边响起“起床了！”我这才知道这是一场梦。虽然这是一场梦，但在 2026 年，这座房子一定会有的。

   #+LATEX: \newpage

* 五年级——雏鹰展翅

** 我喜欢的书

   我非常喜欢看书，我的看书生活恰似一首清丽明快的小诗，也似一支轻快活泼的歌谣。

   小时候，我爱看《三国演义》、《西游记》等，到了一二年级，后来我开始看文学类和科普类的书。之后，我还看了《宝葫芦的秘密》、《皮皮鲁传》等。现在，我发现了一套很吸引人的书，它的名字叫《装在口袋里的爸爸》，是科幻类的书，作者是杨鹏。这系列书每一本主要讲述的是小学生杨歌的爸爸发明了一件东西，然后引出一系列有趣的故事。这些书妙趣横生，耐人寻味。

   我在图书馆借的都是这类书，一次，我发现人文图书城，也能借书，而且能借到图书馆没有的书，我借到了几本杨鹏的书，欣喜若狂。《装在口袋里的爸爸》系列书中有一本书是《我变成了巨人》。这本书非常有趣，讲的是杨歌喝了变大药水，变成了巨人，引发了一系列不可思议的事。

   妈妈以前反对我看，我就偷偷地看书，或者听电脑上的 mp3。有一次晚上，我把书放在床头柜旁边，早上 5 点多起来，悄悄地躲在房间里看。等到六点多，妈妈起来了，我就把书藏起来，装作睡着了。等妈妈一走，再看。如此一来，这本书到七点左右，就看完了。这样既没有让妈妈发现，还增长了知识，真是太满足了，太快乐了。这本书里面的情节让我如醉如痴，也引得我浮想联翩。

   书整整陪伴了我六年，它赠送我很多知识和快乐。阅读能带给我们快乐，就让我们一起阅读吧！

** 横店之旅

   暑假里，妈妈带我去金华横店旅游。那天，我兴奋不已，横店我早就想去了。我怀着兴奋激动的心情去横店游玩。上了大巴车，时间飞逝，9 点多，我们就到了横店的秦王宫。

   我们在秦王宫门口拍了照，并往王宫的广场里走，发现两旁有梅花，近处一看，原来是假的。听说《琅玡榜》就在这儿拍的。我们又到了四海归一点，有一座小桥，桥旁有四只神兽，说是青龙、白虎、玄武、朱雀。之后，我们去地上皇城，先看了表演《英雄比剑》，我第一次看到影片是这样拍的。

   下午，我们又去了“清明上河图”景区，它是一个仿照“清明上河图”的景点，我们先去看了水车和瀑布，之后走了财运桥，我还坐上缆车，在空中飞过去，很刺激的。还看了“笑破天门阵”，就是仿照杨家阵的剧情改编的情景剧。

   后来，我们还去乐大智禅寺，拜了一下佛。晚上，我们还去了梦幻谷，玩了陆地上的小火车，水里的滑梯和沙子等，还看了全国最大的灾难实景演出“暴雨山洪”。

   这次旅行真是不虚此行，意义非凡，受益匪浅啊！

** “二十年”后回故乡

   一年一度的中秋节到了，每当想起王维的“独在异乡为异客，每逢佳节倍思亲”，我不禁想起了自己的家乡——绍兴。

   我开着小汽车，行驶在宽阔的柏油马路上，转眼间到了小区。一进小区，我就愣住了，这就是我魂牵梦绕的家乡吗？到处都是别墅。小区原来一层的房子变成了三四层，没有矮矮的平房和普通的公寓，只有红白相间的别墅。这时一声亲热的声音传来：“儿子！”。我转过头来，原来是爸爸在叫我。我说：“爸爸，小区怎么大变样了？”爸爸说：“因为科学家发明了很多东西，科技已经变得很发达了。你还是先回家吧！”我说：“好啊！我想看看家里怎么样了。”

   我们便向家里走过去，一路上，我看见拥有五颜六色花的花坛，散发着淡淡的沁人心脾的清香。蜜蜂们贪婪地在花丛中吸着蜜，原本旧旧的小区，现在变得一尘不染，一个智能的“吃垃圾”的机器人，专门负责吃垃圾。爸爸说：“这是新上市的机器人。”不知不觉中，我们到了家，看到家的门上有一排按钮。爸爸又说：“这是安保的密码锁”。

   爸爸开了门，我进了家，发现家里一尘不染，非常整洁，还有一个扫地的机器人，它正在扫地。不一会儿，亲朋好友陆续来了，我们一家人，坐在椅子上聊了起来。大家说着，笑着，欢乐的笑声充满了整个家。

   时光飞逝，不一会儿，就到了离别的时间。我依依不舍地离开了我的家乡——绍兴。我相信家乡二十年后一定会变得更好的。

** 击剑

   上个星期日，妈妈带我参加了绍兴晚报小记者组织的活动，即参加击剑仪式和击剑体验。

   我怀着兴奋的心情来到了绍兴奥体中心击剑馆。一进去，到处都是人。我们找了一个教练学击剑。教练先拿出三种剑，给我介绍，拿起其中的一把红色手柄的剑，说这是三把剑中最轻的一把剑，叫“花剑”，也称“公主剑”，有效部位是前胸和后背，攻击方法是刺。教练又拿起一把白色手柄带手环的剑，说这是三把剑中第二轻的剑，叫“佩剑”，也称“骑士剑”，有效部位是上半身，攻击方法是砍和刺。教练又拿起其中一把灰色手柄的剑，是三把剑中最重的一把剑，叫重剑，攻击的有效部位是全身，攻击的方法是刺。

   之后，我和另一个小朋友击剑，三比二，我赢了。

   这次去击剑馆，既体验了击剑文化，又赢了比赛，真是一举两得啊！

** 狗的自述

   大家好！我是大家喜欢的狗，我们是属于犬科的动物，属哺乳刚，食肉目，我们爱啃肉和骨头。我们智力发达，反应灵敏；我们很聪明，可以做算术，被科学家认为是地球上最聪明的动物之一。而且，我们喜爱勇敢地保护主人。我们的嗅觉器官和神经非常发达，嗅觉能力超过人的 1200 倍，听觉也很灵敏，是人类的 16 倍。但我们的视觉和味觉较差，我们的眼睛属于色盲，辨色能力差，远程能力弱。我们属于红绿色盲，只有这两色看不清楚。我们为每年春秋单性发情动物，每胎产仔 2-8 只，寿命 10-20 年。狗的正常体温是 38.5 度-39.5 度。狗还会用肢体表达心情，摇尾巴代表高兴，头垂下代表哀伤。

   好了，我要走了，妈妈叫我睡觉了，再见！

** 吃大闸蟹

   昨天，爸爸网上购买了几只阳澄湖大闸蟹，快递员叔叔送来了六只螃蟹，用一个白色的塑料箱子装着，里面用绳子绑着螃蟹，并在里面冻住了它们。我们把绳子解开，螃蟹就开始活蹦乱跳，有了很足的精神。不一会儿，螃蟹就想爬出塑料箱。我们把箱子盖上，它们才爬不出来。我观察它们一会儿，发现它们和别的螃蟹有点不一样，它们身上没有黑的毛，而且很有精神。

   我上网查了一下资料，阳澄湖大闸蟹的生产地是苏州，李白曾经写过关于这个螃蟹的诗歌。阳澄湖大闸蟹又名金爪蟹，它青壳白肚，金爪黄毛，是中国的名牌产品。关于阳澄湖大闸蟹还有几个故事呢！我们买了 3 只雄螃蟹，3 只雌螃蟹。我们吃着大闸蟹，觉得味道鲜美，非常好吃。里面的肉白嫩鲜美，蟹黄红红的。

   这次吃螃蟹，既吃出了味道，又了解了不少知识。

** 我的电动牙刷

   我家买了一支电动牙刷，这支牙刷是爸爸给我买的，是电动的，它的下面鼓鼓的，里面装着一节电池。它上窄下宽，下边鼓起来，就是这里装着电池。它是旋转形的，要旋转开关，才能刷。它的上面写着“开关”两个字。往开的那边一转，就开了，往关的那边一扭，就关了。

   电动牙刷属于清洁牙齿的工具，它由干电池、微型直流电机、电池盒、牙刷头、金属护板及套筒组成。与手动牙刷相比，电动牙刷在电池的作用下，刷头以每分钟几千次乃至上万次的运动，效率高于手动牙刷。电动牙刷分为两种，一种是振动形牙刷，就是刷毛在刷，牙刷不动。还有一种是超声波仪器，也就是超声波牙刷，价格昂贵。

   电动牙刷还有特别的四大优点，一是清洁能力，手动牙刷刷得慢，清洁能力差，不能完全清洁口腔内的脏物。实验证明，电动牙刷清除口腔脏物比手动牙刷的能力要强得多。而且电动牙刷得速度快，省了手动牙刷的时间。二是可以让不爱刷牙的小朋友爱上刷牙，因为一个东西在口腔内动来东去，非常有趣。三是可以让不会刷牙的人刷好牙，因为是电动的，比手动刷得好一点。手刷刷得重，会痛。如果刷牙不当，会对牙齿造成损害。而电动牙刷可以避免这一点。当然，如果买的电动牙刷质量差，也会损伤牙齿的。四是价格也不贵。

   我非常喜欢我的电动牙刷。

** 徒步雪窦岭

   妈妈听说绍兴稽东镇有一处非常美的地方，被人称为绍兴的小九寨沟，趁着国庆节放假，我们一家一起去了那里看个究竟。

   往山上走，就看到一大块石头，极像一头狮子。据说，以前这狮子曾横行跋扈，四处为非作歹。龙王降伏了它。这只狮子就每日卧于古道边，守护这里的百姓。这就是“石狮平安”的景点。再往上走，又一块很大的石头，上面有“龙门石”三个大字。我们一路往上走，看见有不少当地的农民在卖菜。再往上走，就有一块青灰色的石头，被称为“毒蛇喷雾”。再往前走，发现有一个灰色石头砌成的小房子。

   再往上走，山上有一处地方，瀑布飞泻而下，非常壮观，在绍兴很少见到这样的瀑布。正如李白说的“飞流直下三千尺，疑是银河落九天”。再往前走，就是水库。水库再往前走，就是一片蔚蓝的湖水，水里长着大片的水杉，非常漂亮，如同仙境一样。

   这就是雪窦岭，非常美的古道，希望你能去看一看！

** 竹子

   世界上，有很多值得我们赞扬地人和东西。今天就让我来给大家介绍一下竹子吧！

   竹子曾被古人赞美赞扬，而且还有松、梅一起成为“岁寒三友”，还被称为“四君子”。

   竹子坚忍不拔，一截一截地，而且不畏寒冷，顶得住严寒。古人都赞它非常清高，它往上生长，从不生长相反地地方，而且它非常坚硬。

   竹子除了外型好，内在也非常好。竹子可以做成竹沥，可以治痰，还可以当茶饮。还可以做成竹茹，可以治心烦失眠、惊悸不宁、胃热呕吐等症状。还可做成竹黄，可以缓解气管炎，解胃并止热痛。还可以做成竹叶，能杀小虫，解暑热，取少量竹叶泡水喝。还可以缓解不少症状。

   竹子既清高，又有能治疾病地功效，就让我们学习它，做个外面美，内心也美的人吧！

** 学游泳的启示

   去年暑假里，我在学游泳。

   第一天学游泳时，我还没等教练说下去，就下水了。一下水，水非常冷，我冷得直抖，所以就留在了岸上。第二天，我学游泳时，因为我还是怕冷，所以学不好游泳。在家练屏气，也只屏两三秒。所以数次下来，还是学不会，最多只能屏五秒。妈妈决定换个教练，让我继续学下去。

   第二次学游泳，我一开始学还是有点怕冷，所以状态还是不大好，又过了几次后，我终于会屏气了，慢慢地也会漂浮了。但我有些动作还是不会，而且耳朵也进水了，并且发了炎。所以游泳只能中断。

   之后，我病好了。妈妈又要给我去学游泳。我一点也不情愿。我说：“我不去学游泳，实在是太烦了，水太冷，耳朵都发炎了。”妈妈说：“不经历磨难，怎能见彩虹。如果你就这么放弃了，那你就永远也学不会。”

   我只好硬着头皮去学游泳。第三次学的时候，我慢慢地学会了，学会了很多动作。并且还能自己一个人游十米了。我终于有了进步，我很高兴。

   这次学游泳，让我知道了一个道理。人如果遇到了困难，必须要迎难而上，遇到挫折不能放弃，要克服困难。

** 我是一台电视机

   我是一台电视机。我由一对支架支撑着房间的柜子上。

   用我的时候，只要按一下电视的开关，就能打开了。打开后，按一下电视里的搜索，就可以看任何节目，只要你知道影片的名字。而且还可以观看直播电视，只要点一下小微直播，再搜索节目，就可以看直播的电视啦！我有十二个图标，分别是电视、电影、动漫、少儿、直播、搜索、音乐、屏幕切换、设置、系统、应用、查询。前面的电视、电影、动漫、少儿是可以查找这一类的节目。而音乐就是可以查找你想听的音乐。而屏幕切换是把喜欢的屏幕图片选出来把原来的换去。设置系统查询就是我的系统，还可以查询我的信息、我的公司等。设置是可以装上什么，删去什么，或者调整一下。而应用就是装些东西，什么看电视的软件就在这里安装，比如什么游戏，加快电视播放的速度的软件等。

   那万一看了一会儿，卡住了怎么办？没关系，我看电视是很流畅，一集或者一部是不太会卡住的。即使卡住了，也没关系，只要半分钟至一分钟就可以看了。

   我非常爱我自己。我的功能大家都知道了吗？希望大家能来看我吗？

** 三只小甲鱼

   奶奶家最近养了三只可爱的小甲鱼。

   我给它们取了名字，一只叫做多多，因为它的身体比另外两只都要大，一只叫做笨笨，它经常呆呆躺在缸里，还有一只叫做明明，非常聪明，每吃一次食物，都是它吃得最多。

   它们的样子是这样的，黑黑的龟壳上有几个晶体装的斑点，中间原来是硬的，前面的背壳非常粘人手。前面的背是软的，后面背越来越硬。它们的眼睛是个小黑点，脖子非常长，大概有 5、6 厘米长呢！脖子也很皱巴巴的。它们的嘴巴是尖尖的。四只脚短短的，非常软。它们吃食物时，用一只脚喝另一只脚一起拉扯食物，撕成小块，再用小嘴吃下食物。它们可以吃很多种食物，比如蛋黄、生肉、虾等。

   它们经常一个站在另一个背上嬉戏。有些时候，大家都躲到缸边，爬来爬去。它们的生存能力非常强，所以几天不吃东西，都没有关系。

   我非常喜欢奶奶家的小甲鱼。因为它们非常可爱，所以我喜欢它们。

** 学骑自行车

   这段时间，我在学骑自行车，学习了两个星期。

   第一天，我推着自行车出去。我骑上自行车，坐在坐椅子上，就开始骑了起来。一开始，我骑得非常慢，非常差，后面骑得非常快。最后到了终点。爸爸夸我骑得好。

   后来得几天，我到小区周围骑着，到各条路去骑。

   过了一个星期，弟弟和我都在奶奶家。弟弟也有一辆自行车，他也在学。他说跟我一起去骑自行车。我说：“也好，我们一起比谁骑得快。”弟弟说：“好。”

   我和弟弟一起去奶奶家小区后面的小路上骑自行车。我和弟弟两辆自行车并排停在路上，一声“开始”，我们就开始骑了。我们两辆车左一辆、右一辆就骑起来。弟弟越骑越快，骑得太快了，所以不小心摔了一跤。所以我就成了第一名。正是因为我骑得次数多，所以才能成第一名。

   是啊，有些事情要有恒心，才可以做一些事，学会一些本领。有些事情要练得多，才可以做好事。

** 母亲的爱

   母亲的爱非常伟大，是那首歌唱的：“世上只有妈妈好，有妈的孩子像块宝……”一样，还是和孟郊的《游子吟》中所表达的“慈母手中线，游子身上衣”一样。妈妈，我想对您说我藏在心里的话，今天就让我一吐为快吧！

   我的妈妈对我非常好。每天，一早上烧好早饭，送我去上学。下午放学后，给我削好水果或准备好点心，并问我学校里的事情。吃晚饭的时候，妈妈一个劲地给我把菜放进我地碗。晚饭后，又做了洗碗等家务。做完这些事情后，不休息，还来帮助我，教我做作业，改正我作业中的错误，辅导我学习，有时还帮助我分析试卷的错题，给我签名，还教我一些题目。晚上，妈妈又干了很多事情，很迟才睡觉。每天晚上，您总是一副疲惫的样子。

   记得我小时候，有一次得了肺炎。您知道后，第一时间带我上医院，陪伴了五六天，而且还细心地照顾我。晚上很晚才睡。有一天，我就在医院里吵着说：“眼泪擦擦，眼泪擦一下。”之类地话。您知道我明明没有眼泪，可您还是给我擦了很多次。我说了不知道有几遍，您也擦了很多次。后来，我又说：“妈妈走开，走出去。”之类的话。您迫于无奈才走出去，一个人在外面冷冰冰地走路，走到凌晨才回来。现在回想起来，泪水便涌进了我的眼眶。您无微不至地照顾我，可是我却把您赶出了医院。真是不应该啊！请您原谅我，原谅我小时候的不懂事。

   妈妈，对不起。您帮助我克服困难，激励我前进。所以，我要谢谢您！

** 金华一日游

   叶圣陶先生有一篇文章叫《记金华的双龙洞》，自从学习了那篇文章以后，金华双龙洞是我一直很想去的地方。上个星期天，我和妈妈、外婆一起跟旅游团去金华，去了双龙洞和东阳木雕城。

   乘着车，来到金华双龙洞。在洞外观望，看到洞中有“双龙洞”三个大字。进了外洞，排着队去乘小船，一条小船可以乘六个人，躺在小船上，要仰面擦着石壁才能过去。进了内洞，有很多千奇百怪的石头，构成了很多的景点。有天狗望月、鲤鱼跳龙门等等。还有很多千奇百怪的石笋、石钟乳等。走出双龙洞，就是冰壶洞。冰壶洞到处都是水，走了一点儿路，就是瀑布，流得非常急，水也很清澈，那就是母子瀑，我们还在母子瀑旁拍了照片。

   走出冰壶洞，就是桃源洞。桃源洞里也有很多石钟乳和石笋，还有很多千奇百怪的石头，构成一些景点。洞中得石头非常潮湿，石头上得水非常粘人。

   后来，外面还去了东阳木雕城，木雕城里有很多木制、竹制的东西，数不胜数，比如大到刻有十二生肖得桌子和椅子、红木做的家具，小到木筷、佛珠、饰品。木雕城二期旁还有木雕博物馆和家训馆。我们去参观了家训馆，里面介绍各朝各代教育子女的家训及故事等。

   这次去金华，真是受益匪浅，特别是看到了双龙洞的奇石和冰壶洞的飞瀑，真是大开眼界，收获满满啊！

** 魅力古城在绍兴

   东湖湖水碧如玉，

   柯岩云骨高入云。

   会稽山脉奇秀丽，

   若耶溪畔景似画。

   兰亭修竹忆书圣，

   鲁迅故里仰文豪。

   沈氏名园诉悲情，

   秋瑾碑前赞女侠。

   鉴湖水啊，如明镜，

   古纤道啊，似飘带，

   乌篷船啊，摇啊摇，

   桥洞洞里，大如天。

   茴香豆啊，脆啊脆，

   老酒过过，蜜蜜甜，

   干菜肉啊，香啊香，

   娃娃口水，哆哆流。

   绍兴古城，有魅力！[fn:16]

** 赠人玫瑰，手有余香——读《青鸟》有感

   前段时间，我在看比利时著名作家莫里斯·梅特林克写的《青鸟》。看完这本书，我便思绪万千。

   《青鸟》这本书主要内容是讲一个圣诞节的前夜，蒂蒂和咪蒂的家里非常安静。因为他们家很穷，没钱买礼物。这时，仙女走进来，说自己女儿生病了，要找青鸟，才能治好病。就这样，兄妹俩踏上找青鸟的路，他们去了夜神宫殿、回忆国、幸福花园、未来世界等。在规定日期到来时，兄妹俩还是没有找到青鸟。他们难过失望地回家，却惊喜地发现，代表幸福地青鸟并不在远方，而一直就在他们身边。

   是啊，赠人玫瑰，手有余香。当你帮助他人时，自己也会感到幸福。

   我曾经参加 00 后小义工。有一次，我带着我的小队“阳光小队”，在酷热的暑假给行人送水。有一次给一位邮递员送水。邮递员叔叔还送了我们一份报纸。我还参加了不少 00 后小义工的活动。从一个个活动中，我感受到了帮助别人的快乐。

   从这个事例中，我感受到了我们要宽容要无私，要帮助他人，正是这样，自己才能身心愉悦。幸福无处不在。赠人玫瑰，手有余香。如果你去帮助他人，就能感受到真正的幸福和快乐！让我们行动起来吧！

** 火星撞地球脑力大碰撞

   上个星期天，我参加了绍兴青少年活动中心组织的“燃烧吧，大脑”思维训练营。

   一进青少年活动中心，我参加他们组织的第一个环节“全员加数、脑力对抗”。这是数字连线，就是一个数字，十六个数字有减号就算减，没减号的就是加。可以连好几个数字，可以对角线、直线、横线连线。有一个小朋友，闯了三十二关，我闯了七关。

   第二环节是一位老师给我们上了一节生动的数学课。前面讲的是叛徒定理。叛徒定理是讲动物王国，一只羊家和一只骆军，有个骆兵投降了，影响不是它一个人，而是两个人。后面讲的是巧填算符进阶，讲的就是算式填符号。

   第三个环节是每组准备三十五颗棋子，两人依次取棋子，每次只能取一至三颗，谁取走最后的棋子就获胜。玩了三局，跟我玩的人赢了两次，我赢了一次。之后赢的人再比。后来，一位老师给我们讲解一堆棋子拿法。

   这次参加活动，真是非常好。我既玩了数学游戏，还学会了一堆棋子的拿法。希望你下次也能来。

** 我家来了小客人

   上个星期天晚上，我正无所事事。突然，门外传来了一阵轻微的声音。爸爸连忙去开门。这是谁呢？我心中正想着呢。一个穿黑色衣服的小男孩出现在我的面前。他手里拿着一个盘子，盘子里放着很多车厘子。这个人说：“我是你们楼下的邻居，我到你们这里来玩一会儿。”妈妈欣然应允了，把他领进了客厅。

   我和他坐在椅子上。一开始我们俩都没说话。后来，我说：“你叫什么名字？”他说：“我叫汤博元，你呢？”我说：“我叫舒铭。”然后，我们两个就吃了不少车厘子。但我们两个干什么呢？妈妈说：“要不你们下《三国杀》吧！”我们俩都同意了。选武将的时候，他选了甄姬，我选了关羽。下了一会儿，他渐渐占了上风，最终我扭转局势。第一局我赢了。又下了第二局，我选了赵云，他选了曹丕。我们下了好长时间，才分出了胜负，又是我赢了。时间不早了，我们刚要送他出去。

   这时，他的妈妈来了，跟我们聊了几句，就带着儿子走了。

   我非常高兴，我有了一个朋友。这晚上我过得真是太愉快了！

** 去同学家

   这个星期的星期五下午，江宇皓邀请我和赵磊去他家里玩。我和赵磊都答应了。

   放学后，我们一起来到了江宇皓家小区，先去了小区的小店里，我们买了四包干脆面，其中有两包是“再来一包”的卡，所以赵磊又拿了一包，但干脆面没了。所以我们就去了江宇皓家。江宇皓家在四楼，他的家非常大，有五间房间，地板是木头砌的。他的家宽敞明亮干净。

   后来，我们又看了《勇敢的心》这部抗战片。看了一会儿，我们就一起去叫陈赢舟，我们又去小店买了东西，吃了不少食物。

   我们先去健身的器材锻炼，后来赵磊的妈妈来了，赵磊走了。我们三人就一起玩“猫捉老鼠”，“猫捉老鼠”是其中一个人当猫，两个人当老鼠，猫的地方有六颗钻石，老鼠有三次机会，要获得六颗钻石，老鼠才能赢。我们玩了一局，我们赢了。外面已经很晚了，五点三十分了。我没办法，依依不舍地回了家。

   星期五去同学家，我非常高兴！

** 游安昌古镇

   春节快到了，安昌迎来了一年一度的腊月风情节（原句 一年一度的腊月风情节也到了）。今天，阳光明媚，艳阳高照。我、妈妈和外婆怀着兴奋的心情去安昌古镇游玩。

   我们乘着公交车，来到了安昌古镇。古镇的老街沿河而建，有 1500 多米长。河的南岸住着居民，北面是商市。沿街的各式传统老店密密麻麻，土产品琳琅满目。老街两旁挂满了一串串香肠、酱鸭、酱鹌鹑、鱼干等等，散发着诱人的香味。外婆介绍说：“香肠是用猪的肠子做的，深红色的是酱肉灌的，粉红色的是盐腌渍的肉灌的，腊肠别看难看，可好吃了。”我忍不住香气的诱惑，买了一串香肠，真是好吃好极了。

   古镇的房子错落有致，古色古香。那里的小桥也是别色，安昌素有“碧水贯街千万居，彩虹跨河十七桥”之美誉。沿河而行，顺路来到了深巷里的穗康钱庄，穗康钱庄是由於氏父子创办的。钱庄里的财神与现在的财神截然不同，他左手托着三个叠放的元宝，右手握拳平举于右胸，身穿上红下蓝的古装，端坐在太师椅子上，面带微笑。原本是安放在一个神龛内，神龛上写着“克存信义”四个字。钱庄里还有一株分开三个分枝的腊梅。

   之后，我还参观了师爷馆。安昌不仅有着悠久的文化，还是一个师爷故里呢！安昌在晚清河民国时期出了许许多多的人才，都当过师爷。师爷就是专门为当朝官老爷出谋划策的人，称其为“师爷”。我还参观了宣卷馆、民俗风情馆、石雕馆、仁昌酱园等。

   这次安昌之行，让我了解了安昌的历史文化、民俗风情，真是受益匪浅、收获满满啊！

** 马鞍拜年见闻

   正值新春佳节，我、妈妈外婆一起去了柯桥区马鞍镇，给舅公们拜年。

   我们到达马鞍镇时，时间还早，我们先爬了驼峰山。我们走着倾斜的山路来到了山顶。从山顶眺望大地，各式各样的建筑融为一体。我们还去了山顶的青狮庵，前面是大雄宝殿，有如来、四大天王、观音。观音前面可以抽签。后面就是十八罗汉，气宇轩昂。往右走，就是西方三圣的大殿，里面非常大。再往里走，就是用铜雕做的五百罗汉，栩栩如生。我们一一都拜了佛。

   之后，我们去了马鞍镇的寺桥村，看到了拓宽的河道、清澈的河水、整洁的马路，两旁一幢幢小高楼林立着。我们去了三个舅公家，给他们分别拜了年。我们吃了美味可口的佳肴，有各种肉类和各种蔬菜类。发出诱人的香味，让我们小孩子口水直流。后来，我们去了菜地，看到了油得儿菜、白菜、青菜等。我还看到了扁担。

   今天真是开心得一天，我不仅拜了年，还收获了不少知识，真是收获满满啊！

** 孝敬父母

   父母的爱非常伟大，是他们给了我们生命，是他们精心照顾培养我们，我们应该终身报答。乌鸦反哺，羔羊哺乳。孝是中华民族的美德，我们作为小朋友，应该孝敬父母。

   记得有一次，爸爸摔了一跤，膝盖受伤了，我克服了独自下楼的恐惧，下楼给爸爸买红药水，以前我可没有一个人能下楼，也没有一个人去药店买药。我再药店里给爸爸买了红药水，药店里的人都说我懂事，有孝心。回到家里，妈妈说我是个好孩子，孝敬父母，很懂事。

   记得还有一次，妈妈生病了，起不来床，她说：“铭铭，你能给我削个鸭梨吗？”我说：“好的。”我给妈妈削了个鸭梨，一片一片喂进妈妈的嘴里。过了几天，妈妈就好了。

   记得三年级的时候，妈妈生病住院了，我去看望妈妈。妈妈握着我的手，眼泪都在眼眶里。我看着这种情景，心里也十分难过，泪水情不自禁地流到了脸上。

   寒假里，我帮妈妈拖地、洗碗、烧菜，成为了妈妈的小帮手。

   是啊，孝敬父母不是空话，而是要实际去做地。我做的也只是一点点。孝敬父母应该从小事做起，我们应该为父母做一次饭、洗一次脚、端一碗水……

   孝敬父母是中华民族传统美德，我们应该孝敬父母，从我做起。

** 大自然的魅力——读《秘密花园》有感

   寒假里，我有幸读了美国作家弗朗西丝·霍奇森·伯内特写的小说《秘密花园》。

   《秘密花园》这本书讲的是一个从印度来的小姑娘玛丽，她原先脾气不好，性格倔强。父母因意外死了，她被送进了姑父克雷文家，知道了秘密花园。这个花园是克雷文先生和他的妻子建造的。10 年前，因为妻子车祸死了，克雷文先生悲痛欲绝，就把花园封锁了起来，成为了一个谁都不能提起的秘密。玛丽在知更鸟的帮助下，找到了钥匙和大门，并在佣人的儿子迪康的帮助下，复苏了花园，帮助姑父的儿子科林健康快乐地成长。

   这本书告诉我们大自然的作用。大自然是很美丽的，能让人的心灵变得纯洁舒畅，能让人神清气爽，可以让人的态度变好，脾气柔和。大自然是有无限魅力的。我们小朋友应该多进行户外活动，多呼吸新鲜空气。

   寒假里，暑假里，妈妈经常带我在户外运动，所以我的身体比较健康。大自然是无私奉献给人类的。但是有些人却在破坏大自然，比如过度砍伐树木、污染河水等。

   这本书让我想起了近年来的雾霾，在雾霾的笼罩下，天空灰蒙蒙，不少人都生病了。这就是大自然带给我们的教训。我们要热爱大自然、保护大自然、关爱大自然吧！大自然的一草一木都能带给我们无限的活力。

   就让我们去亲近大自然，热爱大自然、关爱大自然吧！这样，在大自然中，我们舒畅自己的心灵，丰富自己的知识。

** 学编程

   这周的星期五，妈妈带我去胜利东路上的凯盛国际大厦体验编程。

   我们来到了学编程的地方，那里已经有九个小朋友了。首先，老师介绍编程，编程有很多人在使用，国外使用人数更多一些。中国的杭州有编程的兴趣班。编程可以培养逻辑思维能力，提高学习主动性，激发创造力，提高专注力和毅力。全美超 100 万的孩子在学编程。编程可以编故事情节、动画、游戏。还可以控制机器人和无人机。

   接着，老师让我们感受一下编程。我先打开电脑，进入软件。软件的舞台上出现了一只小黄猫。旁边有许多让小猫做动作的方块，点一下，就会做动作，还可以改变动作的多少、时间等。舞台还可以换背景，人物也可以换。还有很多游戏，我也玩了。这些方块里面还有克隆自己，重复执行，碰边缘就反弹等。

   这次体验编程，让我了解了编程的知识，体验了编程的乐趣，真是收获满满啊！

** 给远方的小朋友写封信

   #+LATEX: \noindent
   重庆的小朋友：

   你好!

   看到这封信，你一定会赶到很惊讶。我们虽然素不相识，但同在一个国家里。一想到这里，我就忍不住想给你写封信。

   我们虽然没见过面，但是我愿意将一颗真挚、渴望友谊的心献给你。我叫舒铭，今年 12 岁，是个聪明、幽默的男孩。我有一双小小的眼睛，戴着一副眼镜，嘴巴不大不小，长相一般。也许你是位活泼开朗的女孩，也许你是与我一样的男孩。不管怎样，我们都是中华的子孙，让我们拉起友谊的手，等候我们相聚的那一天。

   我喜欢自己的家乡——绍兴。我的家乡很富饶。绍兴不仅是鱼米之乡，还是酒乡、桥乡，又号称“东方威尼斯”。这里到处是名胜古迹，天蓝水清，空气清新。茴香豆、臭豆腐、霉干菜等都是我家乡的特产。我家乡有大禹陵、鲁迅故里、东湖等风景区。这里是休闲的好去处，希望你有机会，到我的家乡来游玩参观。

   我爱我的学校，我的学校里有一棵桂花树。桂花开了，香气就弥漫在校园里，使人神清气爽。各种的花朵点缀着校园。校园在花朵、绿树等的装扮下，变得生机勃勃。一幢幢教学楼里，有不少老师，老师们精心地培育着我们。我在树人小学东校区五（8）班读书。如果你愿意的话，我每个学期都可以为你寄一本书和一些照片。我们还可以谈谈学习情况，了解对方的情况。你愿意和我做朋友吗？如果愿意，就请尽快回信吧！

   祝你

   身体健康！学习进步！

   　　　　　　　　　　　　　　　　　　你的朋友  舒铭

   　　　　　　　　　　　　　　　　　　2017 年 2 月 21 日

** 大禹陵观鸟

   上个星期天，我和妈妈随着绍兴野鸟会参加大禹陵观鸟活动。

   我们先向前走了大概 100 米处，观察大禹陵中河中的一个小岛，那里栖息着不少鸟，我们看到了夜鹭，也叫夜鹰，是留鸟，亚成鸟是棕色的，成鸟是黑色的，主要是夜行，白天挂在树上，吃的比较杂，鱼、蛙、蛇、麻雀、雏鸟等。叫声是呱呱的，绍兴东鉴湖、画桥那边也有。还有黑水鸡、白鹡鸰、白头鹎等。我们还看到一大群夜鹭，很是壮观。

   后来又去了大禹陵的一个公园，看到了白鹭、树鹨和大山雀。大山雀长着一张小白脸，黑色腹部，很凶残。还有棕背伯劳，它是赵姓的图腾鸟。我还用观鸟镜看见了伯劳、珠颈斑鸠、白头鹎、麻雀、领雀嘴鹎、雀鸲、北红尾鸲、乌鸫和棕头鸦雀。领头的黄老师介绍了观鸟的步骤：要先听鸟声，然后轻轻地走进，靠近鸟，适当地躲，注意衣服颜色不要太鲜艳。

   接着，黄老师又介绍了一些植物，我们看到了苦楝树，观察了它的果实，果实可以吃，白头鹎也爱吃。我还看到了络石、木莲、樱花树、梅花等。

   今天，我学习了很多鸟类和植物的知识，真是收获满满啊！

** 我奉献，我快乐

   今天是 3 月 5 日，是学雷锋日。我度过了非常有意义的一天。早上六点多钟，我早早地起了床，这是我第一次这么早起床。天空灰蒙蒙的，还下着小雨。我看到这副情景，心里打起了退堂鼓。这可怎么办？是去学雷锋做好事，还是待在家里？我正在进退两难的时候，妈妈走过来说：“铭铭，你还是去吧，这是难得的一次活动，做好事，就要坚持，努力克服困难。”在妈妈的鼓励下，虽然下着淅沥的小雨，但还是阻挡不了我学雷锋精神的热情。我决定风雨无阻，参加毅行环城河，捡拾垃圾的活动。

   我们准时来到了治水广场，那里已经有不少人了，其中有一些是小朋友。起初，我认为捡垃圾很简单，但做起来却并不那么容易。我拿起钳子试着捡起一个垃圾，还没放进垃圾袋里，就掉下了。这时，我才知道捡垃圾并不容易。我想到环卫工人，他们天天为我们打扫街道，起得早，回家也晚，还要经受风吹雨打，多么辛苦啊！我们如果还随手扔垃圾，真是不应该啊！

   我们一路走着，继续寻找地下的垃圾。突然，我看到了一个香烟蒂头丢在地下，我拿起钳子就把它夹起来，刚要放进垃圾袋中，它却掉了。我再次夹起烟头，终于把它放进垃圾袋里。后来，我又发现了一些掉在地上的垃圾。我把它们一一捡起，放进了垃圾袋中。有一张塑料膜，因为太滑，一个人捡不起来，我们四个人一起夹起它的四个角，把它放进垃圾袋中。我们一路走过去，把地上的垃圾全部捡干净。我一看，我们走过的地方，地面变得干干净净了。我想保护环境不是一句空话，而是要有实际行动，不随手扔垃圾，环境将变得很干净美丽。我们一路走，一路捡，走到了迎恩门。到了目的地，我们就回家了。

   通过今天的活动，我知道我们不仅不要随手扔垃圾，还要时刻打扫周围的卫生，使环境干净整洁，让绍兴变得更有魅力，让祖国变得更美好。

   今天是学雷锋日，以前，雷锋叔叔帮助别人，助人为乐。毛主席曾说过“向雷锋同志学习”的话，我们也要向雷锋叔叔学习，当一名“小雷锋”。我从小学一年级开始就加入了绍兴 00 后小义工组织，参加过很多活动。比如，炎炎夏日，在爱心凉茶亭守候，给过往行人送水；寒冷冬日，去火车站，给回家过年的旅客送馒头和苹果；还有去小区发放黄手环、在少儿图书馆补书，给志愿者送鲜花等等。在寒暑假，我还组织班级同学，成立“阳光小队”，带领队员们参加各种活动。学习雷锋不是一句空话，而要实际去做，帮助他们，助人为乐。我奉献，我快乐！我们要争做一名优秀的小义工，一个杰出的少年！

** 我是小义工

   我从小学一年级开始就加入了绍兴 00 后小义工组织，参加过很多活动。比如，炎炎夏日，在爱心凉茶亭守候，给过往行人送水；寒冷冬日，去火车站，给回家过年的旅客送馒头和苹果；还有去小区发放黄手环、在少儿图书馆补书，给志愿者送鲜花等等。在寒暑假，我还组织班级同学，成立“阳光小队”，带领队员们参加各种活动。

   在这些活动中，我从胆子小，慢慢地胆子大起来了。这些活动中，我印象中最深的就是夏日凉茶亭送爱心了。今年暑假，我组织小队，在中兴大桥公交车旁给过往行人送出爱心。我们小义工们热情地招待过往行人，给环卫工人、老人等行人送上一杯杯水，让酷暑难耐的行人小憩片刻，解暑降温。大家都纷纷夸奖我们，其中还有一位邮递员叔叔为了奖励我们，还送给我们一份报纸呢。

   除了这些活动之外，今年的 3 月 5 日，我作为 00 后小义工，参加毅行环城河，捡垃圾活动。虽然下着淅沥的小雨，但还是阻挡不了我学雷锋精神的热情。我在妈妈的带领下，拿着铁钳，弯下腰捡垃圾。起初，我认为捡垃圾很简单，但做起来却并不那么容易。我拿起钳子试着捡起一个垃圾，还没放进垃圾袋里，就掉下了。这时，我才知道捡垃圾并不容易。我想到环卫工人，他们天天为我们打扫街道，起得早，回家也晚，还要经受风吹雨打，多么辛苦啊！我们如果还随手扔垃圾，真是不应该啊！我们一路走着，继续寻找地下的垃圾。突然，我看到了一个香烟蒂头丢在地下，我拿起钳子就把它夹起来，刚要放进垃圾袋中，它却掉了。我再次夹起烟头，终于把它放进垃圾袋里。后来，我又发现了一些掉在地上的垃圾。我把它们一一捡起，放进了垃圾袋中。有一张塑料膜，因为太滑，一个人捡不起来，我们四个人一起夹起它的四个角，把它放进垃圾袋中。我们一路走过去，把地上的垃圾全部捡干净。我一看，我们走过的地方，地面变得干干净净了。

   通过这次捡垃圾活动，我认识到保护环境的重要性。保护环境不是一句空话，而是要有实际行动，我们不仅不要随手扔垃圾，还要时刻打扫周围的卫生，使环境干净整洁，让绍兴变得更有魅力，让祖国变得更美好。

   学习雷锋不是一句空话，而要实际去做，帮助他人，助人为乐。我奉献，我快乐！我们要争做一名优秀的小义工，一个杰出的少年！

** 给蚂蚁“洗澡”

   童年是一串晶莹的珍珠，每颗都会让你开怀大笑。其中，最让我难忘的事就是给蚂蚁洗澡了。

   那时，我刚上幼儿园，爸爸给我买了一个养蚂蚁的小盒子，里面又几十只弓背蚁，它们黑黑的、小小的，盒子里还有很多管子和隔层。我十分喜爱，经常把蚂蚁盒子放在床边，看着蚂蚁爬来爬去，一起吃食物、喝水。可是，我经过一段时间的观察，发现蚂蚁从来不洗澡，它们多脏啊！我一想很多动物都洗澡，而它却不洗，还是我帮它们洗个澡吧！我拿出小勺子，盛了一点点水，然后浇向蚂蚁的家，蚂蚁顿时动了起来，在水中动来动去，好像在游泳似的。我一看，非常开心！我一想，这么长时间没洗澡，这么脏，再多洗一会儿。这时，爸爸走了过来，说：“你在干吗呀？”我说：“我在给蚂蚁洗澡。”爸爸听了，哭笑不得，说：“你怎么能给蚂蚁洗澡呢？蚂蚁是一种怕水的动物。”我一看，被我用水浇过的蚂蚁全都一动不动，好像死了。我后悔极了，我为什么要给蚂蚁洗澡呢？害得蚂蚁都死。这件事让我伤心了许久。后来我上网查了一下资料，蚂蚁是一种怕水的小动物，下雨了，蚂蚁要搬家，搬到高的地方去。

   童年的事虽然一去不复还了，但这些回忆还是牢牢地印在我的脑海中。

** 激烈的球赛

   夕阳的余晖照在大地上，放学后，同学们在校外一处废弃的空地上拿出了足球，摆开了阵势，吸引住了小弟弟和小妹妹们，就连大个子叔叔都来看这场球赛。队员们把书包当作球门，分好了队，就踢起了足球。

   那个平头的小守门员目光注视着前方，戴着皮手套，上身前倾，半蹲着，即使膝盖擦破了皮，也不在意。一个穿红色衣服的小孩，在守门员后面站着，他一心想让自己大显身手，挡住几个险球。对方的一个队员，绕过了这一方的队员。那个队员一个射门，就踢向这方的门，守门员往前一扑，牢牢地抱住了球。场外爆发出一阵掌声。

   瞧！那个戴红色帽子的小女孩，怕别人挡住她的视线，探着整个身子，看着足球赛。那个搂着小弟弟的小男孩，也聚精会神地看着球赛。还有一个戴着红蝴蝶结的小女孩，索性站了起来，看着激烈的球赛。她旁边那个小男孩眼睛死死地盯着，好像是第一次看足球赛。不知道谁家地小白狗也跟着主人来了，它懒洋洋地躺在地上，谁赢谁输好像跟它一点关系也没有。还有一个小女孩，脸上没有表情，摆弄着手中的洋娃娃，好像谁胜谁负也和她没有关系。而她旁边地小男孩则兴致勃勃地看着球赛，可能也是他第一次看球赛，才看得这么认真。就连走过的大个子叔叔，都顾不上放下手中的文件，也停下来，观看这场足球赛。可能这场足球赛勾起了他对以前童年或对足球的回忆。

   这真是一场激烈的足球赛啊！不论是球员，还是观众，都聚精会神。过了二十几分钟，终于分出了胜负。

** 竞选班长发言稿

   #+LATEX: \noindent
   敬爱的老师，亲爱的同学：

   大家好！今天，我站在这里，竞选的是班长。俗话说：“宝剑锋从磨砺出，梅花香自苦寒来。”拿破仑也说过：“不想当将军的士兵不是好士兵。”大家都知道，我胆子小，性格内向。所以今天我才要站在这里，竞选班长，挑战自我，锻炼自己。

   从一年级开始，我就当上了小组长，每天收本子，收得整整齐，拥有一定的工作经验。在四五年级，我当上了寒暑假活动的小队长，组织队员参加活动，管理队员，有一次还被评为优秀小队呢！通过这些经历，我拥有了一定的管理能力和经验。此外，我还成为 00 后小义工，经常义务服务，拥有一颗爱心。

   假如我当上了班长，我决不会把班长当作一个虚名，而是实实在在去做，认真地做。我会自己认真地学习，遵守纪律，为同学树立一个好榜样，成为同学们信赖的伙伴，成为老师的得力助手，成为同学和老师之间的桥梁。我还会团结其他班干部，齐心协力管理班级秩序，开展丰富多彩的活动。我还会动员成绩好的同学帮助成绩落后的同学，让大家一起提高学习成绩，提高学习效率，一起进步。

   总之，我会尽自己的能力，管理好班级，让我们班成为优秀的班级。

   也许我身上还有不足，距离你们心目中的班长还有一段距离，希望大家公开地指出来，我将虚心地接受大家的意见，成为一名合格的班长。

   我真诚地希望大家能投我一票，让我有机会为大家服务，谢谢大家！

** 一次难忘的自然观察

   上上个星期天，天气晴朗，阳光明媚。妈妈带着我去府山参加自然公开课，寻找胡颓子。

   一路上，我们几个小朋友说说笑笑，很是热闹。我们先看到了一些鬼针草、结香。根据老师的介绍，我才知道结香的枝条很柔软，可以打结，开三个枝杈，花很香，还可以造纸呢！我们往前走，还看到了枸骨，绍兴人叫“老虎脚底板”，还看到了薜栗果、毛茛等。这些小花小草都是我平时很难见到的。

   我们走着走着，还看到了树上的松鼠，小松鼠活蹦乱跳，在树上蹿来蹿去，毛茸茸的，有长长的尾巴，红色的腹部，非常可爱。往山上走，还看到了刻叶紫堇、八角金盘等。刻叶紫堇十分好看，有五个花瓣，都是紫色的。接着，我们去观察了今天的重点——胡颓子。这种植物我以前都没有听到过。胡颓子有麻点，跟大部分植物不一样，胡颓子是秋花春实，与枇杷类似，但它结果更早，现在就长出果实了。果实上鳞片很多，大多是银白色的，只要用手一搓，就可以把它们搓掉。果实有些像枣子，味道淡淡的。不过现在还没有成熟，果实涩涩的。

   这次自然课，让我体会到了自然之美，大自然的魅力。

** 寻找幸运“四叶草”府山公园亲子定向活动

   草长莺飞，桃红柳绿，春天到了，一切都生机勃勃。在这个阳光明媚的星期天，我和妈妈参加了“我爱旅游”公司组织的寻找幸运“四叶草”亲子定向活动。

   我们来到了目的地府山公园，那里已经有很多人了，周围的人也纷纷到组织者那儿报名，一来二去，也就凑足了二十对家庭。这时，组织者向我们介绍什么是定向活动，定向运动就是利用地图和指南针依次到访地图上所指示的各个点标，以最短时间到达，并完成任务者为胜。每隔三分钟出发一组家庭，我们是第 2 组。总共有六个活动。我们先来到了第一个活动点，第一个活动是“智力大冲浪”，是问一些问题，有脑筋急转弯、常识题等。我在这个环节中被问到了几个问题，其中有些问题我能答上来，而有些想了半天，也没答上来。剩下的活动中，最有趣的莫过于是“趣味吃饼干”了，“趣味吃饼干”是把饼干放在额头上，利用面部肌肉的活动把饼干吃下去，我吃了十几次也没把饼干吃下去，最后把饼干放在嘴巴旁才吃了下去。此外，还有许多精彩的活动如两人三足、企鹅漫步、反向运动等，我们用了二十五分钟，才完成任务，得到了第二名。第一名用时二十三分钟，真是太可惜了，就差了两分钟。

   春光明媚，让身体苏醒吧！让亲子之间增加浓浓的亲情吧！这就是定向运动的魅力，希望你也能来参加！

** 一件让我感动的事

   在我记忆的长河中，有过许多让我感动的事，但我让最感动的还是这件事。

   那是我上幼儿园的时候，那时我才五岁。有一次，我得了感冒，后来病情严重了，妈妈第一时间赶到学校，给我去医院检查，检查出来我得了肺炎，要住院。妈妈就陪着我在医院住院。在住院期间，妈妈精心照顾我，给我吃药，给我擦汗，照顾得无微不至。那几天，我因为生病了，情绪不好，脾气也很差，对妈妈态度也不好。

   记得有一天晚上，我心情不好，就大发脾气，对妈妈说：“眼泪水擦擦，眼泪水擦擦。”实际上根本就没有眼泪水，妈妈没办法，只好拿出餐巾纸给我来擦。但我还是继续哭闹，并说让妈妈出去之类的话语。那时是冬天，夜已经很深了，整个医院静悄悄的，人人都在沉睡，而且外面的风像刀片一样。妈妈没有办法，只好出去。我目送着妈妈的背影，心里有说不出得滋味。

   过了一会儿，妈妈回来了。我原以为她会来骂我，结果什么事都没发生，她还是一如既往地耐心照顾我，问长问短，问寒问暖。我在迷迷糊糊中睡着了。在妈妈的精心照料下，我出院了。这件事情让我很感动。

   除了这件事外，妈妈还对我非常好，陪我参加活动，每天放学后，都来接我，对我无微不至的关心。这些事情都使我很感动。

** 校运动会

   4 月 1 日，我校组织了隆重、激动人心的运动会。那天，天气晴朗，万里无云，全校师生怀着激动的心情参加了这次运动会。

   我们一早乘着公交车来到了这次开运动会的场地——绍兴中专。我们迈着整齐的步伐来到了操场。运动会的入场仪式可谓五花八门，有的班级的入场表演是击剑，有的是舞蹈，还有的是舞狮，可谓千姿百态。

   我们表演的是扇子舞，当“茉莉花”的音乐响起，我们就翩翩起舞。在表演的过程中，我心中有一丝紧张，万一做的不好，那怎么办呀？当做完了后，我才如释重负。表演好了以后，我们就站在草坪上，看别的班级表演。表演结束后，一个个氢气球飞向了天空。操场上空还有一架无人机在全程拍摄。

   下午，就是运动项目比赛了，我观看了一场 400 米女子赛跑。当发令枪“砰”的一响，运动员们就“腾腾”地飞奔起来。周围的小朋友摆动着手臂，高声地呼喊着“加油”。这些运动员不负众望，都跑到了终点，没有半途而废。我在学习中，也要学习运动员这种精神，不要轻易放弃，要努力拼搏。

   天气有点炎热，我们虽然又渴又累，但是都很兴奋。下午四点左右，这场激动人心的运动会终于结束了，我们依依不舍地离开了绍兴中专，回到了学校。

** 学工活动

   一年一度的学工活动又开始了，李老师带着我们全班同学去青少年活动中心参加活动。

   我们乘着公交车，到达了目的地。第一个活动是做科学实验。老师先是让我们测河水 PH 值，就是把药水滴进瓶子里，看它的颜色与 PH 值的纸上哪种颜色最吻合，就是哪种数值。每种颜色都有数值，7.1-8.2 是最好的。然后是测水中的杂质和矿物质，用到的检测笔用来检测水中的杂质。测矿物质是滴三滴试剂，如果呈蓝绿色，就是有矿物质，如果是其他颜色就是没有矿物质。之后是测水中的余氮，测余氮也要先滴三滴试剂，然后看另一种图，按照颜色写出数值。最后就是净化水了，把水倒进一个净化水的杯子里，这样水就会流下来，流进底下的盖子。最后我们小组得了第三名。

   第二个活动是攀岩与速降。老师先讲了动作要领，之后，我们就到了攀岩与速降的场地，我们分为六组，四组攀岩，两组速降。我先玩的是速降，我把装备都装好了，蹲着身子往下降了下去，在下去的一刹那，我有点害怕。这毕竟是从高空降下去啊！万一出危险怎么办呢？但我还是降了下去，踩在了底下的垫子上。成功了！我心里非常高兴。

   第三个活动就是挑战趣桥了，老师先给我们讲了四座桥该怎么走。之后，便来到了趣桥的场地里。趣桥是由四座桥组成的。第一座桥是锁链桥，是由一根绳子、链条和铁板组成的。第二座桥是由三根绳子组成的，叫做缅甸桥。第三座桥由梅花桩、链条、绳子组成的，顾名思义，就叫梅花桥。第四座桥，叫做跷板桥，由跷板和一根平衡木组成。我从第一座桥开始走，在走第二座桥的时候，就不太容易了。第二座桥踩的只是一根绳子，非常难保持平衡，我差点就掉了下来。之后的两座桥就容易了，我飞驰般地走完了后面两座桥，之后就回学校了。

   这次学工活动真是让我收获满满啊！

** 《郑和下西洋》读后感

   最近，我看了一本叫做《郑和下西洋》的书。

   《郑和下西洋》是一本很好看的书，书中的主人公是三保太监郑和，他历经二十八个年头，曾七下西洋，可以说是取得了世界上时间最早、规模最大、活动范围最广的航海业绩。郑和是一位杰出的航海家，比欧洲大航海家哥伦布还早几十年，他不仅去过西洋各地，甚至还远渡欧洲，克服了航海中的各种困难。他不怕困难，勇于克服困难的精神值得我们学习。

   记得有一次，郑和的船队在行驶中，遇到了海浪。郑和没有放弃，拼命地与海浪斗争，最终取得了胜利。

   我也曾碰到很多困难，就拿前年的学游泳来说吧！那次，我游泳学习了很多次，碰到了很多困难，不过我没有放弃，坚持了下去，最终学会了蛙泳的基本动作。

   这本书非常好看，不仅有历史，而且还有生动的故事。4 月 23 日就是世界读书日了，希望你也能看一看《郑和下西洋》，读一读好书。

** 游玩儿童乐园

   这个星期六，爸爸和妈妈带着我去游玩镜湖湿地儿童乐园。

   我们到了那里，人已经有不少了。大门口挂着红灯笼，张灯结彩。门里面有许多卡通形象的人物。门外面有一个梦幻水母馆，我在爸爸的陪同下去了那个馆。

   梦幻水母馆向外面展示的全是水母，有火箭水母、钟水母、澳洲斑点水母、霞水母、中华海刺等等。里面的水母千姿百态，有的大，有的小，各有特色。水母有各种各样的颜色，还有一种叫彩色水母，它的颜色是会变的。

   进了门口，我看见高高的假山站着一只栩栩如生的“孙悟空”。一路走去，到处都是卡通形象的人物，有三字经里的孔融，有西游记里的唐僧等。我非常愉快。就这样我们来到“动物王国奥秘展馆”。

   这个展馆有上下两层，总计 5000 余件，有甲虫和蝴蝶、两栖与爬行、海洋鱼类、湿地鸟类等，还有很多标本和化石，让人应接不暇。

   看完这个展馆，我们又去了下一个展馆——海洋化石馆。海洋化石馆里全是化石，有大有小。海洋化石里有海百合和海龙。

   看完化石馆，我们来到了动物园，看完了动物园里的杂技，我们就在看动物了。动物园里有凶猛的狼、呆呆的猪、绅士的鸟类和羊、马，还有狡猾的狐狸。

   到了午饭时间，我们才依依不舍地离开了儿童乐园。希望你也能来游玩。

** 五一游记

   五月一日，我在爸爸妈妈的陪伴下去游玩了杭州湾海上花田。那天，天气很好，阳光明媚。我们到了目的地，进入了景区。景区的大门上挂满了风车，被风一吹，十分好看，像一群小孩子们在欢迎我们。

   里面就像一个公园一样，景色很美，一路走去，我看到了不少花花草草，有玫瑰色的芝樱、粉色的康乃馨、淡紫的酢酱草、紫色的薰衣草、粉白的波斯菊……还有很多我叫不出名来。徜徉在花海中，顿时觉得心旷神怡，美不胜收。

   除了美景之外，海上花田还有很多休闲游乐项目。我们玩的第一个项目时划船，在我们划船的时候，我看到了有一个人在踩着两根毛竹板，从水岸边划了过来，这就是传说中的“水上漂”。我们还看到有一个人在水中放水鸟——鸬鹚。鸬鹚这种水鸟是黑色的，长得并不好看。我和爸爸踏着船，驶到了对岸，但由于我和爸爸的重量不一样，所以船歪歪扭扭，重心不稳，爸爸差点掉进河里。我们回来的时候有风，所以怎么驶也驶不回来，后来总算驶回来了。

   最刺激的就是越野卡丁车了，排了很长的队才轮到我们。爸爸把油门一踩，车子像离弦的箭一样飞了出去。由于开得太快，所以路上的泥都溅在了爸爸的衣服上，这真是真正的“越野”啊！

   我最爱玩的就是骑马了，我平时就非常想像电视里的大将军一样骑马，今天总算能如愿以偿骑一次马。轮到我骑马了，我心里有一些紧张，万一马有些问题，那怎么办呀？但还好，马没有问题，虽然马走得比较慢，但至少走完了两圈。下了马，我才觉得骑马并不怎么好玩，马背上坐着太震了，震得我肚子都痛。

   此外，我还玩了植物迷宫、挖土机、蹦床等项目，这些也非常好玩。

   到了晚饭时间，我们才依依不舍地离开了杭州湾海上花田。这里非常好玩，希望你也能来玩。

** 猪八戒，我想对你说

   /题目：同学们，你一定读过不少中国古典名著吧！哪些人物给你留下了深刻的印象？是孙悟空、诸葛亮、鲁智深？还是别的？选择中国古典名著中一个你喜爱或讨厌的角色，具体写一写你想对他说的话。/

   *猪八戒，我想对你说*

   猪八戒，你应该勇敢一点，要向孙悟空一样有勇往直前的精神。记得你每次打妖怪，打不过了都是第一个逃的。你应该变得勇敢一点。

   猪八戒，你应该勤劳一点，要向沙和尚一样有勤劳的精神。记得每次最重、最累、最脏的事或活都是沙僧做的，你应该变得勤劳一点。

   猪八戒，你应该不好吃一点，不要吃得太多。记得上次唐僧去拿个西瓜，你却偷偷把西瓜给吃了，真是太好吃了。你应该给大家留下一点西瓜，给大家吃一点。你应该戒掉这个坏习惯。

   猪八戒，如果你把这些坏习惯都戒掉，将会是一个既勇敢，又勤劳、不好吃的人。

** 手机的故事

   手机是现代大家不可缺少的一部分，我和手机还有一段故事呢！

   在我十岁的时候，有一次，我和妈妈一起去买菜。妈妈因为在顾着买菜，我因为以前没来过菜场，就东瞅瞅、西看看，便和妈妈走丢了。走丢了后，我灵机一动，只好躲在她的电瓶车上。过了很久，妈妈才找到了我，我回到家，扑在妈妈怀里哭了起来。就是因为没有电话，不方便联系。

   经过这件事情，妈妈觉得应该给我买一个手机，于是，我就有了一只手机。这只手机是黑色的，别看外型小，里面装的东西可多了，可以看电视、玩游戏、上网、打电话等。我非常得开心，因为我有了一只手机。有了手机，我和妈妈一起出去都带着它，我再也没有丢过。

   但是手机也有坏处，整天玩游戏会导致视力下降，而且还会让自己的身体变得不好，因为手机里有辐射，对身体不好。所以不要沉迷手机游戏。

   我跟手机有这么一段故事，你有没有呢？

   /PS:/

   /有一次，我回到家，做作业的时候，有人敲门。我开门一看，原来是我的表弟。我一问才知道表弟是家里没人来我们家的。我和表弟就玩在了一起。我们玩了很久，发现很没意思，就拿起手机玩起了游戏。玩了不少时间，弟弟妈妈打电话来了，让我们停下来。但我们那一关还没闯好，便还是在玩，又催了一遍，我们还是在玩。妈妈把手机一把夺过去，我们才依依不舍地离开了。/

** 当一回“小八路”

   上上个星期，姑姑带我和表弟去莫干山花花世界当了一回“小八路”。听说可以去当八路，我心里非常愉快，因为我早就想去当“小八路”了。

   我们下了车，到了目的地。我们换上了小八路的衣服，感觉自己就是八路军了。

   一路走过，还有不少花呢！我们玩的第一个项目是过草地。我们从草地上爬了过去。我们过草地的时候就联想到了红军长征的艰苦，他们艰苦的斗争才换来了我们现在的幸福生活，所以我们应该珍惜现在的生活。我们还玩了“飞夺泸定桥”、“过缅甸桥”、“过雪山”等，也非常好玩。我想起了毛泽东写的《长征》，这首诗歌写的就是我们玩的项目。

   玩完了项目，就是午饭时间了，这个午餐可是要自己做的，我还从来没自己做过菜呢！我们这些小朋友一起剥毛豆、洗菜、切蕃茄、打蛋，忙得不亦乐乎。大人们有的炒菜，有的生火，有的准备食材。过了一个小时，终于烧好了。虽然饭和菜有一点焦，因为是自己做的，所以我觉得还是很美味的。

   下午，我们又玩了许多项目，其中有做团子、磨豆腐、抓泥鳅、猪八戒背媳妇等。我做了两个团子，还带回去给爸爸妈妈吃了呢！其中，最好玩的就是抓泥鳅了。泥鳅非常难抓，因为它很滑，我抓了很久，也没有抓到一只。“猪八戒背媳妇”也挺好玩的，就是大一点的孩子换上猪八戒的服装，当猪八戒，背小一点的孩子来回得走过去。

   玩到了三点，我们才依依不舍地上了大巴车。德清莫干山地小八路景区非常好玩，希望你也能来玩。

** 感受忠义，走进三国——读《三国演义》有感

   我非常爱看书，从五岁就开始了我的读书生涯。我读的书有很多，低年级时，我爱看一些童话故事书；到了中年级，我爱看一些历史、神话小说，到了高年级，我就在看一些中外名著了，我常常看得手不释卷。

   我最爱看的书就是罗贯中的《三国演义》。

   “滚滚长江东逝水，浪花淘尽英雄……”，读着这《三国演义》的定场诗，我胸中感慨万千，豪情万丈！一个个熟悉的英雄浮现在我的眼前，有白面长须的刘玄德、羽扇纶巾的诸葛亮、面若重枣的关云长、黑脸虬髯的猛张飞，还有那挟天子以令诸侯的曹操、偏安一隅韬光养晦的孙权，一时多少豪杰，但其中我最敬佩的还是关羽关云长。

   关羽是大家都熟悉的英雄，三国里有很多很多关于他的故事，从最开始的桃园三结义，到后来的温酒斩华雄、过五关斩六将、千里走单骑、水淹七军等。关羽有着一种品质，这种品质就是忠义。“千里走单骑”是最能体现出关羽的忠。刘备被曹操击败，投标袁绍，让关羽看守他的家小，关羽又被曹军围困，但是他只是暂时投降，如果知道刘备在的话，就去找刘备。曹操用很多方法来诱饵关羽，但是关羽还是没投降。后来知道刘备的下落，立刻就赶了回去。这就是关羽的忠君报国。而“华容道义释曹操”这件事情是最能体现出关羽的义。曹操放了他一次，如果没有曹操放他，他早已死了。所以关羽也是放了曹操一次。这就是关羽的忠义双全。

   在我们这样一个新时代，忠义有了新的含义。我们的“忠”不再是忠君爱国，而是热爱祖国，忠于人民。而现代的“义”也不再是江湖道义，而是对社会的责任和义务。我们应该学习古人的优秀品质，结合现在的社会，做一名优秀的学生。[fn:17]

** 余姚一日游

   这个星期六，我和妈妈外婆一起预余姚丹山赤水玩。今天，天气很好，阳光明媚。

   我们到了目的地，下了车，进入景区，还没走几步，就看见一块贞洁碑，这块碑是道光三十一年建造的，原来是给一名女子建造的。这名女子，丈夫死后，一生守寡，浙江巡抚刘彬士微服私访到了此处，上报道光皇帝，才建成了这块碑。

   再往里走，有一棵活了六百多岁的香樟树，曾被宋代皇帝御书过。再往里走，还有一口同心古井，这可是全村人的水源。里面还有一个沈氏宗祖，是沈氏后人的一个宗祠。丹山赤水中有一个柿林村，柿林村民风淳朴。里面还有一个余姚第一党支部书记纪念室，讲的是余姚的抗日经过。

   再往前走，凉风习习，竹林幽幽，构成一道美丽的风景线。丹山赤水的岩石是微红色的，还有一座用石头砌成的赤水桥。我听导游介绍说，余姚这边出过很多革命烈士，很多抗日电影也在余姚拍过，导游说她自己还当过群众演员呢。

   离开了赤水丹山，我们还去了梁弄，买了两包梁弄大饼。接着去了参观了浙东四明山抗日根据地旧址群，具体有浙东区党委旧址、浙东行政公署旧址、浙东抗日军政干校旧址、新四军浙东游击纵队军史陈列室、谭启龙旧居、何克希将军纪念室等，了解了不少浙东四明山抗日的具体过程。

   到了走的时间了，我依依不舍地离开了余姚，希望下次还能来玩。

** 《草船借箭》缩写

   周瑜看到诸葛亮很有才干，心里很妒忌。一天，周瑜以公事为由，让诸葛亮造好十万支箭。诸葛亮说只要三天，并按周瑜的意愿立下了军令状。

   周瑜派鲁肃去探听诸葛亮的情况回来报告他。

   诸葛亮让鲁肃准备二十条船，每条船上配三十名军士，船用青布幌子遮起来，还要一千多个草把子。而且不能让周瑜知道，鲁肃应允了。鲁肃回来果然没提借船的事，只说诸葛亮不用造箭材料，周瑜心中疑惑。

   鲁肃把船交给诸葛亮，听他调度。前两天，诸葛亮没动静。直到第三天四更的时候，诸葛亮秘密地把鲁肃请到了船上，下令把二十条船以绳索相连，驶向北岸。这时候，江上雾很大。

   诸葛亮让船一字排开，逼近曹军水寨受箭，并让军士一边呐喊，一边擂鼓。曹操看不清虚实，下令弓弩手向江中射箭。天亮了，雾还没散。船两边的草把子上插满了箭。诸葛亮下令船头朝东，船尾朝西驶回了南岸，再次逼近曹营受箭。

   这时，周瑜派人来江边搬箭。二十条船，每条船上有五六千支箭，总共有十万多支。鲁肃告诉周瑜经过，周瑜自叹不如。

** 关于张姓的历史和现状的研究报告

   *一、问题的提出*

     我们看过课本上关于李姓的研究报告，便对姓氏感了兴趣，想做一次关于张姓的研究报告。

   *二、调查方法*

     1. 阅读报刊，上网浏览。了解张姓的人口和历代名人。
     2. 走访有关部门，了解张姓人口。
     3. 通过多种途径，搜集张姓的名人故事。

   *三、调查情况和资料整理*

     | 信息渠道 | 涉及方面       | 具体内容                                                         |
     |----------+----------------+------------------------------------------------------------------|
     | 上网     | 张姓的名人     | 张良、张骞、张飞、张巡、张浚、张仲景、张大千、张自忠、张择端等  |
     | 上网     | 张姓的人口数量 | 据统计有 9450 万，占全国人口 7.07%                              |
     | 报纸     | 张姓族谱       | 张姓族谱有一百多种，记载了张姓五千年的历史                      |

   *四、结论*

     1. 我国张姓历史悠久，传说春秋时，有大夫姓张，字张候，其子孙以字命氏，也称张氏。张姓氏中国元代第一大姓。
     2. 我国张姓人才辈出，有运筹帷幄的张良，有勇冠三军的张飞，抗金名将张浚等。
     3. 张姓氏中国人口仅次于李姓和王姓的姓氏，据统计有 9450 万人，占全国人口 7.07%。

** 表弟两篇

   /题目：严监生爱钱如命，小嘎子机灵聪明……仔细观察或回忆你身边的人，哪一个人的哪一个特点给你留下深刻的印象？选一个人的一个特点，通过一件或几件事写具体。注意抓住神态、语言、动作等描写表现人物的特点。/

   *慢吞吞的表弟*

   我有一个表弟，他有许许多多的特点，今天就让我给你说一个吧！

   有一天，我和他都去奶奶家。我们想下去玩，但他有一篇作文没抄好，要抄好才能下去玩。我就耐着性子在等他做完。他写字的速度特别慢，像绣花一样。写了 10 分钟，他才写了两排字。我一看便到旁边看书去了。我看了很长时间，料想他应该写完了，便去看了一下，结果发现他在那浇花，字没写几个。我想应该是我走开，他一直在玩。我说：“快点写，别玩了，你都写了快一个小时了，再不写完就天黑了。”他说：“我这就认真写。”又写了很长时间，还是没有写完。结果到了吃饭时间，才写完。

   我后来问了奶奶弟弟为什么写那么慢，这才知道，我写的时间不到一个小时，但玩的时候有一个多小时。

   这就是我的表弟，一个慢吞吞的人。

   #+LATEX: \vspace*{\baselineskip}

   *精明的表弟*

   我有一个表弟，经常跟我玩。他比我稍微矮一点，脸圆圆的，圆得像只皮球，非常可爱，也十分精明。

   有一次，我和他一起去奶奶家，由于天气炎热，所以我们一起下楼去买棒冰。到了买棒冰的小店。我找了一块棒冰问了一下老板娘要几元，老板娘说要五元。他就说：“要不三元，便宜一点吧！”老板娘说：“这已经是很便宜了，不能再便宜了。”他最后说：“我们是旁边的人，会经常来买的，便宜一点吧！”老板娘说：“算了，算了，你们既然是旁边的人就便宜一点吧，三元就三元。”最后，就以三元成交了。你们说我的表弟精不精明？实在让人佩服啊！

   除此之外，他还经常跟我玩大富翁的棋，每次我都是以失败告终。上次我亲眼看见我上衣一颗纽扣掉了，他就在地上进行了地毯式的搜索，找了快一个小时，但还是找不到，他就哭了。我还经常跟我模拟开店买卖东西。他每次都是以最低价买进，最高价卖出，非常的精明。我的表弟是一个精明、有经商头脑的人，你们说是不是呀！

   我的表弟除了很精明，还是个很认真、聪明、搞笑、调皮的人。

   你们说我的表弟可不可爱，精不精明？

** 方特东方神画一日游

   今天，阳光明媚，爸爸带着我去宁波方特东方神画世界高科技乐园玩。

   我们下了车，到了目的地。我们玩的第一个项目是“七彩王国”，“七彩王国”就是乘着船，两岸有许多木偶，既会唱，又会跳，述说着我国少数民族的历史文化。

   我们下了船，一路走过去，就去玩了“丛林飞龙”。“丛林飞龙”源自于北美，是过山车的鼻祖。我们坐上了“飞龙”从高 15 米的道上飞了上去，又从 15 米的地方掉了下去，实在是太刺激了。当它飞下去时，我不禁闭上了眼睛，因为实在是有点害怕。

   玩完了丛林飞龙，我们就去剧场看了《牛郎织女》的电影，十分好看。看完了剧场的电影，我们就去玩了“女娲补天”。“女娲补天”是坐着船，帮着女娲保护五彩石，从而让女娲补天。玩完了“女娲补天”，我们就去看了剧场里的电影《纵横华夏》——一部描述中华历史变化过程的电影。除外，我们还看了《决战金山寺》和《梨园游记》。《决战金山寺》让我们见证了许仙和白娘子的爱情；《梨园游记》则介绍了中华戏剧的历史与文化，中国有许多种类的戏剧如京剧、越剧、黄梅戏、河北梆子等。

   时间过得很快，分别的时间马上到了，我依依不舍地离开了，希望你也能来玩。

** 重走百草园和三味书屋

   《从百草园到三味书屋》一文是鲁迅儿时的一段美好的回忆。鲁迅故居、百草园、三味书屋等景点也吸引了成千上万的各地游客。一个节假日，我怀着无限向往之情来了鲁迅故里，探寻他记忆中的童年。

   走在青石板路上，一边的小河里摇曳着只只乌篷船，一边是白墙黑瓦的老台门，幽静的弄堂，高高的台阶……我仿佛走进了鲁迅爷爷生活的那个年代。我参观了鲁迅爷爷小时候居住的地方。在那里，我看到了整洁的卧室，幽静的弄堂，高高的台阶。接着，沿着青石板路，我来到了鲁迅爷爷小时候的乐园——百草园。映入眼帘的是碧绿的菜畦、光滑的石井栏、高大的皂荚树……我仿佛看到了幼年的鲁迅和闰土蹲在短墙边挖何首乌的情景。

   接着，我又来到了鲁迅爷爷小时候上学的地方，屋子中间挂着一块匾，上面写着“三味书屋”四个大字。那里的老师带领我们饶有兴致地诵起了《三字经》，有模有样对起了课。当听到鲁迅爷爷刻“早”字的故事，我深深感动了。老师介绍三味书屋后面也有一个园，虽然小，但在那里也可以爬上花坛去折腊梅花，在地上或桂花树上寻蝉蜕。听着听着，我仿佛看到了鲁迅爷爷儿时读书玩耍的场景。

   这次参观鲁迅故里，我不光重温鲁迅当时学习和生活的场景，而且更加了解了鲁迅的经历和故事。我深深地被鲁迅的好学和探索精神所感动，在今后的学习中，也要学习他这种精神。[fn:18]

** 柯岩半日游

   柯岩，我来过许多次了，但最近几年没来过，我今天和表弟一起来，别有一番风采呢！

   柯岩景区分为鲁镇、鉴湖、柯岩三个景区。我们先去了鲁镇，鲁镇的游玩项目是要用鲁镇特制的铜板才能参与。我们凭券兑换好了铜板，先坐了黄包车，黄包车就是一个人坐在椅子上，还有一个人拉车。我玩的第二个是打枪，我每一枪都打中了。我中途还看了“假洋鬼子打阿 Q”的表演。听妈妈说鲁镇是鲁迅笔下的小镇，大多建筑都在鲁迅笔下出现的。

   接着，我们坐着游船画舫，游船开过，白花花的浪花欢乐地跳了起来，发出好听地声音，像是在给我们唱歌。我们上了岸，听妈妈说鉴湖为绍兴名湖之一。鉴湖原名镜湖，相传皇帝铸镜于此而得名。其主干道东起亭山，西至湖塘，长 22.5 公里。我们看到了葫芦醉岛、五桥步月、南洋秋泛等景点。唐代诗人李白云：“镜湖水如月，耶溪女似雪。”南宋陆游耶曾高吟：“千金无须买图画，听我长歌歌鉴湖。”鉴湖中最有名地就是古纤道了，也被称为“白玉长堤”。踏着青石板路，凉风习习，湖光山色尽收眼底。古纤道总长百余米，还有小桥，我表弟还即兴作诗一首呢！

   最后，我们来到了柯岩。看到了云骨、大佛、越中名士苑等景点。由于已经四点多了，所以来不及细看，就匆匆而过了，希望下次能认真看一看。

   这次，我跟表弟玩得非常尽兴，虽然我们以前也来过，但没有这么好，这次来柯岩加深了我对柯岩地印象，还看到了柯岩地美景，真是值得啊！

** 重走“一带一路”上的绍兴古桥

   绍兴有着浓郁的文化资源，今天，我和妈妈参加了绍兴网组织的重走“一带一路”上的绍兴古桥活动。我们到了绍兴日报社，集合好之后，就上车了。听妈妈说，这次参加活动的陈老师，用了六年空余时间，拍到了绍兴现存的 500 座古桥，其中有 50 多座与“一带一路”有关。

   我们去的第一座桥是迎恩桥。迎恩桥位于绍兴市区西郭运河进城口子处，它是古代绍兴水路进城的四门户。古代皇帝驾临绍兴，百官迎候，故称为迎恩桥。当时这处地方非常热闹。此桥现在是省级文物保护单位。

   我们去的第二座桥是高桥。高桥是古代绍兴最高的桥，而到了现在，由于立交桥的产生，高桥俨然成为了“低桥”。高桥旁边是运河园，园内荷叶连连，期间，贺循的雕像赫然耸立，仿佛见证着绍兴的发展变化。之后，我们来到了离高桥几米之隔的泗龙桥，泗龙桥是东浦有名的桥，民间又称“廿眼桥”，长 102 米，像一条长龙。

   后来，我们来到柯桥区，第一站是融光桥。融光桥又名柯桥大桥，位于绍兴市古桥镇古运河上，始建于宋，明、清代重建。旁边还有柯桥、阮社桥。我一直以为柯桥是个地名，原来还真有座桥呢！

   最后，我们去了古纤道旁的太平桥，整座桥形状若龙首朝天、翻腾水面，我们还拍照留念了。

   这次重走“一带一路”上的绍兴古桥活动意义深刻，不仅重走了古桥，还了解了不少知识，真是收获满满啊！

** 篮球初体验

   今年暑假，我迷上了篮球，在满分体育里学习篮球，学习了运球、投篮、交叉步等内容。一分耕耘，满分收获。我在满分体育篮球夏令营里学习篮球。起初，我对篮球很陌生，也有些胆怯。后来，我渐渐熟练了，能随心所欲地操作了。经过十天的训练，我学会了运球、投篮、突破、传球、跑位等动作，手型也很标准，老师还给我写了一段评语表扬我呢！

   有一次，在学投篮时，老师要求要连进五个球才能休息。我们投了很多次，也没投中，我不免有些失望。后来老师指导我们，我们才连进五个球，去休息了。我们还跟别的班级的队员打了一场比赛，虽然最终是我们输了，但由于失败乃成功之母，在后来的比赛中，我们赢过了他们。

   这次学篮球不仅只是学篮球，而且强化了身体的体能。每节课都要做仰卧起坐、俯卧撑、平板支撑等练习。经过这 10 天的锻炼，我身上还长出了几块肌肉呢！这十天，我收获满满，不仅学会了篮球的运球、投球、传球、突破、跑位等基本动作，还增强了体质，学习了篮球的礼仪，真是一举两得。在家里，我还当上了妈妈的小教练呢！

** 读《儒林外史》有感

   “功名富贵无凭据，费尽情绪，总把流光误。浊酒三杯沉醉去，水流花谢知何处。”这是《儒林外史》开头的几句，能够说，这也是整本书的灵魂所在。

   《儒林外史》是我国一部著名的古典长篇讽刺小说，它通过生动的艺术形象，反映了封建社会末期腐朽黑暗的社会现实，批判了八股科举制度，揭露了反对政治的罪恶和虚伪。

   这本书当作了敲门砖，认为“书中自有黄金屋，书中自有千钟粟，书中自有颜如玉。”为了金钱，为了财富，他们能废寝忘食地读书，能够从黑发垂鬓读到白发苍苍。比如“范进中举”里的老童生范进，他五十四岁终于中了举人，却乐极生悲，欢喜成了疯子。

   不过，书里也并不全是迂腐的人，也有像王冕这样的人。王冕从小就家境贫寒而为人放牛，在牛背上他博览群书，画画画得很好，下至平民百姓，上至达官贵人都买他的画。后来朝廷要让他来当官，他却隐居在会稽山，在功名面前不为所动。

   这本书写得非常好，用辛辣的手法写出中国古代统治者的腐朽。希望你也能来看。

** 最忆是杭州

   昨天，是个艳阳高照的日子，妈妈和外婆带着我去了有着“上有天堂，下有苏杭”之称的杭州。

   我们坐着大巴车来到了杭州汽车南站，乘着地铁来到了西湖。我们先到了西湖的湖边，由于风有些大，所以西湖的湖面就动了，被阳光一照，变得银光闪闪。我们在有着“杭州西湖”四个红色大字的石头旁拍照留念。

   之后，我们买了游船的票子，坐上了“龙”头大游船。坐在游船里，里面还有空调，很凉爽。我还走出了游船，来到了甲板上，看着湖面波光粼粼，我想起了苏轼的“欲把西湖比西子，淡妆浓抹总相宜”的诗句，西湖真是太美了！在不知不觉中，我们来到了小瀛洲，在小瀛洲上，我们看到了矗立在湖中的三个潭，即有名的“三潭印月”景点，还看到了浙江先贤祠，里面有介绍浙江的先贤比如黄宗羲、杭世骏、吕留良等。之后，我们乘着游船回到了西湖岸边。

   杭州不仅景色美丽，而且还是名人故里呢！在杭州有郁达夫、龚自珍、沙孟海、蒋经国、胡雪岩、潘天寿、马寅初、司徒雷登、章太炎、苏东坡、钱学森等名人故居。这次我们去的第一个地方就是岳庙。岳飞是南宋抗金名将、著名民族英雄，后被秦桧害于风波亭。我们看完了岳庙，就去了胡雪岩故居。胡雪岩是一位红顶商人，是清朝人。我们参观了胡雪岩的卧室、厨房等。发现胡雪岩的家很大，不愧为红顶商人，还有个地下溶洞，里面又凉快又好玩，旁边亭台楼阁，小桥流水，水里鱼儿快乐地游来游去。

   走出胡雪岩故居，我们来了清河坊，看到了许多小商店，还吃了杭州的特色小吃呢！

   由于时间紧迫，我们依依不舍地离开了杭州，希望下次还能来。

** 坚持就是胜利——读《老人与海》有感

   今年暑假，我读了美国著名作家海明威的小说《老人与海》。我十分佩服小说中老人的意志，他让我懂得了一定要有坚持不懈、勇于搏斗的精神，才能成功。

   小说描写的是一位年近六旬的老人，连续 84 天没有捕到一条鱼，最后在第 85 天，老人捕到了一条大鱼。在海面与它搏斗了三天三夜，虽然明知很难取胜，但仍不放弃，后来成功了。而捕到的这条大马林鱼，却遭来了鲨鱼的抢食，但老人还是没放弃，仍然去跟鲨鱼搏斗，最终突出重围，将大鱼骨架运回了渔港，让其他渔夫佩服不已。

   在捕捉大马林鱼，老人在与它搏斗时左手受伤了，背也痛，又只能吃生鱼。在这样的环境下，恐怕常人都会放弃，而老人没有放弃，而是坚持不懈地斗争了下去，最终胜利了。而在遭受鲨鱼围攻，也正是这种精神才使老人坚持了下去，突出了鲨鱼的重围。

   通过阅读《老人与海》，我懂得了应该积极向上，努力拼搏，坚持不懈，遇到困难要迎难而上，这样才能成功。

   就拿我自己来说吧，我几年前学游泳就碰到很多困难。一开始我怎么也学不会，但是后来我坚持不懈，没有放弃，经过我的努力，终于学会了游泳。

** 走访中国木雕家训馆

   良好的家庭有良好的家风，所谓家风是指家庭人员的风貌和相沿成习的家庭传统。我记得去年冬天，妈妈和外婆带我去金华木雕城，那里有个木雕家训馆，我们进去参观了一下。

   中国木雕家训馆分四个展区，第一个是诗礼作家（中国家训简史）展区，主要展陈从西周到明清时期家训的历史和渊源；第二个是家成业就（修身齐家治国）展区，主要展陈修身、齐家、治国之家训雕版；第三个是风纪世家（东阳本地家训）展区，主要展陈东阳本地的家规家训以及名人故事。最后一个家传户诵（传统家训故事）展区，主要展示以漫画和历史故事为表现形式的古代家规家训。

   在宽敞的“客厅”里，摆放着北宋著名思想家、政治家、军事家、文学家范仲淹的《家训百字铭》：“孝道当竭力，忠勇表丹诚；兄弟互相助，慈悲无过境。勤读圣贤书，尊师如重亲……”短短百字写出了家训的精华，读起来朗朗上口。

   看了范仲淹的家训让我想到了我们家。我们家并没有成文的家风或家训，但却有不成文的规定，那就是“百事孝当先”。比如每次奶奶把爸爸叫去干一些事情，爸爸都是放下手头的活第一时间去先做奶奶吩咐的事情。我也要继承我们家的家训家风，也要做到孝顺长辈。

** 南京二日游

   8 月 11 日，天气晴朗，妈妈带着我去南京游玩。我们乘着高铁，到了南京火车南站，出了车站，我们就开始去玩了，我们去的第一站是总统府。

   到了总统府，映入眼帘的是一幢西洋式的建筑，上面写着“总统府”三个大字。我们进入了总统府，总统府分为东、西、中三条线，中线一开始是天平天国及清朝建筑的遗址和历史介绍。在往后面走，就是大堂了，大堂上方有一块牌匾，上面是孙中山先生亲手写的四个大字“天下为公”。大堂右侧是清代同治年间修建的建筑，里面展示了清代两江总督的介绍，有很多资料。穿过一条长长的走廊就进入了国民政府的办公处，有办公室、卧室、餐厅等。之后走上台阶，就是总统府的“子超楼”了，这是蒋介石办公的地方。游完子超楼，我们就往回走，走出了总统府，去了我们的第二站——江宁织造博物馆。

   江宁织造博物馆主要介绍江宁织造府的历史，江宁织造府是给清朝官员制造衣服的，曹雪芹的祖上也是其中的一员。去完了江宁织造博物馆，我们又去了六朝博物馆，看了六朝古都的一些文物和历史资料。我们还去了梅园新村纪念馆，看到了国共谈判的地方，了解了这段历史。

   之后，傍晚我们去了中华门城堡。中华门城堡是南京的城门，内有 27 个藏兵洞，可藏兵 3000 人，粮食万袋。它是由明代富商捐钱而建成的，非常坚固。

   看完了中华门城堡，我们在老门东吃完了晚饭，就去了夫子庙，看见了秦淮河，去了王导谢安纪念馆，了解了他们的生平事迹。除此之外，我们还去了学宫，拜了孔子。学宫里有大成殿、明德堂、尊经阁等，我们依次参观了。

   第二天上午，我们去了南京博物院，里面有民国馆、历史馆、艺术馆、数字馆等。我们学习了南京的历史，看到了民国时期的街道和场景，了解了南京的历史、文化和艺术。

   下午，我怀着崇敬的心情来到了中山陵，瞻仰了孙中山先生。我们还去了旁边的美龄宫，看到了宋美龄以前住过的地方，了解了宋美龄的生平事迹。这座美龄宫结合西洋建筑，耗时三年，消费了 36 万银元呢。

   傍晚六点多，我们乘着南京的火车回了绍兴，虽然才短短的两天，但我还是了解了南京的历史和文化，希望下次再来。

   #+LATEX: \newpage

* 六年级——笑傲江湖

** 游玩镜湖梦幻水世界

   暑假很快过去一个多月，马上就要开学了，妈妈决定带我去镜湖水世界玩一次水。我听说去镜湖水世界，一口就答应了下来。就这样，妈妈带着我来到镜湖乐园梦幻水世界。

   我们进了水世界的大门，一路往前走，换上了泳装，就到了泳池。首先映入我眼帘的是“爱情风暴潮”。这是一个大水池，有一个舞台，舞台上会有表演节目，而且还能模拟海浪，一会儿波涛汹涌，一会儿水波微动。之后我便去玩了第一个项目——“蓝洋蓝洞”。“蓝洋蓝洞”是国内首次亮相的重量级设备。我和妈妈一起坐在浮筏上，顺着滑道滑到了一个圆盘里，就像玩碰碰车一样，左撞一下，右撞一下，撞了很多下，才掉到圆盘中心的出口孔，到了出口。

   之后，我们又玩了“巨浪来袭”。“巨浪来袭”分为好几个滑道，有很刺激的和中等刺激的，我和妈妈玩了中等的滑道，因为我们都有点怕太刺激。工作人员让我躺在滑垫上，然后把头抱住，就滑下去了。一开始并不怎么刺激，非常平缓，快出口的时候，两边突然喷出很多水，弄得我眼睛里全是水。

   我一边擦眼睛里的水，一边走向另一个项目“海底漩涡”。“海底漩涡”有七条滑道，我们选择了一条中等刺激的滑道，顺着滑道滑下去，马上就到了出口。

   玩完了这个项目，我们又玩了若耶溪漂流、龙吸水、波浪谷等，这些项目都挺好玩的，快到水世界晚上关门的时间了，我们依依不舍地离开了镜湖乐园梦幻水世界，希望明年能再来玩。

** 参加“绍兴市树，我来养护”活动

   上个星期，外婆和妈妈带着我来到嵊州谷来，参加“绍兴市树，我来养护”首届古香榧树主题认养现场踏勘活动。我们去的第一个地方是香榧文化博物馆。香榧文化博物馆里面陈列着很多用香榧做的工具，有扫把、犁、石磨等，还有很多展板，上面介绍了有关香榧的知识和故事，非常有意义。

   看完香榧文化博物馆，我们就去香榧森林公园，看里面的“香榧王”。这棵香榧树有 1300 多岁了，树干非常粗壮，要九个大人才能围着抱起来。它像一把撑开的大伞，把我们罩在其中，风吹来，我感到一阵阵清凉。绍兴电视台“真话难听”的主持人和“师母来哉”里的师母在现场进行了采访，我也被采访到了呢！站在香榧王旁，清新的空气使我变得神清气爽，这沁人心脾的空气是城里闻不到的。听组织者说香榧树还被称为长寿树呢，也是绍兴的市树。接着就是香榧认养活动了。有两个单位认养了两棵香榧树。我觉得我们应该保护生态环境，让天空变得更加美好。

   接着我们去走了古道，走在古道旁，香榧树连山成片，姿态万千。走在香榧树边，我认真观察一棵香榧树，树上已结了小拇指般的香榧果实，沉甸甸的果实压弯了树枝。香榧的果实是青色的，跟我们吃的香榧颜色不一样。一颗颗果实像一块块绿宝石。

   走完了古道，我们在旁边吃了饭，就去看了林彪军事防空洞，还看了竹溪村的旗杆台门，这是省内规模最大的台门，有 66 间房子，占地面积约 5000 平方米。该台门建于道光年间，保存的还很完整。

   看完了旗杆台门，我们就返程了。这次来到嵊州参加活动，真是收获满满啊！

   #+LATEX: \vspace*{\baselineskip}

   *绿水青山　榧树飘香（修改版）*[fn:19]

   沿着悠长的山路，我们一群人来到了香榧的故乡——嵊州谷来，参加“绍兴市树，我来养护”首届香榧主题活动。

   这里香榧树连山成片，姿态万千。我第一次看到了真正的香榧树。蓝天白云，群山环绕，绿水青山，榧树飘香，呼吸着新鲜的空气，顿时感到神清气爽。

   九月是丰收的季节，我们沿着古道，踏着石板路，拾阶而上。古道旁，往山上走。两边的香榧树上挂满了沉甸甸的果实，像是在向我们打招呼。不一会儿，我们到了香榧森林公园，里面有很多香榧树，还有一棵有着 1300 多年树龄的“香榧王”，它见证了绍兴的沧桑历史。遥看香榧王，它像一把撑开的绿伞，也像一位慈眉善目的老人凝望着前方。岁月幽幽，唯有香榧王依然如旧。

   我走到“香榧王”面前，它的树干非常粗壮，要九个大人才能围抱起来。香榧的鲜果是绿色的，跟我们平常吃的香榧很不一样。一颗颗果实像一块块绿宝石。香榧树的叶子很特殊，它的叶子从茎开始就是分开的，由一丝纤细而又坚硬的叶片组成，犹如许多枚绿色的绣花针。一阵风吹来，我感到一阵阵清凉。站在香榧王旁，这沁人心脾的空气是城里闻不到的。

   听领队介绍，香榧树又称为长寿树、子孙树、摇钱树等，香榧营养丰富，还能做药品呢！而且香榧树要在海拔 300 米以上的地方种植才会结果。香榧树也是绍兴的市树。两个单位认养了两棵香榧树，给树施了有机肥。领队说：“我们应该保护生态环境，让天空变得更蓝，让绿水青山变成金山银山！”

   听着领队的介绍，我的眼前仿佛看到了大家保护生态环境下的绿色美丽家园，多么令人向往。

   这次来到嵊州参加户外健身活动，我近距离地接触香榧树，了解了关于香榧的不少知识，更懂得了保护生态环境的重要性，真是收获满满啊！

** 体验无人机

   昨天，我们一家人去了浙江杭一电器有限公司参加无人机培训。无人机是属于专业性蛮强的机械设备，没有专业指导要入门是很难操作的。我以前只看过，听过，从来没有操作过呢！我怀着激动的心情，参加这次活动。

   走进杭一电器有限公司，就有一架无人机的模型，远处还有好几只羊。等所有人都到齐了，我们就进了一间会议室，听老师介绍无人机的法律、法规。老师说现在有不少人开无人机不遵守规则，导致不少机场航班停止，所以现在无人机驾驶需要驾照。之后老师又简单介绍了无人机的构造。接着，我们就去试飞无人机了。

   我们先分好组，工作人员展示了无人机的功能，再教我们怎么操作。看完了工作人员的演示，我也迫不及待地试了一下。我手握遥控器，飞机一会儿上升，一会儿下降，一会儿左转右转。除了拍视频，也能拍照，我觉得很好玩。我操作了一会儿，觉得越来越得心应手。看到飞机再天空中翱翔，我觉得会开无人机真好！

   这次参观杭一电器有限公司，不仅知道了无人机地法律法规，还试飞了无人机，真是收获满满！

** 王化溪戏水

   上个星期六，是个阳光明媚、适合出游的好日子，我们一家人去平水王化溪玩。

   大概有 40 分钟的车程，我们来到了王化溪。那里的溪水非常清澈，像一面明镜，能让我们看见溪中的小鱼和小虾。我往溪水中一看，有好几个人在划皮划艇，我和弟弟一看，发现皮划艇看起来挺好玩的，我们就付了钱，下去划皮划艇了。

   我、表弟、姑爹三个人一起下去划皮划艇，我和表弟一人一只桨，姑爹拿着一只篙。但是我和表弟并不会划船，一会儿倒着划，一会儿乱划，所以船并没有往前动，一直在转圈圈。后来，姑爹教我们要往后划，要等桨进入水中再划，而且两人基本上速度要一致。有了这个正确的方法，船就动起来了，往前开了。但是由于我们并不会划，再加上过了桥，水的阻力越来越大，马上就又划不动了，在原地转圈。后来我们又划了一会儿，之后时间到了，我们就划回去了。

   划完了皮划艇，我们就去捉鱼和摸石头了。我们捉了半天，也没抓到一条鱼，倒是捡到了不少石子。捡了几块石头后，我们就开始玩水了。清凉的溪水冲着我的脚，我感到一阵清凉，非常舒服。我和表弟互相泼起水来，非常好玩。王化溪的溪水非常清澈、也非常凉快。我们玩了一会儿水，就上岸了。夕阳西下，我们依依不舍地离开了王化溪。

   虽然这次并没有玩太长时间，但是王化溪非常好玩，除了清澈的溪水，还有古老的香樟树、两百多年历史的万安桥，一边是崭新的农村新貌，一边是满地的庄稼，希望下次还能来。

** 国庆一日游

   十月二日，天气很好，妈妈带我去梦享城的海洋馆玩。一进入海洋馆，我就看见了很多鱼，有七星飞刀，还有血鹦鹉、电鳗等。这些都是来自亚马逊热带雨林的各种鱼类。看完了鱼类，我们就去水母馆，看见无数的水母在美轮美奂的灯光下翩翩起舞。我细看一个水母，发现水母的外圈在收缩，内圈像一朵花，但是不动。

   看完了水母馆，我们就去看海豹表演了。我观察海豹，发现海豹的皮是棕色的，嘴巴旁有着胡须，胡须是白色的，海豹有两只前爪，抖动前爪像是在向我们打招呼。表演开始了，饲养员先让海豹向我们打招呼，之后就让海豹做一些表演动作，先是让海豹顶球，海豹在水中顶着球，不让球掉下来，但最后球还是掉了下来。顶完了球，海豹又表演了跳杆顶球、套圈、水中跳芭蕾。通过观看这次表演，我觉得动物也是很聪明的，很有灵性，只要一个手势就懂了，非常聪明。

   之后，我又去看了人鲨喂食表演，看见潜水员在水中自由地游来游去，不时给身边的鲨鱼喂食，旁边还有海龟和电鳐，非常地亲密无间。

   看完这两场表演，我们又看了美人鱼表演，还领到了一只小乌龟。快乐的时光总是短暂的，快中午了，我们依依不舍地离开了海洋馆。

** 为中华崛起而读书

   我国有一位总理，他少年时就有远大的志向，勤奋好学、热爱祖国，最终成为一代好总理，成了人民的好总理，成为我们的好榜样。

   他就是我们敬爱的周恩来总理，他的故事流传至今，值得我们学习。周恩来在他上学的时候，校长给大家上课，问同学们：“你们为什么读书？”有的人说为做官而读书，有的人说为父母而读书，有的人说为挣钱而读书……当问到周恩来的时候，他清晰有力地回答：“为中华崛起而读书！”周恩来不仅如此说，也是如此做的。他为国为民，为新中国的繁荣富强做出了极大的贡献。

   我们应该学习周恩来的精神，从小要有远大的志向，并且要付诸实践，不能纸上谈兵，而要脚踏实地。

   少年强则国强，少年富则国富。我们是祖国的栋梁，我们一定为建设祖国贡献自己的一份力量，把祖国建设得更繁荣、富强、昌盛、美好！愿这盛世如总理所愿！

** 观鸟不关鸟

   这个星期五，妈妈带我去参加绍兴野鸟会组织的讲座——观鸟不关鸟。

   野鸟会秘书长黄老师介绍观鸟是对野生状态下观察、鉴别鸟的种类、数量和行为，要做到不破坏鸟儿的环境，不骚扰鸟儿的生活。之后便放映了一些鸟的图片。其中，黄老师讲到上虞有一所学校因为有一只乌鸫飞进了学校，筑起了巢，该学校视之为珍品，把它保护了起来。这种行为值得我们学习。

   黄老师还介绍了一些鸟的习性和特点。我听得津津有味，非常入迷。黄老师还播放了一段小视频，视频中，两只麻雀在打架，其他麻雀在旁边观看，感觉像一群“吃瓜群众”，我觉得蛮好玩的。黄老师介绍的这么多鸟中，我最喜欢的是大山雀。大山雀的体型很小，很爱洗澡。基本上体型小的鸟都爱洗澡。黄老师还介绍了凤头鹰，凤头鹰专门爱捕捉松鼠，但是成功率非常低。黄老师说他曾在府山上发现过凤头鹰，看到过凤头鹰捕捉松鼠，但都失败了。因为松鼠有茂盛的枝叶作掩护，还会活蹦乱跳，所以成功率很低。

   除了观鸟，还有一种叫“关鸟”的行为，关鸟是把鸟关在笼子里，为了拍照，破坏鸟儿的生态环境，我们不能做这样的事。

   观鸟可以培养观察力、专注力、辨别力，就让我们一起爱鸟，观鸟吧！

** 炎炎夏日送清凉

   今年暑假，我带领我的小队参加由越城区共青团委、绍兴 E 网、00 后小义工组织的“爱心凉茶亭”活动。

   那天下午，天气格外炎热，但却无法抵挡我那颗助人为乐的火热之心。我早早来到了那里，穿上了志愿者的服装，兴高采烈的来到服务现场，这已经是我第四次参加这类活动了。组织者先向我们介绍了怎么装水等内容。听完后，我就开始工作了。因为炎炎夏日，所以行人很少，但是我们始终坚持在自己的岗位上，一有行人过来，我们就冲过去给他们送水。他们也会鼓励我们，说“谢谢你们”之类的话，使我感到温暖。

   其中有一位环卫工人走了过来，我一看环卫工人来了，就迫不及待地灌好了水，迎了上去，端给了环卫工人。他拿着水杯，把水一饮而尽，满是沧桑疲惫的脸绽开了花一样的笑容。

   还有一位老太太抱着孩子，我们主动让她们坐在大棚下的凳子上。她们是等公交车的，我们给她送了水。那个小孩有点中暑，我们给她送了药品。老太太说：“你们这群孩子真好！”听到这句话，我感觉我们的活动很值得。

   每每听到大家对我们的表演，我感动很温暖。我们应该给予别人一些帮助，给别人温暖，也能得到别人的关爱。于是，我感到天更蔚蓝，水更清澈，树更绿。

** 拔牙记

   我们人的一生都会有过拔牙的经历，就让我给你介绍一下吧！

   今天，我突然觉得有一颗牙齿很疼，我照了一下镜子，发现这颗牙齿已经要掉了。我轻轻一碰，牙齿就轻轻地摇晃。我一看原来是一颗乳牙，白白的乳牙像白胖的小孩子。

   乳牙是人的第一套牙，乳牙经过一段时间就会脱落，变成恒牙。总共有 24 颗乳牙都会换成恒牙。

   我晚上吃饭的时候，不小心用牙齿咬到菜，就感觉非常痛。所以我决定把乳牙拔下来，但因为晚上，医院关门了，所以只能在家自己拔。

   我拿好水杯，装满了水，拿了几张纸，我先用舌头舔着牙根，想把牙齿舔下来，但是舔了半天，并没有什么效果。我只好又用牙齿咬着，过了很长时间，牙齿被我舔着只剩一点还在口腔里，牙齿摇摇欲坠，像是要掉下来了，让人感到心慌。我鼓起勇气，像武侠片里的英雄，用手把牙齿拔了一下，但是并没有拔出来。我又试了一次，终于把牙齿拔了出来。之后，我又喝了点水，漱了口，看着被拔的牙齿，我觉得这颗牙齿，完成了它的光荣使命。

   我有这样的拔牙经历，但是这也是成长的烦恼，一颗乳牙的掉落意味着一颗恒牙的诞生，成长就是这样。

** 游兜率天宫

   今天，天气晴朗，阳光明媚，是个出游的好日子，妈妈和外婆带着我去大香林景区去玩，我一口答应了下来。

   我们乘着公交车，到达了景区，我们先去了大香林景区，看到一棵中国桂花王，和很多桂花树。我们去了月老祠、花神庙等。

   去完大香林，我们就乘着观光车到达了兜率天宫，我们就乘着观光车到达了兜率天宫。一到兜率天宫，映入眼帘，最上面有一朵“莲花”，两边有两尊佛像，非常宏伟壮观。听说这朵“莲花”堪称为世界之最。一走楼梯，我就听见哗哗的水声，我顺着楼梯往上走，原来是上面有一个小口，水顺势流下来。顺着楼梯往上走，每一层都有一个小的景点，比如石雕博物馆等。我往上看，又是一层又一层的楼梯，我只好不顾一切地往上走，总算走到了第七层，也就是顶层。顶层一进去就是十二生肖喷水池，铜雕的十二生肖喷着水，栩栩如生。之后，我就看见了这朵世界之最的莲花，这朵“莲花”是金色的，有 48 朵花瓣，直径 56.7 米，高 16 米的紫金莲花。还有一尊高大的佛像，是世界之最。观景平台下有一尊三十八米的室内佛像，这是世界第一高的室内佛像。如果在五楼看，必须仰起头才能看到高大的佛像。站在顶楼，整个绍兴的风景都映入眼帘，巍巍稽山，雄伟龙华寺，微风拂过，我感到神清气爽。游玩了兜率天宫，旅途也该结束了。我们去了最后一站——龙华寺。我们在龙华寺拜了佛，就回家了。

   大香林景区非常好玩，希望你也能来玩。

** 节水建议书

   #+LATEX: \noindent
   尊敬的校长：

   我是树人小学一名六年级学生，在这所美丽的学校学习了很长时间。我的校园景色优美，有着美丽的花坛，还有一栋栋高大的教学楼，但仔细察看，就会有美中不足之处。

   校园中的有些地方在漏水，虽然并不怎么严重，但时间一长，也是在浪费水资源。不少同学洗手时水龙头开到最大，很浪费水资源。一些同学洗完水不关水龙头，更浪费水。

   我们都知道，水是人类生活的重要资源，一会儿不喝水，就会很难受，可见水的重要性。一直以来，大家认为水是用之不尽、取之不完的。但是，世界上水资源是有限的，而中国的水资源更是缺乏。不少地区严重缺水，很多居民都喝不了多少水。校园之所以存在不少浪费水的地方，我觉得是同学们不了解水的宝贵性。

   节约用水不是一句口号、一句空话，要有实际行动，要实际去做，时时刻刻注意节约用水。作为本校一名学生，我提出以下建议：

   1、在校园每个用水地方，贴上一些关于节约用水的标语。这样用水时就能看到了，提醒大家节约用水。

   2、每班召开几次节约水的班队课活动，让每名同学都能发表自己的意见。

   3、在每个楼道口安排人员督促、管理，让大家有节水的想法。

   4、在每个星期一开展节水活动，让大家知道水的宝贵性。

   5、给节水好的班级鼓励，颁发奖状。

   节约用水不是一句空话，更不是一句口号。让全校师生一起节约用水吧！一起行动吧！

   　　　　　　　　　　　　　　　　　　树人小学东校区六年级学生

   　　　　　　　　　　　　　　　　　　2017 年 11 月 7 日

** 博学的表弟

   我有一个表弟，他跟我年级一样，但比我小一岁，他是属狗的，我是属鸡的。虽然有个成语叫“鸡犬不宁”，但我们却相处很好，很安宁。

   我的表弟很博学，知道很多东西，尤其是许多自然科学类的东西。有一次，我们去名人广场一起玩。到了名人广场，看到一个水塘，表弟说：“水塘里有水葫芦、水草，可以摘一点回去，放在金鱼缸里。”我很惊异地说：“你怎么知道这些？”他说：“这有什么了不起。我平时经常看到这一类书的。书上都有，你也可以去看。”他又指向一点绿绿的圆圆的像叶子一样的东西，说：“这是浮萍，是浮在水上。”我看着他感觉我的知识，实在是太少了，跟他比起来，就像《少年闰土》中的鲁迅和闰土。

   还有一次，我们一起去月华山养心谷游玩回来。在车上的时候，他讲了许多科学自然方面的事，比如宇宙的形成、地质的变化，让我感到他知识的丰富。他在这方面已经完全超越了我。他讲的话我简直听所未听，闻所未闻，从来不知道。

   这就是我的表弟，一个博学的人。

** 上虞湿地观鸟

   这个星期六，妈妈带着我去上虞湿地参观野鸟会组织的观鸟活动。

   我们来到了观鸟的地方，在一片草地上看到了白鹭，还看到了在水中直立的苍鹭和反嘴鹬。我还在空中看到了好几只鸬鹚。之后，我们去了第二个观鸟点，看见了白腹鹞和白尾鹞在打架。这两只都是猛禽，国家二级保护动物，白腹鹞打架掉了好几根羽毛，后来又来了一只鹊鹞，打了一会儿架就飞走了。白腹鹞非常好看，眼睛中等大小，腹部是白色的，翅膀很大，而且是灰色的。

   之后，我们去了最后一个观鸟点——水边。在去的途中，我们看到了有着尖尖黄嘴和黑色羽毛的鸬鹚在天空中飞翔。我们到了河边，用望远镜和单筒望远镜从河里看到了无数只野鸭，密密麻麻，非常多。看完了野鸭，活动就结束了，这时，我看见旁边的工地上有很多人在挖掉泥土，破坏环境，听说要在这里造工厂。正是这样的行为使鸟的栖息地被破坏，导致了鸟类的大量死亡，破坏了鸟的生态平衡。

   之后，我们拍了照，作了纪念。通过这次活动，我认为我们应该保护环境，让鸟儿有更多的栖息地，保护环境人人有责。

** 缤纷鸟世界

   这个星期五，妈妈带着我参加绍兴野鸟会组织的菜鸟成长营的最后一次室内课程，听野鸟会会长绍兴文理学院梁教授来给我们讲“缤纷鸟世界”。

   梁老师先跟我们讲了鸟从哪里来。他说全世界有近 1 万种鸟，根据进化论理论，鸟是从恐龙中的“飞龙”进化而来。动物分为有脊椎、无脊椎两种。无脊椎动物体型小，但很多。世界上现存着三个鸟类总目，分别是平胸总目、突胸总目、企鹅总目。梁老师还说，有不少不能的鸟，比如在青藏有一种叫蓑羽鹤的鸟，每到冬天，都要飞跃喜马拉雅山，还有帝企鹅，它最深能下潜到 550 米深度，连潜水艇的深度也不过 600 米。还有能挖地洞的白腹腰雀，能像建筑师一样，在斜面上为洞的翠鸟，在花间吃蜜的红头长尾山雀、伪装者虎斑地鸫、漂亮的红嘴蓝鹊、环颈雉等。而为什么有这么多鸟能生存下去是因为物种的多样性、食物链和丛林法则。鸟儿中还有清道夫——秃鹫、捉虫能手——戴胜、互惠型鸟——牛背鹭、家八哥、城市鸟——家麻雀等。还有因为人类而改变的鸟儿，比如滇池的红嘴鸥、松花江上的赤麻鸭、绿头鸭等。还有着美丽的白颊噪鹛、叉尾太阳鸟、橙腹叶鹎，还有乌鸦叼蛋、温情的黑水鸡。梁老师最后说，实际人类是鸟类最大的天敌，现在气候变暖，大量适合鸟类的栖息地荒芜，而且我们人类也遭到气候变暖、海平面上升、冰川融化、土地沙漠化等危机。

   听了这次讲座，我学习了有关鸟类的各种知识，并深感保护环境的重要性。我们应该用双手保护我们自己美好的家园。

** 巴西龟

   在十月份的时候，我在花鸟市场上买了一只巴西龟。

   以前我看它都市是非常活跃的，我一放食物它就来吃。而到了现在，这只乌龟一动不动，四肢僵硬，给它喂食物，也不吃，像是死了一样，缩着头，真像缩头乌龟。哦，忘告诉你这只乌龟的外貌了。这只乌龟，它的背是园的，也是绿色的，背上有浅白的纹理。四肢都是短短的，粗粗的，头也是又小又绿。这只巴西龟体型很小，且并不爱吃食物，所以生长得很慢。都两个月了基本上没有长大。听花鸟市场里养过巴西龟的人说，这么小的乌龟要养到可以吃，大概要 5-10 年。多么漫长的时间啊！

   有一次，我拿龟粮喂乌龟，它并没有吃。我喂了好几次都不吃。后来我气得走开了，乌龟却吃了。此外，乌龟还非常不爱动，始终窝在家里不动，缩着头，真像缩头乌龟。后来我才知道，他们在冬眠。

   这就是我的巴西龟，你喜欢吗？

** 看《装在口袋里的爸爸》读后感

   杜甫曾说过：读书破万卷，下笔如有神。刘向也曾说过：书犹药也，善读之，可以医愚。现代的高尔基也说过：书籍是人类进步的阶梯。从古至今，无数名人都曾说过书的好处，每个人都有一本或一套自己最喜欢的书。我也不例外，我最喜欢的书是《装在口袋里的爸爸》。这套书总共有 24 本，作者是杨鹏。

   这套书主要讲的是原来有着 1 米 8 身高的杨歌爸爸经常被杨歌妈妈骂之后越变越小，最后变成了拇指小人儿，成了杨歌的“教育部长”。因为杨歌爸爸闲着没事干，就发明了许许多多稀奇古怪的东西，比如聪明饭、时间魔表、摇钱树等。其中我最喜欢的是《时间魔表》这本书。该书讲述了杨歌爸爸发明了时间魔表，可以借用自己或别人的时间，发送一系列不可思议的事，杨歌借了很多时间用来学习，去救助火灾，给死去的人变活等。总之，杨歌帮助了大家，但是后来由于时间魔表的时间是要以一换十的，杨歌就变成了七八十岁的老人。后来杨歌又变回了跟原来一样，但他不轻易使用时间魔表了，而是告诉市长让时间魔表推广，造福了整个城市。但时间魔表被匪徒“猴子”利用，使全国陷入危机，最后杨歌最终胜利里。

   这本书非常好看，有着无穷无尽的想象力，幽默风趣地写出了杨歌的生活。歌德曾说过读一本好书，就像是与高尚的人谈话。我觉得我们应该趁现在多读书，读好书，做一个书香少年。

** 看美食书有感

   我的爸爸很会烧菜，但有些不合我口味。所以妈妈就去图书馆借了一大堆美食的书。

   我也时常看这些书，通过阅读这些书，我知道了我们中国的食文化有数千年的历史文化，是中华文化的一颗明珠。中国烹饪技巧以其技艺精湛、花样品种繁多、色香味形俱绝而驰誉世界。我国自古就有川、鲁、粤、苏、湘、浙、闽、徽等八大菜系。

   不管我看哪一本书，里面都有既美味，而且还有好听的名字的各种美食。虽然只是一幅幅图片，但是却是生动地展现在我的面前。看着这些图片，我垂涎三尺。

   其中我最爱吃的就是辣味脆皮炸鸡了。这个菜虽然很简单，但却非常好吃，比家常菜好吃多了。总之，每一种菜我都觉得非常好吃。

   希望我们学校的厨师也能看这些美食书，烧出美味的佳肴。

** 表弟离家出走

   看到这个题目，你会想到什么呢？离家出走是离开家走掉吗？对，事情是这样的。

   我有一个表弟，他的名字叫任鉴琛。他的父母元旦在上班，所以他就来他的外婆家做作业。今天我来我的奶奶家过节，就是他的外婆家。到了奶奶家，我就去做作业了，做完作业后大家一起吃午饭。饭菜非常好吃看，吃完饭之后本来是准备去学校附近逛逛的，但是我突然发现表弟不见了。一开始我们并没有在意，以为他只不过是去下面玩玩而已。但过了好长时间，他都没有上来，我就追了下去。但是他拼命地跑，我没追上。但是最终被我爸爸追上带了回去。因为我的表弟经常躲来躲去，我们习以为常了。之后我和爸爸就回到了自己家。不一会儿，奶奶打电话给爸爸，说表弟不见了，不知道跑到哪里去了。我和爸爸连忙赶到奶奶家。但是不知道表弟在哪儿，所以无济于事。全家人都出动了，纷纷去找他，给他打电话，他也不接。后来，姑姑打来电话说：“他要去他的奶奶家，现在已经在中兴大桥上了。现在说等会儿来接，让他在他的外婆家等。”奶奶听完后，焦急的神情便一扫而光。但是我们等了好久才见到表弟的身影。之后，我们就回家了。

   通过这件事，我认识到做什么事情都不能随心所欲，由着自己的性子乱来，否则后果不堪设想。

** 我和狗交上了朋友

   大概是三年前吧，我的表弟在花鸟市场上买了一条狗，取名叫“小 A”。

   由于我一开始很怕狗，有一次，我表弟去我奶奶家，便把狗牵了过来。狗一叫，我便以为它要咬我，便拼了命地跑。小 A 便追了上来，跑了一会，我便跑不动了。眼看狗要追上我的时候，我的表弟用绳子牵住了狗，危机解除了，但我再也不愿意接触这只狗了。之后玩好，我们便去吃饭了。

   吃饭的时候，我在门里，小 A 在门外，我非常惊慌。但后来我的表弟跟我说：“你给它吃几根骨头，它就会跟你好的。”我半信半疑，万一狗把我咬了怎么办？表弟说：“没关系，它不会咬你的。”我将信将疑，便拿了几根肉骨头，走出了门。我慢慢地走到小 A 面前，扔过去一根肉骨头。小 A 在那块骨头上舔了又舔，我长出了一口气，我的戒心松散了，我又拿了几块肉扔给小 A，最后我都能亲手喂它了。就这样，我已经不怕它了。我跟表弟一起跟小 A 玩了。我摸摸小 A 的身体，它也会来舔我的脚，放佛我是它的第二主人呢了。从此，我不怕任何狗了，我和狗交上了朋友。

** 素描初体验

   最近，妈妈给我报了一个素描体验班，我和我的表弟一起去学。第一次课时，老师就开始讲了素描的知识。素描是运用单色线条的排列组合来表现物体造型、色调和明暗效果的一种绘画形式。老师说：“今天这节课我们来排线。”之后，老师讲了一些关于排线的技巧和方法。之后，课上完了，老师说：“大家回去画一张排线的图画，下次课要检查。”

   上完第一次课后，我感觉非常没意思，便有了不想学的想法。但是妈妈说，虽然这是公益课程，可以不去，但是如果对任何学习抱有这样的态度，是学不好任何东西的。我听了妈妈的话，又有了信心，决定继续学下去。

   之后，我便坚持学了下来，每一节课从不间断，认真听讲。功夫不负有心人，经过素描体验后，我的绘画技巧也变得越来越好了。

   虽然体验课已经结束了，学习的任务也很重了，但我仍想把素描学下去。

** 科技馆里看春晚

   上个星期，姑姑带着我和表弟去参加科技馆组织的科技春晚。到了时间，我们进入舞台，发现舞台大，能坐千余人。由于去得比较晚，前面都坐满了，我们只能坐在后排。前排的人举起荧光棒，形成了一片彩色的海洋，好不壮观。

   表演开始了，第一个是大型歌舞剧——《向未来问好》。第二个节目则是歌曲联唱《新年喜乐会》。这两个是开头的节目，之后便是科学表演了。第一个科学表演是特斯拉线圈，唱起歌，特斯拉线圈就会发电。之后，是三个嵊州市的小孩子表演了五种科学表演。我想到他们这么小，却能表演科学，自愧不如。后来有机器人的创意舞蹈以及科普剧《杯酒释“英雄”》，这科普剧生动地讲述了历史中的科学。这么多表演中，我觉得最好看的就是“神勇警犬”。神勇警犬是柯桥警察大队的一员，它们在舞台上给我们表演了“搜索毒品”，让我们知道了狗的聪明与机智。

   由于时间比较迟了，我们依依不舍地离开了晚会现场。这次科技春晚非常好看，希望我下次还能有机会欣赏。

** 府山观鸟

   寒假中的一个下午，妈妈带着我参加了绍兴野鸟会组织的府山观鸟活动。

   那天，天气晴朗，阳光明媚，是出游的好日子。府山上还有一些积雪，树叶山闪着一丝丝金光，寒气中透着意一丝春的气息。

   我们来到了集合的地点，排好了队。领队的绍兴野鸟会秘书长黄老师给我们每个人都发了一个望远镜，我们戴上望远镜，一个个看起来像专业的观鸟人士。

   我们迎着寒风向山上走去。我们先看到了白头鹎。我仔细观察它，发现白头鹎的头是白色的，头上有一簇黑色的毛，而身体是青褐色的，羽毛则是灰色的。我们再往前走，看到了远东山雀。远东山雀的头被蓝色包住，头上只有小小的一块白色的地方。远东山雀与大山雀很像，有很多人都会认错。之后，我们又往前走，看见了很多只珠颈斑鸠，它的腹部是红色的，头部非常得小，嘴巴很尖，在空中飞行很快。叫声非常得清脆、动听。之后，我们又看到了黑鹎。黑鹎顾名思义就是黑色的。的确，黑鹎全身都是黑色的，但是头部却是白的，嘴巴是红的。之后，我们又看到了栗背短脚鹎，栗背短脚鹎的背是橙灰色，腹部是白的。除此之外，我们还看到了很多种鸟。如在树上生活的强脚树莺，有美丽漂亮红胁蓝尾鸲，叫声响亮的白腹鸫和竖立枝头的灰背鸫。

   最后我们还看见了不常见的牛头伯劳和锡嘴雀。这次来府山看见了这么多鸟，既丰富了我的知识，还爬了山，真是一举两得。这次活动真是意义非凡啊！

** 绍兴过年风俗

   现在春节日渐临近，到处洋溢着过年的气氛。在绍兴，过了腊八，绍兴就进入了过年模式。掸尘、舂年糕、裹棕子、送灶神、贴春联等等，最核心的活动当数祝福了。

   绍兴祝福，俗称“请大菩萨”，起源于宋元时期，至今仍广泛盛行于绍兴民间，每年农历廿三夜送灶司菩萨上天后，除夕之前，每户人家总要选择一个祝福的吉日，来举行一年中最为隆重的大祭典，祈求来年幸福、风调雨顺。

   除了我们绍兴，诸暨也有在积极的习俗——草塔抖狮。草塔抖狮，在元宵踩街等活动中，经常能看到它的风采，这是草塔前店村特有的一种将民间舞蹈与牵线技巧相结合的民间表演艺术，始于明末清初，至今已有上百年的历史。除了草塔抖狮，诸暨市陈宅镇陈宅村的民间艺人走街串巷，为邻里乡亲表演独特的民间艺术—擂马。擂马是陈宅村的传统艺术形式，有 200 多年的历史。民间艺人用绸布和竹子等扎成马及骑马的人物，并在底部安放木架和轮子，在节庆之时配以锣鼓队表演，为人们送去欢乐和祝福。

   新昌也有自己的习俗，那就是舞板凳龙。这是新昌大市聚后梁村的一项传统的群众自发性庆祝活动，在每年开春以舞“板凳龙”这种独特的方式，来祈求一年的风调雨顺、幸福安康。

   除了习俗，绍兴还有一些食物也很有年的特色，比如新昌打年糕。在农村一般腊月左右就开始热热闹闹地打年糕了，小作坊里的热气氤氲，香气扑鼻，打年糕的工人遵循着古老的手法：磨粉、蒸米、捣米、切条……一道道的工序承载着记忆中的年味！

   每到腊月，安昌这个小小的水乡古镇便会热闹非凡，狭长的廊棚里挂满了鱼干、酱鸭、香肠；各家各户都忙着打年糕、串腊肠、晒鱼干……

   “年”就这么有声、有色、有味儿地开始过了。

** 读《金戈铁马——刘宋帝国兴亡录》有感

   斜阳春树，寻常巷陌，人道寄奴曾往。想当年，金戈铁马，气吞万里如虎……这就是对南北朝刘宋帝国六十四年的概括。

   寒假里，我读了很多书，其中我觉得最好看的是描写南北朝刘宋帝国年间的书——《金戈铁马——刘宋帝国兴亡录》。

   这本书生动、有趣，非常好看，是一本好书。这本书生动地讲述了存在时间只有六十多年的刘宋王朝。虽然刘宋王朝只存在了六十多年，但却是非常的精彩和惊心动魄。刘裕的两次北伐以及刘义隆的元嘉之治和北伐草草和刘宋皇族为了至高权力而进行的骨肉残杀……庙堂之上，刀光剑影、疆场之上，万马奔腾，为后人谱写了一幅波澜壮阔的历史画卷。

   刘宋是南北朝中南朝第一个朝代，开工皇帝姓刘名裕，小名“寄奴”。我对他的印象非常深刻，可以说他是南北朝中的一位英雄。想当年，刘裕也曾“金戈铁马，气吞万里如虎”。之后，刘裕大儿子和二儿子相继被赶下了皇帝的宝座，改由刘裕的第三子刘义隆继位。他当时做了两件惊天动地的事情，一是“元嘉之治”，二是“元嘉北伐”。之后有刘骏、刘子业、刘彧、刘昱、刘凖等皇帝，但这些都不怎么出名。

   通过阅读这本书，我了解了南北朝南朝第一个朝代刘宋帝国的兴亡。这本书图文并茂，描写的人物栩栩如生，是一本好书。让我们多读书，多读好书吧！

** 跟刘备做朋友

   每一个人都会有不少朋友，有的朋友可以给予你物资上的帮助，有的朋友能让你学到本领，还有的朋友能让人的心情非常愉快。

   我也想有一个朋友，大家对他一定又熟悉又陌生。他就是——刘备。最近我在听“大话三国之刘备篇”。

   刘备出生在公元 161 年，也就是东汉末年。他的祖上是中山靖王，他是汉室宗亲。他从十岁就开始卖草鞋，但是他在卖草鞋的时候也胸有大志，遇到困难永不放弃。他曾拜中郎将卢植为师。后来，他在桃园与关羽、张飞结为异姓兄弟。他在他的同学公孙瓒手下，与十八路诸侯共同讨伐董卓。消灭董卓之后，他离开公孙瓒独立。之后，徐州牧陶谦被曹操进攻，刘备赶去支援，陶谦把徐州牧让给了刘备。之后，吕布又把刘备的地盘给抢了。刘备投靠了曹操，曾与曹操煮酒论英雄，后来投奔袁绍。之后，又投奔刘表。后来，刘表病死，荆州被曹操夺取，刘备撤离，十余万百姓与他一起，由此可见刘备的名声很好，很仁义。后来与孙权联手在赤壁大败曹操。最后，刘备入川，消灭刘璋，之后与曹操争夺汉中，以刘备的胜利而终，在汉中称帝，形成了天下三足鼎立的场面，成就了一方的霸业。

   刘备有很多的优点，他有着百折不饶的精神。他虽然一开始没钱、没人、没地盘，但他坚持实现自己的理想。而且刘备非常仁义，有很多百姓拥护他，比如曹操攻荆州的时候，很多百姓都与他一起走，足足有十余万人。而且刘备还极有识人之才。他手下的五虎上将：关羽、张飞、赵云、黄忠、马超等。还有诸葛亮、庞统、法正等。还有陈到、魏延、马岱、杨仪等。

   这就是刘备，一个三国的英雄，我想跟他做朋友！

** 读《三国演义》有感

   《三国演义》是明代罗贯中所写的历史小说。它讲述了东汉末年时期到三国一统归晋的事情。

   首先，我看到的是“滚滚长江东逝水，浪花淘尽英雄……”这首《临江仙》。书中有着无数的英雄，这些英雄在乱世中群雄并起，最终三国鼎立，之后三分天下皆归于晋。

   先是汉室衰弱，董卓进京，十八路诸侯共讨董卓。之后曹操挟天子以令诸侯。曹操先灭了陶谦，之后又击败吕布，之后，斩杀吕布，又灭张绣。之后，在官渡大败袁绍，后来，统一黄河以北，灭刘表。在西凉灭马腾、韩遂、张鲁，一时间成了霸主。但是在赤壁被孙刘联军大败。虽然失败了，但曹操还是三国里最强的一个。曹操手下还有张辽、乐禁、于禁等五子良将，还有夏侯惇、夏侯渊、曹仁、曹洪等魏八虎将。不仅如此，还有典韦、许褚两员猛将。可以说，曹操是天下的一位英雄。

   天下除了曹操，还有刘备、孙权这两大英雄。刘备原来只是一个卖草鞋的，但他也做了皇帝，次次都从虎口脱险。有了诸葛亮后，如鱼得水，在汉中称帝，成为了一位英雄。而孙权也是一位英雄，他守住了他的父亲孙坚与他的哥哥孙策的基业，使曹操、刘备对他毫无办法。手下也有周瑜、吕蒙等谋士，还有凌统、周泰、丁奉等名将。

   在《三国演义》中，还有机智的诸葛亮、仁义的关羽、勇猛的张飞、老当益壮的黄忠和黄盖、号称曹魏第一将的曹仁等。

   在这么多英雄里，我最敬佩的是关羽关云长。关羽自从刘关张桃园三结义后，始终不离不弃，誓死追随刘备。虽然，后来投降了曹操，但也是迫不得已。斩颜良、诛文丑，可见关羽的英勇。后来听说刘备的下落，便立马离开了曹操，投奔了刘备，还千里走单骑，可见关羽的忠心。后来，虽然关羽在华容道放走了曹操，那也是他忠心的表现，因为曹操曾送他许多东西。后来关羽又水淹七军，天下闻名。但到了后来，关羽便骄傲了起来，最终导致兵败麦城。所以我们不能骄傲，要虚心听取别人的意见。

   这就是《三国演义》，一本描述群雄逐鹿年代的历史书。我们应该去认真地读一读。

** 万寿山一日游

   这个星期六，天气晴朗，阳光明媚，我们一行人浩浩荡荡地来到平水的万寿山水库。汽车开到了山脚停了下来，说是要去爬山。

   我们一步一步地朝山上走去，我们一开始的时候很有信心，决定爬到山顶。我们就开始往上爬，爬了一点路，发现就只有两个人在爬山了。那就是我和表弟。我们爬啊爬，爬到了半山腰。由于天气热，我们身上汗流不止。我们又走了很多路，腿也非常麻。表弟说：“铭哥，还爬不爬？”我说：“如果不爬了，那么我们刚刚爬的就全都浪费了。”我和表弟又有了信心，努力地爬着。后来，表弟又问我爬不爬了，实际上我心里也在想这个问题。如果爬还不知道又要爬多少路，的那如果不爬，不就半途而废了吗？到了表弟再次问的时候，我心中而是犹豫不决。后来，一想，还是爬了上去。终于，我们来到了山顶。虽然山顶上也不是“会当凌绝顶，一览众山小”，但风景还是不错的。我爬上了这么高的心，看着美景，一切疲劳一扫而光。

   通过这次爬山的经历，我觉得不只是爬山，做事也是一样。遇到挫折不要放弃，要克服困难，才能成功。

** 车站的一幕——看《假文盲》有感

   大家听说过文盲吗？文盲就是不识字的人。这对我们来说是很陌生的，但是生活中却有一些人宁愿当不识字的“文盲”，也不愿当一个有文化、有素质的人。

   这是一幅关于《假文盲》的漫画，讲述了在寒冷的一天，在公交车站的站点，立着一块十分醒目的牌子，上面写着“母子上车处”五个格外耀眼的大字。但我看着这幅漫画，就觉得很奇怪，这应该是妇女儿童等车的地方吧？怎么有四个身体强壮的男子在这里等车，把本应该有特权的母子挤在了一边。我看了一会儿，终于看懂了这幅漫画。我陷入了沉思。为什么本是母子上车处，却有四个完全不是母子的人站在那里，装成文盲。这些人虽然衣着华丽，但内心却是丑陋的。

   的确，社会上有好多不好的风气，比如草坪上大多有“不要践踏草坪”之类的标语，可真正又有几人去遵守并实行了呢？大多是为了方便，宁愿做一个“假文盲”，也不愿做一个有文化、有素质的人。

   还有垃圾桶，很多垃圾桶上贴着分类的标志，但真正扔对的人并不多。还有，很多事情都有着不好的风气，人们已经对这种坏风气少见多怪了。

   让我们一起改掉坏风气，不做“假文盲”，做一个有文化、有素质的人吧！

** 第一次烧烤

   自从在我五岁的时候，在我的爸爸单位组织下，我们曾经在兰亭森林公园进行了一次烧烤，那次的美味回味无穷，我就盼望着能再吃一次烧烤。

   机会终于来了，在上个星期六，阳光明媚的日子里，我们一行人浩浩荡荡地来到了月华山上烧烤。我们怀着兴奋的心情来到了烧烤的场地。但是由于风太大了，火点了几次都没有点燃。我们费了九牛二虎之力，想尽办法，终于把火点燃了。我们在上面铺上了锡箔纸，放上了要烤的鸡翅。我在鸡翅上面刷上油，还刷上了酱油，这样就更好吃了。过了大概十分钟，鸡翅烤熟了，散发着诱人的香气。我们每人都拿了一个。鸡翅金灿灿的，非常好吃。这个时候，奶奶爷爷在另一边烧红薯，我就一直在帮他们烧红薯，而我的表弟则兴致勃勃地把篮子拿出来，一个人在烧烤炉旁来回地帮助大家。这个时候，炉子里正在烧西兰花，由于西兰花很难烤熟，所以我们吃的都是半生不熟的。到了烧烤的中后期，基本上都是我和表弟在烧。表弟先把牛排和培根放进去，然后我在它们的表皮上涂上油汁以及酱油，烧了五六分钟，牛排就熟了。我不禁垂涎三尺，实在是太诱人了。咬了一口，我就忍不住再想咬一口。之后，我们就烤这次的主食——年糕和刀切馒头。而这个时候，我不在旁边，回来的时候，发现刀切馒头和年糕竟然有好多都烧焦了。我一问才知道，原来是表弟走开了，没人来管这个烧烤，所以才烧焦了。这个意外让我明白了做什么事都要一心一意，不可三心二意，否则做什么事都不会成功的。

** 阅读给我带来了快乐

   高尔基曾说过，“书是人类进步的阶梯”；莎士比亚也曾说过，“书是全世界最好的营养品”；刘向也曾说过“书犹药也，善读之可以医愚。”的确是这样，书可以给人带来无穷无尽的快乐与知识。在书中，我明白了做人的道理，世间万物的变化以及学习的意义。

   书，就像我的知心朋友、心灵伴侣。在我不开心时，还能帮我解除烦恼。《安徒生童话》和《格林童话》让我知道一个又一个既有趣又有意义的故事；凡尔纳的科幻小说令我流连忘返、回味无穷。当年明月的《明朝那些事儿》有厚厚的九本，我用了一个月时间把它看完了。从中，我知道了“以人为镜，可以明得失；以史为镜，可以知兴替。”《红楼梦》让我知道了中国古典文化的魅力；《三国演义》让我知道了那一段英雄辈出的时代；《水浒传》让我知道了朋友之间亲如手足的感情；《西游记》让我明白了只有经历磨炼，才能成功的道理。《唐诗三百首》让我知道了盛唐时期那璀璨的文化。此外，我还看过《雾都孤儿》、《百科全书》、《秘密花园》、《史记》、《红岩》、《狼王梦》、《山海经》以及金庸的武侠小说等。

   书更像一座永不熄灭的灯塔，引导我在知识的海洋中遨游，获得无穷无尽的知识。

   阅读能带给人快乐，就让我们一起阅读吧！[fn:20]

** “厉害了，我的兵”体验有感

   上个星期天，妈妈带着我参加了绍兴青少年活动组织的“厉害了，我的兵”活动。该活动有 12 个队，每队 3 人。各个队颜色都不一样。活动一共有三个环节。第一个环节是“负重搬运”，就是有头盔、背包、枪，然后 3 个队员各拿一样，搬着轮胎，类似接力赛。第二个环节是“固定打靶”，看哪队最好。第三个就是团队生存赛即真人 CS，最后根据总成绩选三组进入总决赛。

   第一个环节开始了，我们做好了充足的准备。不料竟然安排我们先去参加第二个环节即固定打靶。听老师介绍完之后，就让我们练习一下怎么打靶。到了真正要打靶的时候，我拿起枪，瞄准了靶，扣动了扳机，激光便射了出去，但是没有预期中的一闪。我一看原来是打偏了。之后，我又打了一枪。这一次因为我吸取了上一次的教训，所以就打中了。之后，我采用了一样的办法，但是由于只有一分钟的时间，所以我只打中了六枪。但是也还算不错了的。玩完了第二个环节的激光打靶，就开始了第一个环节负重对抗。最后我们组用了一分钟时间完成了这个环节。

   接着，我们要参与最后一个环节了。教官讲好了规则。之后，我们就开始了。第一局由于我才刚刚玩，所以并不怎么会玩。而且我们选的地方有很多人。所以我们这一队很快就“死”了。第二局我们选了一个人比较少的地方。突然，我看见前面有一个人，我连忙开枪射击，我的枪中出现了“OK”的声音，说明我打中了。没想到，我竟然也被那个人打中了一枪。我连忙蹲下，之后又开枪射击。经过好几分钟的激战，对面的那个人终于被“打死”了。而此时，比赛也结束了。这一次，我们仍旧没有拿到第一名。最后一局，我们商讨了战术，决定和别的一组联盟。我们这一次便成了个人分散作战。我在草丛附近，突然看到两旁的草丛旁竟然也有人，并且还有三个人。原来我在的地方人竟是这么多。所以，我马上就“死”了。虽然，我也杀了七个人，但我也“死”了。

   这一次“厉害了，我的兵”活动很有意思，既锻炼了身体，又增长了知识，真是一举两得啊！

** 做奶油泡芙

   昨天，爸爸带我一起上了由青少年活动中心组织的美点制作课程，这次做的是奶油泡芙。

   我们到了教室，按照老师的配方准备好食材，鸡蛋 6 个、低筋面粉 130 克、黄油 160 克、面粉 200 克用来做泡芙，黄油 80 克、面粉 100 克、糖 40 克用来做酥皮。酥皮是要盖在泡芙上面的。

   拿完了食材，就要开始做了。第一步就是把面粉用筛子筛一遍，这样会面粉会更干净一些。之后把黄油放进一只大的碗里，用打蛋机将它搅拌均匀，这可是一个很累的活。我们组用了九牛二虎之力才完成了这个任务。之后，把筛好的面粉放进去，再把它搅拌好，之后，再放进去鸡蛋，放完一个，搅拌好，再放一个，再搅拌。虽然说有 6 个鸡蛋，其实只要放 5 个就够了。与此同时，又派一个人去洗烤盘。洗完之后，用裱花袋将碗里的黄油装好。然后，在烤盘里挤出一个个泡芙的造型，泡芙就做好了。

   泡芙做完后，就要做酥皮了。酥皮就是用黄油和面粉以及糖粉合成的，之后用保鲜膜封好，最后用擀面杖擀一下，酥皮就完成了。把酥皮放入烤箱，烤十分钟。接着，用模具刻在酥皮上。之后，贴在泡芙上面，再放进烤箱去烤。

   过了二十多分钟，泡芙就烤成了。之后把泡芙的皮剥开，可以往里面放鲜奶油，也可以不放。

   这次做泡芙，让我知道了做一样东西是很麻烦的，既要有耐心，又要有方法和技术，真的要万事俱备才能行啊！

** 看电影《起跑线》有感

   看到“起跑线”这三个字，你一定想到了那句口号——不要让孩子输在起跑线上！

   这是一部印度电影的名字，《起跑线》讲述了为了不让孩子输在起跑线上，家长们费尽心思，千方百计送孩子进全市最有名的学校。片中男女主角拉吉和米塔夫妻也是一样的，他们尽管想让孩子上好的学校，但由于他们是开时装铺的，所以英语并不怎么好，与他们所居住的富人区格格不入。他们为了让女儿进名校，在多方面尝试后，仍然不能进入名校。他们最后只能装穷人，因为穷人能占名校 25%的名额。但是，一进入贫民区，就差点被发现了。而另一户真正的穷人却热心的帮助他们，而后来自己的孩子却落选了。然后，男主角拉吉就认为让自己的女儿去公立学校是自己剥夺了他们的权利。

   这部电影的题材非常大胆，批判了印度的教育。这仅仅是一个幼儿园啊，就如此费费尽心机。就在幼儿园，皮娅就丧失了自由。这让我想到我们中国。我们中国的教育又何尝不是如此呢！就拿我表弟来说吧！他就是一天到晚做作业，双休日上培训班，没有自由。

   家长为了让小孩子进入好的学校，用了各种方法，但到了好的学校未必就是最好的。

   这部电影非常好看，非常好看，希望可以再看一次。

** 一次难忘的学工活动

   这周星期四，学校组织了一次学工活动。今天，我早早地来到学校。等到全班同学都到了，我们就乘着大巴车来到了青少年活动中心。虽然青少年活动中心我以往也经常来，但我感觉这次来与前几次并不太一样。这次多了许多同学，与以前自己来不大一样了。

   今天整一天的学工主要是参加三个活动，是真人 CS、丛林探险、划船着三个项目。这个活动我以前都有玩过。其中最好玩的就是真人 CS 了。虽然这个真人 CS 我大概加上这次也来了七次了吧。

   真人 CS 项目开始了，先是老师讲解，之后，拿完装备就开始了野战对抗了。组完队，我就发现我们的队伍虽然人数多，但是以女生为主。对方虽然人少，但都是比较厉害的。

   第一局比赛开始了，由于我的枪不大好，所以我并没有怎么参与。后来等我枪调好了，比赛也就结束了。第一场比赛结束之后，一公布成绩，对方红队胜利。第一局输了，我们就开始了第二局。比赛开始了，交换了场地，我躲在一个废弃的油桶后，战斗开始后没超过两分钟，我就只剩下三条命（开局有五条命）。这两条命都是被队员打的。正是应了那句话“不怕神一样的对手，只怕猪一样的队友”。我一直静静地蹲在那儿，直到看见有一个人在轮胎后面，我拿起枪，枪托放在右肩上，眼睛看着瞄准镜，看到里面的红点，对准了头部，我便扣动扳机，过了几秒钟，我的枪发出了“OK”的叫声，说明我打中了对方。这时，我突然发现对面草丛里站着一个人，我仔细一看，原来是对方队伍的潘磊。我还是跟刚刚一样向他的头部射击，我射中他两次后，就发现他不见了。而另外一个人站了起来，我不知道是谁，但又被打中了两枪。之后，又被队友打了一枪，然后我就“死”了，来到了“烈士陵园”。之后，我们又玩了第三局，跟前两次也差不多，玩完了真人 CS，我们就去划船了。

   划船就是划一艘小船，六个人穿上救生衣，划着桨，划船划完之后，就是吃午饭了午饭后，休息了片刻，我们就进行了丛林探险了。丛林探险就是在树上开辟出来的道路上行走，也是非常好玩的。

   美好的时光总是很短，到了 2:30，我们就要离开青少年活动中心。这真是一次难忘的学工，也是小学里最后一次学工活动，最后一次学工就这么结束了！

** 读《鲁滨孙漂流记》有感

   我在三年级的时候，就看过这本书。而到了这个学期，我又重新在课文中看了一遍这篇文章。

   鲁滨孙是一个英国人，他喜欢冒险。一次冒险中遇到大风翻了船，同伴们都葬身海底，只有他一个人没有死，漂落到了一个没有人、没有食物的荒岛上。虽然是一个荒岛，鲁滨孙却在那儿生活了二十八年。二十八年，那么长的时间，有九千多天。有谁能像鲁滨孙一样，在荒无人烟的孤岛上生活了这么多时间呢？大概没有吧！

   鲁滨孙是一个非常厉害的人，他在一个荒岛建造出了他自己的家园。他有非常强的生存能力。而且他还很乐观，整整二十八年。没有人能这么乐观、有毅力吧？比如我做一件事，就没有像鲁滨孙一样乐观，也没那么有毅力。跟鲁滨孙相比，我就缺乏鲁滨孙这些精神。

   如果我像鲁滨孙一样，在这个荒岛上的话，我会像他一样生存下去吗？不会的，我没他的生存能力，也没有他那样乐观、有毅力。如果我看到野人，会像鲁滨孙一样，救出“星期五”吗？我也不会，因为我没有胆量。

   鲁滨孙是一个不惧艰险、有很强的生存能力、积极、乐观、有毅力的人。没有多少人会做得比他好。鲁滨孙值得我们学习，他是一个榜样。李白曾说过：“天生我材必有用”，人生下来都是有优点和缺点的。我们不应该在逆境中悲观，要像鲁滨孙一样艰苦奋斗。

   #+LATEX: \vspace*{\baselineskip}

   *读《鲁滨孙漂流记》有感（修改篇）*

   《鲁滨孙漂流记》这本书是一本名著，应该有很多人都看过吧！鲁滨孙是一个有毅力、乐观、不惧艰险、有极强生存能力的人，这么多品质中，我觉得他身上的毅力最令人佩服。

   鲁滨孙是一个英国人，他喜欢冒险。一次冒险中遇到大风翻了船，同伴们都葬身海底，只有他一个人没有死，漂落到了一个没有人、没有食物的荒岛上。虽然是一个荒岛，鲁滨孙却在那儿生活了二十八年。二十八年，那么长的时间，足足有九千多天。有谁能像鲁滨孙一样，在荒无人烟的孤岛上生活了这么多时间呢？大概没有吧！

   如果没有毅力，鲁滨孙一定不能活下去，他一定会死在岛上，绝不可能回到英国。正式因为有毅力，他才回到了文明社会。

   这就是毅力的体现，就拿我学游泳来说吧！一开始我学游泳，憋气始终没有多大进步，但我没有放弃，一直在家里脸盆中练习憋气，功夫不负有心人，终于憋气这一关通过了。接着我继续学习漂浮，眼看着我快要学会了，我的耳朵发炎了。等耳朵发炎治好后，我依然坚持学下去，终于我学会了游泳。这就是毅力，虽然一波三折，困难不断，但正是这种毅力才让我学会了游泳。毅力是不是有很强大的力量？

   的确，毅力是最最重要的，当一个人面对困难时，即使没有生存能力，只要有毅力，也能成功。拥有毅力，坚持下去，就能成功！

** 难忘的第一次

   生活中有些事情，会难以忘怀，并且时时萦绕于心。因为，你也许能从中不断地得到启示。

   这是两年前的事情了。那年暑假，妈妈给我请了一个游泳教练，教我和另外一个小朋友游泳。第一天，我兴高采烈地来到了游泳池旁。教练首先教我们屏气，我在池旁试了几下，以为我已经学会了，便一头扎入水中。但一入水，我在陆上学的动作就忘了。两三秒后，我的头便浮出了水面。之后，我又试了几次，跟第一次的情况也差不多。我的第一节课就这么泡汤了。之后，我又学了好几次课，但是我没有多大进步。妈妈一看这种情况，便给我换了一个老师，同时，在家让我抓紧练习憋气。

   于是，过了几天，我来到了另一个老师那里学。第一节课，仍旧是屏气。由于我已经学会了憋气，所以很轻松。第二节课，就是学漂浮了。我努力练习了很多次，终于能浮在水上了。眼看我快学完，再练几节课就可以学会了。但是这时我的耳朵发炎了，只能暂时停止练习了。眼看快要学成的游泳又中断了。

   后来我的耳朵好了，妈妈又说：“有个水上乐园可以学游泳，我可以报名了，明天就去学。”因为我两次都没有学会，不免有些心灰意冷，便说：“妈妈，学了两次都学不会，第三次也学不会的。”妈妈说：“宝剑锋从磨砺出，梅花香自苦寒来。只要多练习，游泳一定能学会的。”我便又有了信心，又有了想学下去的信心。

   之后，我来到了第三个游泳的场地开始学习了。这一次，由于前面打好了铺垫，而且我也认真地在练习，所以学习得非常快，很快就学会了很多动作。最后，我终于能独自一个人游泳了。

   这次游泳让我明白了，坚持就是胜利，如果我们做一件事，没有成功，但是坚持就一定能胜利。不管做什么事情，只要坚持就能成功！

** 除夕

   春节是所有传统节日中最隆重的节日，而除夕则是春节中最热闹的一天。

   到了除夕，春节的气氛额外得浓郁。大部分家庭会在自己的门上贴上红红的对联，意图吉祥。比如我们家贴的对联就是“福照家门万事兴，喜居宝地千年照。”

   到了差不多中午，我便来到了奶奶家，表弟也在。大家聚在一起，这样就更加热闹了。到哦吃午饭，桌上放着十几个装满了糖水的碗，绍兴人俗称“十碗头”。我们插上蜡烛，要先拜一下祖先。到了吃午饭的时候，桌上有鸡、鸭、鱼、肉、虾等等美味的佳肴。桌上差不多有十几碗菜，摆满了整个餐桌，散发着诱人的香气。在吃饭期间，我们还可以从长辈那里得到红包呢！但是，今年爷爷提出了一个要求，因为今年是狗年，必须说出一个带这个生肖的成语。如果说不出，就要扣一百块钱，而且不能用于手机查资料。经过一番思考。我和表弟终于如愿以偿地得到了红包。我的表弟一看到红包，便不管旁边有没有人，拆开了红包，一个人数着红包中钱的数量，数了一次又一次。以往吃完饭，我和表弟便会跟我下楼去放鞭炮，但现在要保护环境，所以市区不能放鞭炮了。

   到了除夕的晚上，就更加热闹了。家家灯火通宵，全城都是灯光。听爸爸说，除夕晚上以前是要看春晚的，但现在看春晚的人少了，大家都在抢红包，即使几毛几角也都很开心的。因为则会个红包抢到的不仅仅是钱，还有一些运气、心意和祝福。除夕这一天的确是热闹非凡的。

   虽然除夕只有一日，但我永远也忘不了这热闹的除夕。

** 我的理想

   每一个人都有一个自己的理想，有的想当警察，有的相当老师，有的想当医生。大家能猜到我的理想吗？应该猜不到吧！

   列夫 托尔斯泰曾说过：“理想是指路明灯，没有理想就没有坚定的方向；没有方向，就失去了前进的力量。”我的理想就是做一名历史老师。

   在两年前，我发现了一套《明朝那些事儿》的书，这本书里面的故事幽默生动，非常好看。于是，我便读了起来。之后，我便走进了一个新天地——那就是历史。

   随着我一天天地长大，我的历史知识也多了起来，对历史也越发充满了兴趣，对历史中的许多人物也十分佩服，如曹操、李世民、赵匡胤、朱元璋等，如果没有这些人物，那么历史就得改写了。

   为了获得更多知识，我不仅在看历史方面的书，还利用业余时间在一些听书软件上听一些有关历史的内容。听的效果要比看书的效果更好，因为这些听的内容比较幽默风趣，所以我在不知不觉中了解了历史。如果我以后当了历史老师，我也要将这样风趣、幽默、活泼的说话方式教给学生。

   但我深深地知道，作为一名历史老师并不是很简单的。不过加里宁曾说过：“只有自己提出伟大理想为之奋斗的人，才是最幸福的。”的确，人要立长志，不要长立志。既然有了理想，我们就应该朝着理想的方向前进，才能有一番作为。虽然说理想看似对我遥不可及，但世上无难事，只怕有心人。只要为理想而奋斗，理想终将会实现。

** 佛国圣境——游新昌大佛寺

   在前不久的一个星期六，春光明媚，晴空万里。我们怀着敬仰的心情来到了新昌的大佛寺。

   大佛寺始建于公元 345 年，距今已有 1600 多年的历史了。我们一行人浩浩荡荡地来到了大佛寺。

   我们来到入口处，首先映入我眼帘的是一个刻着“石城”两字的城墙。再往里走，就是大佛寺了。在大佛寺中，我发现里面的垃圾桶是一个可爱的小和尚提着两个水桶的形象，两个水桶便是垃圾桶了。我们走啊走，走了一会儿来到了双林石窟。双林石窟下面有瀑布，如同仙境一般。而从双林石窟一直往上面走，里面有亚洲第一卧佛。这个卧佛非常大，横跨整个石洞。这个如来侧卧在巨大的石头上，神态安详。

   去看完了卧佛，我们来到了放生池，放生池的水是绿色的，里面有很多小鱼。我看到了放生池旁边的两座山，上面写着“佛”和“放生池”这几个字。之后，我们穿过古朴的门，向前走着。我们进入了寺门，一步一步地往上走，我们首先进入了大雄宝殿。大雄宝殿跟我们绍兴的也差不多。我们继续往上走，功夫不负有心人，我们终于找到了江南第一大佛。江南第一大佛非常得大，能工巧匠真是非常伟大，竟然将如此大的一个佛雕的惟妙惟肖。他们真是值得我们佩服啊！我发现，无论从哪个角度，大佛都在慈祥地看着我。我觉得很神奇，更加佩服古时的人了，现代用高科技未必就有古时修得好。

   看完了江南第一大佛，时候不早了，我们匆忙回去了，还有不少景点没有去过呢。大佛寺一天的旅程结束了，希望以后还能再来。

** 理性的力量——参加科学演讲会有感

   在五一假期，让人期待已久的“理性的力量”科普大会年度演讲在绍兴大剧院火热举行！妈妈带着我参加了这次演讲会。

   偌大的一个大剧院里座无虚席，等了一会儿，讲座开始了，全场一下子静了下来。首先出场的是吴京平，他讲的是“SPACEX 的太空探索之旅”，讲述了美国以及俄罗斯航空的竞争以及相继上火星之梦的失败，让我了解了太空的奥秘。

   第二个出场的是王木头，他讲的是“生命的游戏：孕育生命”。他讲的比较深奥，所以不太听得懂。我这时才知道科学的博大精深，如果这是历史，我一定能听懂，所以我应该多方面发展。

   听了王木头演讲后，就是这次的主角——汪洁了，汪洁是绍兴人，他讲的是他的创作历程。他写过许多书，有《时间的形状》、《科学有故事》等。现在他拍了一部科普片，他给我们欣赏了一下。这部被他称为处女作、低成本、国产片的科普片，却让我感到非常好，并不是脑海中的烂片。

   然后，就是旭岽讲“可以预测的未来”，他的演讲让我知道了原来未来是可以预测的，我们可以预测 10 年、20 年、50 年、100 年、1000 年甚至一亿年，完全可以像当年明月一样写一部《未来那些事儿》。听完了他的演讲，我懂得了未来的一系列的危地，但转念一想，未来还有很长时间，跟我也没什么多大关系。

   之后，是思考盒子讲诉了外星人到底有没有，听了思考盒子的演讲，我知道了外星人只是一个可能的事情。

   这次演讲会让我热爱上科学，从此，我下定决心，排除万难，探索科学。

** 树人情

   十年树木，百年树人。我在树人小学度过了快乐、难忘、有意义的六年小学生涯。我从一个懵懂儿童长成了一个翩翩少年。在树人小学每一处留下我们的欢声笑话和难忘的足迹。

   六年内，我碰到了很多优秀的老师，老师像妈妈一样，伴随着我成长。她们不仅教授给我们丰富的课本知识，还教导我们做人的道理。难以忘记，我生病时，两位老师到我家来关心我的身体，嘘寒问暖，关心我的学习；难以忘记语文老师在学校里辅导我们怎样写作，让我学会了如何遣词造句；难以忘记班主任老师让我参加各种活动，给我鼓励。老师是辛勤的园丁，这句话一点也不假，正是老师才让我成长。

   六年内，我也碰到很多同学，他们也是像老师一样伴随我成长。难以忘记春秋游时同学间的欢声笑语；难以忘记每一次活动中的欢乐时光，难以忘记运动会时顽强拼搏，为班级争光；难以忘记同学之间朝夕相处的深厚情谊。

   我印象最深的还是五年级下的事。那一次，我生病了，妈妈让爸爸把我的作业拿回来，而爸爸到了教室却说没有找到作业本。这时，楼下传来“舒铭、舒铭”的喊声，我觉得很奇怪，心里想着这是谁啊？是邻居还是同学呢？就在我思索的时候，门铃叮叮地响了起来。我连忙去开门，发现门外站的是三位同学，原来是赵磊、陈赢舟、张昊炳，我起先以为他们是来做客的，后来才发现他们是来给我们送作业的。我的心中顿时非常感动。而且他们不光是送作业，而且还教我题目，让我体会到了同学之间的情谊。

   难忘怀，树人情。我们应该珍惜现在的一切时间，让我们珍惜最后的小学时光吧！

** 炎热的天气

   最近的一段时间，天气比较反常。虽说刚入夏，但这个星期，天气变得格外炎热，最高温度有个 36、37 度了吧，简直要热死人了，就拿我们班来说吧——

   我们班自从星期一升旗仪式结束后，就开始做扇子。做完扇子后，就可以用来扇风了，但还是很热。第二天大部分同学都戴上了校徽来取代红领巾，并且带上了从家里拿来的扇子。即使没有的，也在问别人借。天气一天比一天热，人人都穿上了短袖，要知道现在才五月份呢，就跟真正的夏天一样热。

   在我们家，也是一样。我一回家，就把空调开了起来。爸爸下班一回家，就进入空调间，拿出一瓶饮料喝了起来。这分明就是夏天，哪里是什么五月份啊！

   我在思考一个严肃的问题：为什么每年夏天都比上一年要热。我想到这是因为全球气温变暖，导致温度上升，经过长时间的积累，终于变得异常炎热了。如果气温再变暖，几十年后的夏天估计就五十摄氏度了。如果再不保护环境，那么人类就真的会灭亡。所以我们应该保护环境，珍惜环境。这样才能让我们拥有美好的家园，才能迎来美好的未来。

** 成长的烦恼

   每一个人都有一副属于自己的牙齿，每一个人都希望自己的牙齿洁白、美丽。我也不例外，但是我的牙齿带给我无尽的烦恼。

   从我一开始出生，牙齿是很好的。但是到了八九岁，自从乳牙换成了恒牙。牙齿就不是很好，而是很差了。

   比如说我上面的牙齿在门牙后面了，长偏了，而这颗牙齿右边的那颗牙齿也长得很差。这样让我的牙齿很不美观。还有很多牙齿也很差。

   为了牙齿美观，我还在网上查阅相关资料，这些资料基本上没有用，都是说要去医院矫正。我也是保护我的牙齿的，可我这一年的牙齿却都长得很差，有一颗甚至停在那，不往上长了。在最近这一年内我也经常去牙科医院，下个星期又要去了。总之，我的牙齿带给我无尽的烦恼。

   我每天都在认真地刷牙，但我的牙齿还是很差，这难道是我的运气太差了吗？这里难道有不少不为人知的奥秘吗？

   对于牙齿，我的内心充满了忧伤、脑中一片茫然，不知成长到底是有益还是无益……

** 温暖的父爱

   马上就要到六月下旬，在六月下旬有一个非同凡响的节日——父亲节。这让我想到了我的父亲。

   父爱如山，父爱像山一般深沉，我的父亲亦是如此。他拥有超人的智慧。当我在学习中，遇到不会做的题目，都是他教的。他帮我解决疑难，使我勇往直前。记得有一次，我在思索一道题目，这道题目比较难。而爸爸一看，几秒钟就想出来了。但我听了一遍、两遍，还是不懂。爸爸不厌其烦地教了我五六遍，直到把我教会了为止。

   父爱如山，父爱像山一般雄伟，我的父亲亦是如此。他非常地辛劳，每天早上给我们烧饭，还每天送我上学，非常地辛苦。不仅如此，他还在晚上烧美味的佳肴，让我们吃上了美味的食物。

   父亲除了之外，还非常的幽默。他的幽默给全家带来了快乐。当我郁闷时，他总能用他的幽默使我开心起来。

   的确，父爱如山，父爱的确像山一样，虽然不善于言表，但父爱还是很深的，是父爱让我在困难面前永不退缩，在遇到挫折时迎难而上，使我在生活中坚忍不拔。

   #+LATEX: \newpage

* 番外篇——抗战之中国英烈

  /作者对穿越的看法：/

  /这个穿越是有蝴蝶效应的，能改变历史的。/

** 穿越

   叮咚叮咚，特种兵徐方被闹铃吵醒了，他听见都泗门方向枪炮声阵阵。徐方想这不是在做梦吧？但这声音听起来不像是在做梦，也不像是在拍抗战片。他下床往窗口一看，忽见四外火光一片。他急匆匆套上鞋子，拿起桌上的手机，发现没了信号，就随手丢下手机，跑了出去。徐方跑到了都泗门时，天已大亮。此时，一大批鬼子冲了上来，而国军正在拼死抵挡敌军的进攻。徐方一看，觉得奇怪，难道穿越到了抗战？

   他不管三七二十一，拿起一支汉阳造，填了几发子弹，就开始朝着鬼子射击起来，几乎弹无虚发，阻挡住了鬼子的进攻。不一会儿，鬼子撤了下去。为首一名国军将领走了过来说：“兄弟，你真厉害，百发百中！”不过，又过了一会儿，一阵炮弹下来，一百多名鬼子上了刺刀，一起冲了上来。徐方大喝一声：“弟兄们，打！”一挺重机枪，两挺轻机枪，大量汉阳造的射向鬼子，大批的鬼子死了。鬼子又撤了下去。而这时候，抗战部队到了，鬼子不敢轻举妄动。这时，徐方说：“都泗门地形不利，要不撤到绍兴内城和鬼子打巷战吧！”国军将领李万军说：“不行，机不可失，一定要捍卫绍兴城！百姓还没有撤离，不能退出去。” 徐方一看也能勉强，只好同意了坚守。

** 激战

   徐方一看，看了看身旁的弟兄大概有三百来人。这时又是一阵炮击，至少两门步兵炮、四门迫击炮，一个炮兵中队的炮火。日军指挥部日军少佐叫山本腾三，他指着几个中、小队长叫骂到：“八嘎，正面战场势如破竹，你们几个混蛋，足足牺牲了一百多名皇军的性命，大日本帝国的脸面都让你们这群废物丢尽了。不要再用试探性进攻了，直接进攻！”“哈依”不少鬼子重重顿首。四五百个鬼子冲了过来，为首的鬼子中尉说：“帝国的勇士，杀丝改改。”但徐方也不是吃素的，一枪一个鬼子便一命呜呼了。一挺重机枪，一挺轻机枪，两挺歪把子射了下来，子弹像雨点一样，一大片鬼子倒了下来，但剩下的鬼子也开始接近阵地了。徐方说：“用手榴弹炸死这帮狗娘养的！”一百多颗手雷，炸得鬼子哭爹喊娘，又一次守住了。徐方说：“冲啊！弟兄们，打啊！”

   战士们势如破竹地冲了过去，每人拿着一把大刀，两方就开始了激烈的白刃战。徐方冲在最前面，大刀挥舞，砍下了不少鬼子的头颅，鬼子溃不成军。山本腾三拿起军刀，大喊：“八嘎，帝国的勇士，杀丝改改！”徐方一看，挥起明晃晃的大刀，向着山本这个鬼子砍了下去。山本连忙用军刀抵挡。徐方舞动着大刀，挥动如飞。趁着山本一不防备，一脚踢倒在地，一刀结果了性命。徐方他们取得了胜利，徐方说：“快打扫战场，等会鬼子增援部队到了，就麻烦了！”

** 整编

   徐方全歼了山本大队，缴获的物资不计其数，国军连长邵勇说：“妈的，咋这么多物资，鬼子他娘的真富裕。”

   不远处，几个人围住了一个人在哭泣。徐方走了过去，说：“让一下，让一下。”徐方一看是独立营的营长李万军，已经断气了。徐方问：“怎么回事？”另一个连长龙七说：“营座他被鬼子暗算了。”突然，李万军颤巍巍地说：“你打仗真行，从此独立营就交给你了，一定不能……”话没说完，便与世长辞了！徐方悲痛万分地说：“你放心，我一定能带好。”徐方数了一下现在独立营还有 207 人。徐方说：“君子报仇，十年不晚，我们不是君子，既然营座让鬼子杀了，我们要不要报仇？”叫喊声此起彼伏。这时候，不远处的邵勇过来说：“又有一百多鬼子过来了。”

   徐方说：“先拿这股鬼子开刀。邵勇，你带一个排埋伏在小树林旁，剩下的埋伏在这里。”鬼子过来了，看着鬼子全进了伏击圈，徐方说：“弟兄们打，打死这帮该死的鬼子。”说完拿起王八盒子，就是一枪，一名鬼子的头颅像皮球一样爆开了。邵勇拿起一挺机枪就扫了起来，，七八个鬼子便血肉模糊。打死了这些鬼子，邵勇说：“营座，这才这么一点鬼子，太少了，简直不堪一击。”徐方说：“这是一百多鬼子，我们要干掉全中国的鬼子，为营座报仇，把鬼子赶出中国。”清理完战场，徐方说：“这儿的鬼子不多，要不去上海打吧，那里有几十万鬼子。”众人说：“好！”两百名战士便赶去上海。经过一天一夜的急行军，大伙儿终于赶到了上海。

** 收编

   徐方一到泸淞战场发现军队已经开始撤退了。徐方一看时间已经 11 月份，历史上的撤退也是这个时候了。但是徐方一想，我可以在泸淞会战中把部队里的残兵、溃兵收拢起来，这样兵力就多了，打起鬼子来也更好了。就这样，徐方收拢了一些军队，有了一千多人。但是此时，日军已经占领上海，徐方一想便决定去华北参加八路军，不能在这儿浪费时间，应该立即突围。这个时候，侦察员报告大概有四千人从这里过来了，徐方听完后对警卫员说：“通知各连排长来这里开会。”十分钟后，大家都到齐了。徐方说：“目前大概有四千鬼子来这里，应该是来消灭我们的，说说你们的看法吧！”邵勇首先说：“对付鬼子一个字：打！打这些鬼子。现在我们占据有利地形，即使鬼子攻过来，咱们也能让他们付出惨重的代价。”投奔过来的国军营长万忠说：“打个屁，鬼子天上有飞机，地上有坦克，还有一门门的重炮，咱们就一千多人，根本经不住鬼子打的，一下就死光了。七十多万正规军都顶不住，以我们现在的状况，应该突围！”一旁的龙七说：“撤什么撤，周围都是鬼子，往哪儿撤？” 徐方说：“消耗这股鬼子，等有时机撤出去。”众人说：“好！”

** 突围

   日军一个中队来到徐方他们的地方，这是一支先头部队吧！徐方猜想，但是炮击已经开始了，两门迫击炮大展神威，向着徐方的阵地轰了过来。之后，一个小队的鬼子又冲了过来，徐方一看鬼子进入了有效射程，徐方拿起王八盒子就是一枪，“兵戈”一声，一个鬼子就丢了他的脑袋。邵勇拿起一挺机枪突突地扫射起来，转眼间鬼子死伤大半。徐方说：“冲啊！弟兄们。”一营的战士们人手一把大刀，如狼一样，不一会儿，鬼子的中队一百五十七名鬼子便丢掉了性命。一名鬼子联队长说：“八嘎，简直是群废物，竟然损失了一个中队的兵力。命令木下大队，务必挡住支那军，不能让支那军逃窜，待我联对主力到达，就是他们的死期。” 徐方打完胜仗，并没有大意，而是命令部队加强警戒，防止鬼子偷袭。徐方说：“咱们商量一下，往哪儿突围。”邵勇说：“东边，突围出去还有友军呢！”龙七说：“你傻啊！谁知道鬼子会不会派重兵呢？” 徐方说：“从北边突围，鬼子就几百人。可是那是鬼子的地界。鬼子绝对想不到。”就这样，徐方所率独立营，改编成了独立团。从北面成功突围到了南京，准备支援南京保卫战，但却气得鬼子哇哇暴叫。

** 备战南京

   徐方率领部队来到牛头山，趁鬼子还没有在打南京，在牛头山上打一个伏击。牛头山曾是岳飞大败金兀术的地方，从此大名远扬。而此时的徐方是想在这打鬼子后勤部队一个伏击。虽然没什么用，但也能稍微减轻一下正面战场的压力。徐方心里想决不能让南京大屠杀的悲剧重演，所以压力很重。而此时的独立团突围的时候也收编了一些兵马，兵力有小两千之众，且装备精良。

   现在徐方有着三个营的兵力，一营营长邵勇，下辖四个连。是独立团的主力，而二营的营长是龙七，下辖三个连。这两个人都是有独立营的底子，连营长都是，外加一些溃兵。而三营营长就是万忠，下辖三个营，都是一些残兵溃兵。

   徐方有一个警卫连，时刻保护他的安全。此外还有一个炮兵营，有八门破击炮和两门步兵炮。营长是黄埔高材生李云。此外还有侦察连班，还有一个特战班，特战班是徐方把近两千人中抽调枪法好的加入这个班。徐方知道是很强，这个班有三十二人。此外还有个参谋长叫刘国强。

** 又一个伏击

   徐方说：“召集连长以上的来开会。”过了一会，人员集齐，徐方说：“诸位，现在鬼子攻占完上海，一定会攻占南京的，我们要与南京守军一起坚守南京。大家说说看法吧！” 徐方为什么让大家思考，就是因为这样集思广益，才会有自己的想法来思考。邵勇首先发言：“我们应该争取外线作战，在鬼子的后方与敌周旋。”而龙七却说：“我们应该与南京守军一起坚守阵地。” 徐方说：“按邵勇所说的办，此外，多收集船只。”万忠问：“收集船只有什么用？” 徐方微微一笑，我可深知就是因为没船，南京城里的居民没多少撤离出来，才造成了南京大屠杀的惨剧。这时，侦察兵进来说：“报告，五里外发现一千多鬼子。” 徐方闻言从桌上拿起望远镜一看，还真有一千多鬼子朝这里走来。徐方说：“才行一场伏击，一营在左翼，二营在右翼，三营负责阻挡支援的鬼子，回去准备吧！”鬼子不知道他们即将魂归天外。

** 激战牛头山

   邵勇看着鬼子进入了伏击圈内，说了一声打，一百多颗手榴弹便扔了下来。炸得鬼子原本整齐的队伍顿时混乱了。徐方带着特站班，游动在鬼子身边，徐方一抬枪，一名鬼子便倒下了。而三营却遭到了周围一千多名鬼子的猛攻。

   在三营阵地，万忠拿着他的三个连，愣是抵挡两个大队的鬼子。他拿起一挺歪把子扫了起来，旁边的警卫班班长张雷走了过来说：“营座，弟兄们越来越少了，都已经不到两个连了。鬼子太多了，要不撤吧？” 万忠说：“不行，如果一撤，团长他们就危险了，顶住！”

   在伏击阵地，徐方拿起一支三八大盖，瞄准了一名鬼子，砰的一声，一名鬼子便魂飞魄散。这时，警卫员李三强走了过来说：“团座，三营顶不住了，损失惨重，怎么办？” 徐方一听说这个消息便问来了多少人。李三强答道：“两千来人。” 徐方闻言说：“带上特战班，随我走。”

** 死守阵地

   徐方到了三营阵地，发现三营也就一个连的兵力了。

   徐方拿起一支三八大盖，射向一名鬼子。那名鬼子便中弹倒地。徐方连忙一个卧倒，因为鬼子的一挺机枪向他扫了过来。徐方说：“射鬼子的机枪手与军官。” 徐方每发一枪，便有一名鬼子倒下。而伏击阵地那儿，一营和二营已经在打扫物资了。徐方知道后，立刻带着三营剩下的部队撤了出来。而鬼子由于天黑了，便也没有追。徐方已经得知部队伤亡人数，便皱了一下眉，因为一天就损失了四百七十六名弟兄，还有伤员近三百名。而鬼子虽说歼灭两千来人，但却还有两千人。明天仗该怎么打？徐方在心里盘算了起来。他可深知鬼子正在攻打南京，可有二十多万人呢！自己得谨慎对待啊！

** 毒气弹

   徐方一想，有了，我不是缴获了一些毒气弹吗？不是可以用吗？徐方喊来三个营长，说：“这次我们使用毒气弹来对付鬼子！”龙七说：“什么时候发起进攻？” 徐方答道：“现在是凌晨三点，我们三点半发起进攻！一营打主攻。”过了一会儿，徐方一看已经三点二十八分了，就对警卫员说：“命令炮兵营开火。一营戴上防毒面具，发起进攻！”

   /炮兵阵地/

   李云一看时间快到了，便说：“放！”顿时一发发炮弹落入敌阵。

   /日军大帐/

   青田大队长与吉田大队长正在交谈，突然听到一阵炮响。青田说：“吉田君，支那进攻发起炮了。”这时，一名大尉走了进来说：“报告两位少佐阁下，支那放的是毒气。”吉田鬼子说：“防毒面具呢？”“没有多带，吉田君。”青田说。这时一营的战士已经杀入敌阵，杀得鬼子大败。而这时徐方在想我现在应该怎么支援呢？正面呢？不如用特战班去骚扰鬼子吧！这是战斗已经结束了。徐方说：“你们撤吧！我带着特战班之后便去打鬼子。”

** 特种作战

   徐方带着特战班等到了天黑，便来到了雨花台。徐方对大伙儿说：“我们这次的重点是打炮阵地和坦克，明白了吗？”于是，大家往每一个营帐里扔一个手榴弹，几十个手榴弹飞了出去，顿时火光阵阵。这时，旁边有几十个鬼子走了过来。徐方说：“打！”二十几挺捷克式疯狂地扫了起来，在密集的火力网下，日军死伤惨重。徐方又说：“走！”他们来到了炮兵阵地，发现炮兵阵地上有一个中队的日军。徐方说：“打！”二十几挺捷克式的火力异常猛烈。顿时一个中队的鬼子便死伤殆尽。徐方拿起了手榴弹，便一扔，炮全成了废铁。徐方一看，旁边有八辆坦克，徐方说了声“隐蔽”之后他看了一下，不过一个小队的鬼子，便打了起来，不一会儿，便扫清了。徐方说：“进去，咱们也开开坦克！”八辆坦克便冲了出去，如狼入羊群一样，打了鬼子一个措手不及，队伍顿时乱了起来。徐方操纵着坦克上的机枪疯狂地扫射起来。而雨花台的守军也趁势反攻。第六师团越发抵挡不住，往后撤了。

** 准备——机枪的怒吼

   在双重打击下，日军往后撤退，徐方却没有停留，而是撤到了下关码头附近，与主力部队会合。徐方来到了指挥部，见到了刘国强，问刘：“现在情况怎么样了？”刘国强忧心忡忡地说：“船还是太少，最多一次运千余人。”徐方说：“估计南京再过两天就会失守了，我们这儿是必经之路，现在只有延缓他们了。”“调一个连的兵力，全带机枪。”“好的”刘国强下去准备了。不一会儿，一个全带机枪的机枪连便准备好了。徐方说：“我们要去雨花台，协助守军守阵地，待会我们去打一下鬼子。” 徐方他们来到了雨花台日军的后方，徐方说：“打！”一百多挺歪把子发出了吼声，对着没有任何防备的鬼子。这些人都是辅兵，有工兵、骑兵、炮兵、医务兵，相比用于战斗差距是很大的。

   日军一个师团的编制有甲乙丙丁四种，日军 1 到 20 加近工师团（缺 13、15、17、18）是常备师团，辖两旅团（一旅团二联队），工、骑、炮、镏各一联队。还有丙种师团，与丁种师团并不常见。还有独立混成旅团。而面前的是日军常备师团第六师团，也是日军六老牌师团。又补充一些兵员，所以有 3 万余人了。但是也经不住这么打。战士们一路冲了过去，快速碾压日军。

** 休整

   徐方又一次歼灭日军一千余人，取得了大捷。但他不知道日军已经盯上了他。

   日军指挥部松井石根大将正在大发雷霆：“八嘎，谷寿夫这个混蛋，他一个师团还攻占不了雨花台，五天了，还损失惨重，第六师团竟如此愚蠢。”这时，旁边的参谋长说：“这两次袭击听说都是徐方的独立团所为。这支部队非常得狡猾。我看了一下他的资料，此人 10 月份用一个营击败我皇军一个大队。之后在上海补充兵员，从我大日本皇军一个联队的包围圈中突围。之后在南京伏击了我军一个大队。之后，我军支援的两个大队被狡猾的支那人用毒气打溃我军。之后仅用二十余人把第六师团打得灰头土脸，与守军一同击溃我军。之后，运用一个机枪连歼灭我军一千余人的辅兵。”松井石根说：“真是狡猾的支那人，他现在在哪里?”另一个参谋说：“下关码头。”松井石根说：“支那人一档想帮守军撤出来支援守军。命令重滕支队去支援谷寿夫，让支那军撤到码头，一起歼灭。”

** 南京失守

   自 10 日起，日军大举增兵，又加入了一个 114 师团，兵力是守军的一倍还多，向 262 旅阵地发起了猛攻。下午的时候，262 旅只剩下了一百多人。264 旅也就剩下二百多人。鬼子又发起了进攻，朱赤旅长拿起了机枪喊道：“宁做战死鬼，不做亡国奴。”说完便与鬼子进行了残酷的白刃站，与此同时，264 旅阵地站进行着白刃战。

   12 月 11 日，中华门失守，南京已无险可守。南京卫戎司令唐生智下令部队撤退，但十分混乱。八十八师乘着辎重营的三百余条船撤离，七十四军的俞济时乘着一艘汽轮，运走了四千多人。而六十三军军长叶肇和八十三军军长邓光从光华门突围。其余部队则撤到了下关码头，但是下关码头却没有一条船。因为守卫南京时，把船都销毁了。码头上场面十分混乱。这时，徐方率领独立团走了出来，说：“我们有船，百姓先上船，老人、孩子、妇女优先。”底下的士兵说：“我们为什么不能上船？”“对啊！对啊！”人群骚动了起来。徐方拿起手枪朝着天空打了一下，说：“这船上，我安了炸药，谁过来，我就炸了船，一起与南京共存亡！”溃兵们说：“不要，我们听你的。” 徐方说：“百姓们快上船。”坐着木船的百姓开始渡江。

** 喋血码头

   但好景不长，过了一会儿，鬼子的部队便立刻赶到了码头。徐方说：“一营跟我去阻击鬼子，二营掩护过河。” 徐方带着一营在码头旁抵挡鬼子。他拿起一挺机枪猛烈扫射了起来，其他战士也在死命地支撑着。突然，空中几十架战机从空中轰响了起来。这些飞机从低空掠过，朝着密集的炸弹，一枚枚炸弹便炸了下来，人群顿时乱了起来，而鬼子的炮弹也呼啸而下，给独立团造成了不小的伤亡。而过河的船只也被鬼子的炮艇炸掉了许多。徐方心中气愤无比。阵地马上就要失守了，还好此时的南京市市长萧岭带着一批官兵赶来支援，稳住了局面。徐方说：“鬼子封锁了江面，很多船只都被打掉了。萧司令你快过江吧！这儿我撑着。”萧岭说：“徐团长，你先走！”这时，一名战士走了过来说：“报告，鬼子增援了兵力，第一道防线快要撑不住了。” 徐方一看说：“特战班的跟我走，去支援！”

   徐方带着特战班，来到了第一道防线，发现阵地已经岌岌可危。徐方连忙命令特战班立刻进攻。特战班有二十三几乎是每人都有一挺歪把子。二十几挺歪把子向着鬼子扫射了起来。一大片鬼子顿时倒下了。战士们便开始反击了，与鬼子进行了白刃战。徐方拿起一把刺刀冲向敌阵。这时，一名鬼子朝他刺了过来。徐方拿起刺刀一抹，这名鬼子便倒下了。徐方如狼入羊群一般，对鬼子进行了屠杀。这时，码头上已经没多少人了。徐方便带领部队乘着小船来到了对岸。之后，徐方便带着独立团北上山东，参加八路军。

** 改编与休整

   徐方北上山东，在山东省沂蒙山，参加了八路军。上级给他配来了一个叫苏宾的政委。番号为沂蒙山抗日独立团。徐方现在下辖二个营，一营营长是邵勇，拥有两个连，二营营长是龙七，有两个连。此外还有一个警卫连和医疗队和后勤队、特战班。在休整了一个月后，徐方有了三千多人。除了八百多人原独立团的老兵，还拥有了一个六百多人的县大队和一千多人的民兵和两三百的新兵。拥有了三千多人，有了一定的实力。徐方知道徐州会战要打了，命令部队加强训练。徐方所部下辖五个营，一营和二营是王牌，由老兵组成，三营是由县大队为主要力量，四营则是以新兵为主，五营则以民兵为主。

** 徐州会战爆发

   1938 年一月，日军进攻山东，山东省主席韩复渠不战自溃，几乎没放一枪，导致黄河天险失守，济南沦陷。韩复榘后被军委会枪决，徐方知道在徐州鬼子吃不到任何便宜，还几乎被全歼了第十师团。但徐方还是想历练一下新兵。他决定攻击附近的鬼子减轻周围的压力。就这样，徐方带三、四、五营各一连，外加一个特战班出去扫荡。徐方一看周围在不少碉堡炮楼。徐方带着部队就出去攻打了。徐方他们来到了一个炮楼附近，徐方说朝天开枪，小五百人朝天开枪，枪声很密集，里面的鬼子非常惊慌。徐方说：“特战班随我走！”鬼子被枪声吸引，没想到特战班从天而降十几颗手榴弹。乘着这个时候，徐方发起了反攻。眨眼间，徐方已经冲了进去，他说：“把鬼子衣服扒了，特战班的穿上，不管死不死，都补一刀。”随着徐方的命令，战士们开始了补刀。徐方让各处部队进攻炮楼、碉堡，锻炼战斗力。

** 二月整训

   徐方知道现在要尽快发展部队战斗力，提升部队素质，才有一战之力。徐方的独立团经过两个月的整顿和招编，已经发展到了上万人。虽然，部队有一万来人，但装备不足，而且成了山东日军的眼中钉、肉中刺，驻守山东的日军第五师团以及第五旅团决定向沂蒙山发起进攻。但是徐方也深知自己这支部队是精锐之师，经常打碉堡，可谓不是乌合之众，而且，沂蒙山虽然没有什么大的要塞，但是以现在的攻势，以日军的精锐之师，很难打下来，更重要的是，日军的第五师团虽然在台儿庄战役中虽然没有被歼灭，但也受到重创，战斗力并没有以前这么强，但日军的第五旅团也不过七八千人，并没有多少用处。徐方现在的特战队已经有近万号人，战斗比较强，真的是一支特战兵了。当徐方现在才懂得“强兵再丑，仍然是天下无敌”的意思了。他思索着应该如何支援兰封（徐州）会战。因为现在第二次徐州会战又要开始了。日军抽调 40 万人想全歼徐州水军。徐州守军并没有撤退，而仍然坚守。徐方知道虽然自己撤退也没有问题，但是自己这支沂蒙山武装部队就会立马被山东的日军消灭掉。他现在想尽一切努力扩大兵力，增加实力。不过现在徐方的兵由原先的八百多到现在的一万之众，所辖 5 个营的兵力。虽说是营，实则已和营相似，而且这五个营就有一万余人，外加炮兵、民兵，然后后勤部队，已有一万五千多人，再加上沂蒙山的民众等，加在一起共有三万多人，已是山东最强的武装了。

** 强敌来袭
   徐方在沂蒙山附近设置了很多外围据点，总共有五千多人，而日军却派出了三万多人进攻各个小据点。小据点并不是什么关卡要塞，但徐方的部队有一个优势就是沂蒙山训练出来的特种部队技术力量强，一个能抵十个，战斗力极强，拥有很强的火力和战斗力。若没有这些特战兵，这些据点早就被日军占领了。有了特战队，特战队的将领往后面一冲，冲垮了日军的阵营，日军就无法再猛攻了。日军已经损失了三千多人。但已经攻下了外围的据点，马上就要进攻沂蒙山了。但徐方还是实力很强，他目前所率领的一万两千多人并没有损失多少，他决定死守沂蒙山。日军第五师团指挥部板藤孙四郎对着下面的副官说：“炮火准备好，强攻沂蒙山！”身边的副官连忙应声到：“哈衣”。

   一天后，日军第五师团所率的四个连队中的三个连队从山的东、西、北三面向上攻击。徐方连忙拿出望远镜向远处瞭望，发现每个地方都有上千名日军。徐方大喝一声：“打！”他知道山的东面防御设施是最不牢固的，所以他先去守卫山的东面。一股日军小队往上冲，徐方拿起就是一枪，一个鬼子便应声倒下，其他鬼子发现了他，拿起九二式重机枪疯狂地扫射起来。但是并没有什么用，在徐方旁边的一名特战队员立刻拿起一挺冲锋枪进行火力反射，那个拿九二式重机枪的鬼子和周围的几个鬼子即刻死于非命，徐方趁机拿起他的三八大盖连续射倒了十几个人。由于徐方和特战队的强力救援，整个山的东面已经安然无恙了，日军的进攻也不如第一次那么猛烈。两三天内是攻不下来的。徐方就去了山的西面，等他来到那里，拿起他的三八大盖“砰”的一枪，只听“并嘎”一声，一名鬼子应声而倒。但是，徐方突然看起有一个枪口正对准了他，他立刻低头，但脸还是被飞来的子弹擦伤了，徐方一看，在树的后面有一个鬼子，这个鬼子枪法不错。徐方连忙把三八大盖往那方向一射，没想到的是，这三八大盖竟然没有子弹了，这时，那个鬼子的子弹已经射了出来，徐方连忙趴下，这枪没有打中，徐方一看，自己没有子弹，没有还手之力了，只能拔出刺刀冲了过去，和鬼子进行肉搏战。徐方刺了几刀，但没有刺中，他的拼刺技术已经很高了，但是毕竟跟着徐方来的是特战队，跟着这个日军来的是一个班，特战队的乙二走了过来，一看自己的司令官在拼刺刀，连忙拿起一把枪，扫了几枪，这时，特战兵前来支援徐方，双方展开了激战。徐方一看，心里想到：哎，现在的鬼子战斗力还是蛮强的，所以我军更应该消耗日军的主力，号称“日军之花”的关东军战斗力是否更应强大？正在徐方胡思乱想中，突然旁边跑来一名警卫员，向他报告：“司令官，山的南面快守不住了！”徐方深知山的南面虽山势险要，但守军人数不多，只有一千多人，是第三团在守卫，第三团虽然成军早，但部队战斗力和素质都不行。徐方一看，感觉来到了山南方，有了徐方和特战队的支援，山的南方也守住了。这样一来，日军白忙活了一场，还死伤了不少人。板藤孙四郎对沂蒙山的部队有了新的认识，这支部队确实能征善战。

   /流血山坡/

   日军第五师团及第五旅团向山的四面八方进行了围攻，利用强大的火力进行进攻。并且日本士兵奋不顾身，而且天上每天都有飞机在空中轰炸，五天下来，徐方的头都大了。不是山的东面告急，就是山的西面告急，徐方非常生气，自己的部队不是也有枪有炮，怎么会有这么多问题，而且徐方发现了一个更大的问题，他的部队子弹不够，他是有一个小的兵工厂，但他的兵工厂没有什么实力，产量太少，一个月才生产几十个。而徐方的独立支队（独立营改成独立支队）这十几天下来，损失惨重，就是特战队，就死了十多个，伤了二十多个，打到后来，特战队也无多少战斗力了。整个山很战势很紧，徐方犯难了，日军火力很猛，机枪“吐吐”的响个不停，山的三个面全面告急，我方弹尽粮绝，怎么办？

   /夜袭/

   日军第五师团及第五旅团板藤孙四郎忙对着下面的人说：“今天再发动夜袭，命令第七大队整个大队全力进攻！” 第七大队大队长报川德众，这个大队在十六七天伤亡不大，现在还剩下五百多人，而且战斗力强。到了晚上，第七大队带着五百人悄悄出击，而此时，徐方正在研究地图，希望他的部队能够度过难关，因为现在部队已经伤亡了五千多人，报川德众带着精锐部队，五百多挺歪把子强烈开火。山的东面抵挡不住强大的火力，立即告急。

   /撤军/

   /（本文为纪念抗日战争胜利 73 年而作，系原创小说，未完待续。）/

* Footnotes

[fn:22] 此句原文如此，推测其大意为安全区内攻击无效的意思
[fn:21] 本文在学区“五水共治”征文比赛中获三等奖
[fn:20] 本文于 2018 年 5 月在绍兴晚报“我的读书故事”主题征文大赛获奖，并刊登在第 8805 期花季版
[fn:19] 2018 年 5 月 5 日发给秋老师，参加越城区“安戈洛杯”青山绿水 美丽家园主题征文活动，获得校级二等奖。（六年级 1 个一等奖，3 个二等奖）
[fn:18] 本文发表在《树人研究》2017 年 6 月第 11 期百草集萃栏目（P96）
[fn:17] 本文参加第十八届华人少年作文比赛绍兴市征文 2017 年 6 月份投稿
[fn:16] 该文于 2016 年 11 月 22 日参加“美丽家乡  快乐童谣”新绍兴童谣创作活动征文比赛，并获校一等奖
[fn:15] 本文参加绍兴晚报组织的 7 月 30 日东浦黄酒小镇开耕节小记者亲子家庭体验活动后投稿，并发表在《绍兴晚报》2016 年 8 月 13 日 A10 花季版
[fn:14] 本文参加“国旗下讲话”之“爱我中华”征文投稿
[fn:13] 本文参加以 2016 年 2 月在校“我最喜欢的一本书（刊）”为主题的征文活动中获三等奖
[fn:12] 2016 年 2 月 12 日在佳作网投稿，参与“三爱征文 - 扣好人生第一粒扣子”活动
[fn:11] 该文在 2015 年首届“江浙沪新少年作文大赛——重写《从百草园到三味书屋》”中荣获鼓励奖
[fn:10] 本文发表在绍兴晚报 2015 年 9 月 22 日求学导刊 B6 版特刊 小记手记
[fn:9]  本文于 2015 年 5 月份投稿绍兴市第六届“我与好书为伴，践行核心价值观”读书活动
[fn:8]  本文于 2015 年 5 月投稿“小试牛刀”
[fn:7]  “我的中国梦”演讲稿
[fn:6]  李芳写，参加“感恩亲情，共同成长”家长征文
[fn:5]  舒铭写，参加“感恩亲情，共同成长”学生征文
[fn:4]  本文发表在《树人研究 学生版》2013 年 6 月第七期
[fn:3]  2013 年 3 月 7 日星期四的作业，写在绍兴 E 网论坛教育版
[fn:2]  本文于 2013 年 3 月 1 日参加征文活动
[fn:1]  本文发表于绍兴广播电视报第 38 期（2012 年 9 月 21 日出版）第 27 版
